<?php
/** Feature Bingo cards - Asset Management: lists, custom fields, import, inventory agent, vCenter, Intune, labels, handover, expiries. See includes/feature_bingo.php for the format. */
return [
    // --- The lists every asset is sorted by ------------------------------
    [
        'id'       => 'assets.asset_types',
        'module'   => 'assets',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Asset types',
        'what'     => 'The categories assets are sorted into - laptop, desktop, server, monitor, phone and so on. Every asset is given one.',
        'why'      => 'The asset list is grouped and filtered by type, and custom fields hang off it. Without types, a printer and a laptop look like the same kind of thing.',
        'done'     => 'At least one asset type exists (demo data not counted).',
        'link'     => 'asset-management/settings/?tab=asset-types',
        'check'    => ['rows', 'asset_types', 'is_demo = 0'],
    ],
    [
        'id'       => 'assets.asset_statuses',
        'module'   => 'assets',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Asset statuses',
        'what'     => 'The lifecycle states an asset can be in - for example In use, In stock, In repair or Retired.',
        'why'      => 'A status tells you at a glance whether a machine is on somebody\'s desk, on a shelf ready to issue, or waiting for disposal, so spare stock is not bought twice.',
        'done'     => 'At least one asset status exists (demo data not counted).',
        'link'     => 'asset-management/settings/?tab=asset-statuses',
        'check'    => ['rows', 'asset_status_types', 'is_demo = 0'],
    ],
    [
        'id'       => 'assets.type_icons',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Icons for asset types',
        'what'     => 'An icon chosen for each asset type, shown beside assets of that type.',
        'why'      => 'In a long list an icon picks out the servers from the laptops faster than reading a column.',
        'done'     => 'At least one asset type has an icon chosen (demo data not counted).',
        'link'     => 'asset-management/settings/?tab=asset-types',
        'check'    => ['rows', 'asset_types', 'icon_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'assets.locations',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Locations',
        'what'     => 'A tree of places your equipment lives - country, site, building, room - nested as deep as you need.',
        'why'      => 'When a machine fails or goes missing you need to know where it physically is. It also lets you count what is in each office before a move or a refresh.',
        'done'     => 'At least one location exists.',
        'link'     => 'asset-management/settings/?tab=locations',
        'check'    => ['rows', 'asset_locations'],
    ],
    [
        'id'       => 'assets.shared_locations',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Locations shared by every company',
        'what'     => 'A location every company on the install can pick, such as a shared data centre or head office.',
        'why'      => 'If you look after several companies from one building, recording that building once saves keeping a copy of it per company that drifts apart.',
        'done'     => 'At least one location is marked as shared.',
        'link'     => 'asset-management/settings/?tab=locations',
        'check'    => ['rows', 'asset_locations', 'is_shared = 1'],
    ],
    [
        'id'       => 'assets.asset_suppliers',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Suppliers you buy hardware from',
        'what'     => 'Suppliers from the shared supplier registry marked as available to pick on an asset.',
        'why'      => 'When a disk fails under warranty you need to know who sold you the machine. Contracts uses the same supplier record, so the details are kept in one place.',
        'done'     => 'At least one active supplier is marked as available for assets (demo data not counted).',
        'link'     => 'asset-management/settings/?tab=suppliers',
        'check'    => ['rows', 'suppliers', 'supplies_assets = 1 AND is_active = 1 AND is_demo = 0'],
    ],

    // --- Getting assets in -----------------------------------------------
    [
        'id'       => 'assets.inventory_script',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'integrations',
        'title'    => 'Inventory script on your PCs',
        'what'     => 'A PowerShell script, scheduled on each Windows machine, that reports hardware, disks, network adapters, Device Manager and installed software to FreeITSM.',
        'why'      => 'Nobody keeps a hand-typed asset list accurate. Once the script runs on a schedule, new machines appear by themselves and the specification, logged-in user and free disk space stay current.',
        'done'     => 'The script has reported at least one machine (disk or Device Manager data received from the agent).',
        'link'     => 'asset-management/help.php',
        'check'    => ['any', [
            ['rows', 'asset_disks', "source = 'agent'"],
            ['rows', 'asset_devices'],
        ]],
    ],
    [
        'id'       => 'assets.manual_assets',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Equipment no agent reports',
        'what'     => 'Assets added by hand - printers, monitors, headsets, phones, televisions - that no inventory script or sync will ever find.',
        'why'      => 'The agent only sees Windows PCs. The kit people borrow, lose and break most often is usually everything else.',
        'done'     => 'At least one asset exists that no agent or sync has reported (demo data not counted).',
        'link'     => 'asset-management/',
        'check'    => ['rows', 'assets', 'last_seen IS NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'assets.import',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Import assets from a spreadsheet',
        'what'     => 'A wizard that reads a CSV, maps its columns to asset fields, decides which column identifies a row, previews the result and then imports it.',
        'why'      => 'A supplier stock list or an old spreadsheet can be brought in in minutes, and importing the updated file again updates the same records rather than duplicating them.',
        'done'     => 'At least one live (not preview) import has been run.',
        'link'     => 'asset-management/settings/?tab=import',
        'check'    => ['rows', 'asset_import_runs', "mode = 'live'"],
    ],
    [
        'id'       => 'assets.vcenter',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'VMware vCenter connection',
        'what'     => 'The server name and credentials FreeITSM uses to read your virtual machines from vCenter\'s REST API.',
        'why'      => 'Virtual machines never run the inventory script from a desk. Connecting vCenter puts every VM, its host, cluster, CPU, memory and storage in the same place as the physical estate.',
        'done'     => 'A vCenter server address has been saved.',
        'link'     => 'asset-management/settings/?tab=vcenter',
        'check'    => ['setting', 'vcenter_server', 'nonempty'],
    ],
    [
        'id'       => 'assets.vcenter_synced',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Virtual machines synced',
        'what'     => 'The Servers page, filled from a vCenter sync, with totals and a searchable table of every VM.',
        'why'      => 'Saving the credentials does nothing until a sync runs; this is the point where you can actually answer "which host is that VM on".',
        'done'     => 'At least one virtual machine has been synced from vCenter.',
        'link'     => 'asset-management/servers/',
        'check'    => ['rows', 'servers'],
    ],
    [
        // PR #167
        'id'       => 'assets.proxmox_synced',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Proxmox VE virtual machines synced',
        'what'     => 'One or more Proxmox VE servers, read with an API token, filling the Servers page with their VMs and containers, IP and MAC addresses.',
        'why'      => 'An estate on Proxmox sits beside vCenter in one list, and a VM is only removed when Proxmox itself no longer has it - never because a node was down.',
        'done'     => 'At least one VM or container has been synced from Proxmox.',
        'link'     => 'asset-management/settings/?tab=proxmox',
        'check'    => ['rows', 'proxmox_vms'],
    ],
    [
        // PR #167
        'id'       => 'assets.vcloud_synced',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Cloud Director virtual machines synced',
        'what'     => 'One or more VMware Cloud Director servers, read per organization, filling the Servers page with their VMs and listing their edge gateways.',
        'why'      => 'Hosted and provider estates appear in the same Servers list as everything on-premises, with each VM\'s network cards, addresses and disks.',
        'done'     => 'At least one VM has been synced from Cloud Director.',
        'link'     => 'asset-management/settings/?tab=vcloud',
        'check'    => ['rows', 'vcloud_vms'],
    ],
    [
        'id'       => 'assets.intune',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Microsoft Intune connection',
        'what'     => 'An Azure AD app registration (tenant ID, client ID and secret) that lets FreeITSM read managed devices through Microsoft Graph.',
        'why'      => 'If your laptops and phones are enrolled in Intune, it already knows their serials, owners, compliance and encryption state - there is no need to deploy a script to learn it again.',
        'done'     => 'An Intune tenant ID, client ID and client secret have all been saved.',
        'link'     => 'asset-management/settings/?tab=intune',
        'check'    => ['all', [
            ['setting', 'intune_tenant_id', 'nonempty'],
            ['setting', 'intune_client_id', 'nonempty'],
            ['setting', 'intune_client_secret', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'assets.intune_synced',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Intune devices synced',
        'what'     => 'A device sync from Intune, creating or matching an asset for each managed device.',
        'why'      => 'Phones and tablets never run the Windows script, so a sync is the only way they arrive automatically - with their serial number and who they belong to.',
        'done'     => 'At least one device has been synced from Intune.',
        'link'     => 'asset-management/settings/?tab=intune',
        'check'    => ['rows', 'intune_devices'],
    ],
    [
        'id'       => 'assets.intune_software_sync',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Installed software from Intune',
        'what'     => 'A batch job that pulls each Intune device\'s detected applications from Microsoft Graph into the software inventory.',
        'why'      => 'Machines managed by Intune can feed the Software module and its licence counts without running the inventory script as well.',
        'done'     => 'At least one Intune software-sync job has been queued.',
        'link'     => 'asset-management/settings/?tab=intune',
        'check'    => ['rows', 'intune_app_sync_jobs'],
    ],
    [
        'id'       => 'assets.intune_renames',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Asset names that follow Intune',
        'what'     => 'When a device is renamed or reassigned in Intune, its asset takes the new name at the next sync, with the change in its history.',
        'why'      => 'Asset names drift from reality every time a laptop is re-issued. Off after upgrading, so it renames nothing until you choose.',
        'done'     => 'Renaming assets from Intune is switched on.',
        'link'     => 'asset-management/settings/?tab=intune',
        'check'    => ['setting', 'intune_sync_hostnames', 'eq', '1'],
    ],
    [
        'id'       => 'assets.intune_batch_size',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Intune software batch size',
        'what'     => 'How many devices one Intune software-sync job covers, from 1 to 500. The default is 30.',
        'why'      => 'A large estate needs a lot of clicks at 30 devices a time; a larger batch covers it sooner if your server copes with the longer job.',
        'done'     => 'The batch size has been saved as something other than the default of 30.',
        'link'     => 'asset-management/settings/?tab=intune',
        'check'    => ['setting', 'intune_app_batch_size', 'neq', '30'],
    ],

    // --- Custom fields ---------------------------------------------------
    [
        'id'       => 'assets.custom_fields',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Custom asset fields',
        'what'     => 'Your own fields on an asset - IMEI, screen size, SIM number, toner model - defined once and reused across asset types.',
        'why'      => 'The built-in details describe a computer. Custom fields are how you record what matters about everything else, without a database change.',
        'done'     => 'At least one custom asset field exists.',
        'link'     => 'asset-management/settings/?tab=custom-fields',
        'check'    => ['rows', 'asset_fields', 'is_deleted = 0'],
    ],
    [
        'id'       => 'assets.field_sets_on_types',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Fields attached to asset types',
        'what'     => 'A set of custom fields attached to an asset type, so every asset of that type asks for them.',
        'why'      => 'Attaching "Mobile details" to the Phone type means every phone shows the same boxes to fill in, instead of each person remembering what to record.',
        'done'     => 'At least one field set is attached to an asset type.',
        'link'     => 'asset-management/settings/?tab=custom-fields',
        'check'    => ['rows', 'asset_type_field_sets'],
    ],
    [
        'id'       => 'assets.field_dropdowns',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Pick-list custom fields',
        'what'     => 'A custom field with a fixed list of choices, optionally colour-coded.',
        'why'      => 'A pick-list keeps values consistent - "Vodafone" rather than "voda", "Vodafone UK" and "VF" - so filtering and reporting on the field actually work.',
        'done'     => 'At least one custom field has a list of options.',
        'link'     => 'asset-management/settings/?tab=custom-fields',
        'check'    => ['rows', 'asset_field_options'],
    ],
    [
        'id'       => 'assets.field_as_column',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Custom fields as list columns',
        'what'     => 'A custom field marked "Offer as a column", so it can be shown, sorted, filtered and exported in the asset table.',
        'why'      => 'Answering "which phones are on which network" becomes a column filter rather than opening each asset in turn.',
        'done'     => 'At least one custom field is offered as a column.',
        'link'     => 'asset-management/settings/?tab=custom-fields',
        'check'    => ['rows', 'asset_fields', 'show_in_list = 1 AND is_deleted = 0'],
    ],
    [
        'id'       => 'assets.field_searchable',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Searchable custom fields',
        'what'     => 'A custom field marked "Find assets by this field", so typing its value into search finds the asset.',
        'why'      => 'Somebody reading an IMEI or serial off a device can find its record in one search instead of scrolling the list.',
        'done'     => 'At least one custom field is searchable.',
        'link'     => 'asset-management/settings/?tab=custom-fields',
        'check'    => ['rows', 'asset_fields', 'is_searchable = 1 AND is_deleted = 0'],
    ],
    [
        'id'       => 'assets.field_unique',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Unique custom fields',
        'what'     => 'A custom field where no two assets may share a value.',
        'why'      => 'Stops the same SIM or serial being recorded against two devices by mistake, which is how duplicate records start.',
        'done'     => 'At least one custom field is marked unique.',
        'link'     => 'asset-management/settings/?tab=custom-fields',
        'check'    => ['rows', 'asset_fields', 'is_unique = 1 AND is_deleted = 0'],
    ],

    // --- Lifecycle: purchase, warranty, lease ----------------------------
    [
        'id'       => 'assets.purchase_details',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Purchase details on assets',
        'what'     => 'Purchase date, cost and order number recorded against an asset.',
        'why'      => 'Tells you how old the estate really is and what it cost, which is what a refresh budget or an insurance claim is built from.',
        'done'     => 'At least one asset has a purchase date, cost or order number (demo data not counted).',
        'link'     => 'asset-management/',
        'check'    => ['rows', 'assets', "is_demo = 0 AND (purchase_date IS NOT NULL OR purchase_cost IS NOT NULL OR (order_number IS NOT NULL AND order_number <> ''))"],
    ],
    [
        'id'       => 'assets.warranty_dates',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Warranty expiry dates',
        'what'     => 'The date each asset\'s warranty runs out, recorded on the asset.',
        'why'      => 'A repair under warranty is free and one day after it is not. Knowing the date is the difference between a phone call to the supplier and a purchase order.',
        'done'     => 'At least one asset has a warranty expiry date (demo data not counted).',
        'link'     => 'asset-management/',
        'check'    => ['rows', 'assets', 'warranty_expiry IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'assets.warranty_alerts',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Warranty expiry alerts',
        'what'     => 'Where assets with an expiring warranty show up - a Watchtower card, Calendar entries, both or neither - and how many days ahead.',
        'why'      => 'A date on a record nobody opens helps nobody. Surfacing it gives you time to extend cover or plan the replacement.',
        'done'     => 'The warranty alert setting has been saved (the default, Watchtower only, applies until then).',
        'link'     => 'asset-management/settings/?tab=warranty',
        'check'    => ['setting', 'asset_warranty_surface', 'nonempty'],
    ],
    [
        'id'       => 'assets.lease_dates',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Lease end dates',
        'what'     => 'The date leased equipment is due back, recorded on the asset.',
        'why'      => 'Leased kit kept past its end date keeps costing money, and kit returned late or wiped late can breach the lease terms.',
        'done'     => 'At least one asset has a lease end date (demo data not counted).',
        'link'     => 'asset-management/',
        'check'    => ['rows', 'assets', 'lease_expiry IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'assets.lease_alerts',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Lease expiry alerts',
        'what'     => 'Where assets with an ending lease show up - a Watchtower card, Calendar entries, both or neither - and how many days ahead.',
        'why'      => 'Returning leased kit takes planning: a replacement ordered, data wiped, a courier booked. An alert 60 days out gives you that time.',
        'done'     => 'The lease alert setting has been saved (the default, Watchtower only, applies until then).',
        'link'     => 'asset-management/settings/?tab=warranty',
        'check'    => ['setting', 'asset_lease_surface', 'nonempty'],
    ],

    // --- People and the physical kit -------------------------------------
    [
        'id'       => 'assets.assignment',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Assets assigned to people',
        'what'     => 'Recording who holds each asset - a requester or a member of the desk - with a custody trail of every hand-over and return.',
        'why'      => 'When somebody leaves, you can list exactly what they need to hand back. When a ticket comes in, you can see what the caller is using.',
        'done'     => 'At least one asset is assigned to somebody (demo data not counted).',
        'link'     => 'asset-management/users.php',
        'check'    => ['rows', 'users_assets', 'is_demo = 0'],
    ],
    [
        'id'       => 'assets.loan_returns',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Loans with a return date',
        'what'     => 'An expected return date set when an asset is checked out, for loan laptops and pool kit.',
        'why'      => 'A loan without a due date quietly becomes permanent. The date tells you which spares are overdue and who has them.',
        'done'     => 'At least one check-out has recorded an expected return date.',
        'link'     => 'asset-management/users.php',
        'check'    => ['rows', 'asset_checkout_log', 'expected_return_date IS NOT NULL'],
    ],
    [
        'id'       => 'assets.handover_template',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Equipment handover document',
        'what'     => 'Your own layout for the handover document: which sections appear, their wording, the equipment table\'s columns, and merge codes for the person and date.',
        'why'      => 'A signed record of what was handed over settles the "I never had a charger" conversation when somebody leaves, and your wording can carry your acceptable-use terms.',
        'done'     => 'At least one handover template has been saved.',
        'link'     => 'asset-management/settings/?tab=handover',
        'check'    => ['rows', 'asset_handover_templates'],
    ],
    [
        'id'       => 'assets.asset_tags',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Asset tags',
        'what'     => 'A human-readable asset number, such as IT-00412, recorded against the asset and printed on its label.',
        'why'      => 'A tag stuck on the device lets anyone read out a number over the phone and be talking about the same machine as you.',
        'done'     => 'At least one asset has an asset tag (demo data not counted).',
        'link'     => 'asset-management/assign-tags.php',
        'check'    => ['rows', 'assets', "asset_tag IS NOT NULL AND asset_tag <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'assets.qr_labels',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'QR labels',
        'what'     => 'A printable sheet of QR labels, each opening the asset\'s record when scanned with a phone camera, plus a scanner page for stocktakes.',
        'why'      => 'Scanning a label beats typing a serial number, and a stocktake becomes walking round the office pointing a phone at stickers.',
        'done'     => 'At least one asset has had a QR label generated (demo data not counted).',
        'link'     => 'asset-management/labels.php',
        'check'    => ['rows', 'assets', 'qr_token IS NOT NULL AND is_demo = 0'],
    ],
    // PR #164 (Sandy): automatic tags, the label designer, Intune renames.
    [
        'id'       => 'assets.tag_autogen',
        'module'   => 'assets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Automatic asset tags',
        'what'     => 'Every new asset - added by hand, imported, or found by the inventory agent or Intune - gets the next tag in a format you choose, such as AST-00042.',
        'why'      => 'Nobody has to know what number was last used, two people never hand out the same tag, and numbers are never reused once they are on a sticker.',
        'done'     => 'Automatic asset tags are switched on.',
        'link'     => 'asset-management/settings/?tab=asset-tags',
        'check'    => ['any', [
            ['setting', 'asset_tag_autogen_enabled', 'eq', '1'],
            ['rows', 'tenant_settings', "setting_key = 'asset_tag_autogen_enabled' AND setting_value = '1'"],
        ]],
    ],
    [
        'id'       => 'assets.label_design',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Labels with the fields you need',
        'what'     => 'Choose which fields a printed label carries and in what order - hostname, serial, location, a finance ID from your custom fields - plus a header, a footer and your logo in the QR code.',
        'why'      => 'A server label wants the serial; a laptop label wants the location. One fixed layout suits nobody for long.',
        'done'     => 'The label fields or header have been changed from the defaults.',
        'link'     => 'asset-management/settings/?tab=asset-labels',
        'check'    => ['any', [
            ['rows', 'system_settings', "setting_key IN ('asset_label_fields', 'asset_label_title') AND setting_value IS NOT NULL AND setting_value NOT IN ('', '[\"asset_tag\",\"hostname\"]')"],
            ['rows', 'tenant_settings', "setting_key IN ('asset_label_fields', 'asset_label_title') AND setting_value IS NOT NULL AND setting_value <> ''"],
        ]],
    ],
    [
        'id'       => 'assets.disk_hide_rules',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Hidden drives',
        'what'     => 'Rules that hide physical drives you do not care about - virtual disks, card readers - for one asset or every asset.',
        'why'      => 'Clears the noise so the drives that matter, and their serial numbers, are the ones you see.',
        'done'     => 'At least one drive hide rule exists.',
        'link'     => 'asset-management/',
        'check'    => ['rows', 'asset_disk_hide_rules'],
    ],

    // --- Seeing the estate -----------------------------------------------
    [
        'id'       => 'assets.dashboard_widget',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Your own asset dashboard chart',
        'what'     => 'A chart you have designed for the asset dashboard library, beyond the thirteen that come with FreeITSM.',
        'why'      => 'The built-in charts cover operating systems and hardware; a chart of your own answers the question your manager keeps asking.',
        'done'     => 'At least one asset dashboard widget exists beyond the thirteen supplied.',
        'link'     => 'asset-management/dashboard/',
        'check'    => ['rows', 'asset_dashboard_widgets', 'id > 13'],
    ],
    [
        'id'       => 'assets.shared_views',
        'module'   => 'assets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Shared asset table views',
        'what'     => 'A saved arrangement of the asset table - columns, order, sort and filters - shared with a team or everyone.',
        'why'      => 'Build "Laptops due for refresh" once and the whole team opens the same list instead of each person rebuilding the filters.',
        'done'     => 'At least one asset table view is shared with a team or everyone.',
        'link'     => 'asset-management/table.php',
        'check'    => ['rows', 'table_views', "table_key = 'assets' AND visibility <> 'private'"],
    ],
];
