<?php
/** Feature Bingo cards - Calendar: events, categories, subscription feed, dates from other modules, links and automation. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'calendar.first_event',
        'module'   => 'calendar',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Team calendar in use',
        'what'     => 'A shared, colour-coded calendar for maintenance windows, certificate expiries, renewals and team events that everyone on the service desk can see.',
        'why'      => 'Dates kept in personal reminders or a spreadsheet get missed when that person is off; a shared calendar means somebody always sees the expiry coming.',
        'done'     => 'At least one event has been created by a person (demo data and automatically generated dates do not count).',
        'link'     => 'calendar/',
        'check'    => ['rows', 'calendar_events', 'source IS NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'calendar.categories',
        'module'   => 'calendar',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Event categories',
        'what'     => 'Named, coloured categories events are filed under - maintenance, certificates, meetings - which the sidebar can tick on and off to filter the calendar.',
        'why'      => 'Colour tells you what kind of date it is at a glance, and filtering lets someone hide the meetings and see only the maintenance windows.',
        'done'     => 'At least one category exists that you created yourself (demo data and the ones other modules make automatically do not count).',
        'link'     => 'calendar/settings/',
        'check'    => ['rows', 'calendar_categories', "is_demo = 0 AND name NOT IN ('Renewals', 'Warranty', 'Lease')"],
    ],
    [
        'id'       => 'calendar.subscription_feed',
        'module'   => 'calendar',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Calendar subscription feed',
        'what'     => 'A private iCalendar (.ics) link to the team calendar that Outlook, Google Calendar or a phone can subscribe to, read-only. Each analyst gets their own link and can reset it.',
        'why'      => 'Maintenance windows and renewals show up on your phone next to your own appointments, without opening FreeITSM.',
        'done'     => 'At least one analyst has generated a calendar feed link.',
        'link'     => 'calendar/',
        'check'    => ['rows', 'user_preferences', "preference_key = 'calendar_feed_token'"],
    ],
    [
        'id'       => 'calendar.generated_dates',
        'module'   => 'calendar',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Dates from other modules',
        'what'     => 'Events FreeITSM keeps on the calendar by itself from other records - asset warranty and lease expiries, software licence renewals and notice dates - kept in step whenever the record changes.',
        'why'      => 'A renewal or warranty that expires quietly costs money; putting those dates on the shared calendar means they are seen without anyone copying them in.',
        'done'     => 'At least one automatically generated event is on the calendar.',
        'link'     => 'calendar/',
        'check'    => ['rows', 'calendar_events', 'source IS NOT NULL'],
    ],
    [
        'id'       => 'calendar.contract_events',
        'module'   => 'calendar',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Events linked to contracts',
        'what'     => 'Linking a calendar event to a contract, so a renewal meeting or notice deadline can be opened from the contract and the other way round.',
        'why'      => 'When the date comes round, the contract terms, value and supplier are one click away instead of a search.',
        'done'     => 'At least one real calendar event is linked to a contract.',
        'link'     => 'calendar/',
        'check'    => ['rows', 'calendar_events', 'contract_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'calendar.documents',
        'module'   => 'calendar',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Documents on events',
        'what'     => 'Files and links attached to a calendar event - a maintenance plan, a vendor\'s change notice, the meeting agenda.',
        'why'      => 'Whoever picks up the maintenance window on the night has the plan with the event, not in someone else\'s inbox.',
        'done'     => 'At least one document is attached to a calendar event.',
        'link'     => 'calendar/',
        'check'    => ['rows', 'document_links', "parent_type = 'calendar_event'"],
    ],
    [
        'id'       => 'calendar.shared_table_views',
        'module'   => 'calendar',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Shared calendar table views',
        'what'     => 'A saved arrangement of the Calendar table - columns, sort and filters - shared with a team or with everyone.',
        'why'      => 'A ready-made view such as "Renewals in the next 90 days" saves everyone building the same filter to answer the same question.',
        'done'     => 'At least one saved Calendar table view is shared with a team or with everyone.',
        'link'     => 'calendar/table/',
        'check'    => ['rows', 'table_views', "table_key = 'calendar' AND visibility IN ('team', 'public')"],
    ],
    [
        'id'       => 'calendar.workflow_triggers',
        'module'   => 'calendar',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on calendar events',
        'what'     => 'A workflow that runs when a calendar event is created, updated or deleted.',
        'why'      => 'A new maintenance window can tell the people affected, raise a task or post to a webhook without anyone doing it by hand.',
        'done'     => 'At least one real workflow is triggered by a calendar event.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', "trigger_event LIKE 'calendar_event.%' AND is_demo = 0"],
    ],
];
