<?php
/** Feature Bingo cards - Change Management: lookups, the change form layout, CAB and approvals, risk, schedule and review. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'changes.first_change',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Record your first change',
        'what'     => 'A change record for a planned modification to your environment - a server upgrade, a firewall rule, a new deployment - with who, when, why and how to back it out.',
        'why'      => 'When something breaks, the first question is "what changed?". If changes are recorded here, the answer is a search rather than a round of phone calls.',
        'done'     => 'At least one change exists that was not created by the demo data importer.',
        'link'     => 'change-management/new/',
        'check'    => ['rows', 'changes', 'is_demo = 0'],
    ],
    [
        'id'       => 'changes.types_tailored',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Change types',
        'what'     => 'The kinds of change you recognise. FreeITSM ships Standard, Normal and Emergency; you can rename them, recolour them or add your own.',
        'why'      => 'If your change policy talks about "pre-approved" or "major" changes, the form should use the same words, so nobody has to translate between the policy and the tool.',
        'done'     => 'At least one change type has a name other than the shipped Standard, Normal and Emergency, or one of those has been removed.',
        'link'     => 'change-management/settings/',
        'check'    => ['any', [
            ['rows', 'change_types', "name NOT IN ('Standard','Normal','Emergency') AND display_order <> 999"],
            ['sql', 'SELECT COUNT(*) < 3 FROM change_types'],
        ]],
    ],
    [
        'id'       => 'changes.statuses_tailored',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Change statuses',
        'what'     => 'The stages a change moves through, from Draft to Completed, and which of them count as closed.',
        'why'      => 'Matching the statuses to your real approval process means the list of open changes and the Watchtower counts reflect where work actually is.',
        'done'     => 'At least one change status has a name other than the ten shipped ones, or one of those has been removed.',
        'link'     => 'change-management/settings/',
        'check'    => ['any', [
            ['rows', 'change_statuses', "name NOT IN ('Draft','Submitted','Pending Approval','Approved','Rejected','Scheduled','In Progress','Completed','Failed','Cancelled') AND display_order <> 999"],
            ['sql', 'SELECT COUNT(*) < 10 FROM change_statuses'],
        ]],
    ],
    [
        'id'       => 'changes.priorities_tailored',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Change priorities',
        'what'     => 'The priority scale for changes, with a colour for each and a default for new ones.',
        'why'      => 'A scale that matches the one your organisation already uses stops people guessing what "High" means for a change as opposed to a ticket.',
        'done'     => 'At least one change priority has a name other than the shipped Low, Medium, High and Critical, or one of those has been removed.',
        'link'     => 'change-management/settings/',
        'check'    => ['any', [
            ['rows', 'change_priorities', "name NOT IN ('Low','Medium','High','Critical') AND display_order <> 999"],
            ['sql', 'SELECT COUNT(*) < 4 FROM change_priorities'],
        ]],
    ],
    [
        'id'       => 'changes.impacts_tailored',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Change impact levels',
        'what'     => 'The scale used to say how much of the business a change touches.',
        'why'      => 'Impact is what decides whether a change needs a wider review, so the levels should mean something specific to your organisation rather than a generic Low, Medium, High.',
        'done'     => 'At least one change impact has a name other than the shipped Low, Medium and High, or one of those has been removed.',
        'link'     => 'change-management/settings/',
        'check'    => ['any', [
            ['rows', 'change_impacts', "name NOT IN ('Low','Medium','High') AND display_order <> 999"],
            ['sql', 'SELECT COUNT(*) < 3 FROM change_impacts'],
        ]],
    ],
    [
        'id'       => 'changes.form_sections',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Change form layout',
        'what'     => 'The sections of the change form and which field sits in which, arranged by drag and drop under Settings -> Form fields.',
        'why'      => 'Putting the fields your team fills in first at the top, under headings they recognise, makes a change quicker to raise and easier to review.',
        'done'     => 'The change form has a section other than the five shipped ones (General information, People, Schedule, Details, Attachments), or one of those has been removed or renamed.',
        'link'     => 'change-management/settings/',
        'check'    => ['any', [
            ['rows', 'change_field_sections', "name NOT IN ('General information','People','Schedule','Details','Attachments')"],
            ['sql', 'SELECT COUNT(*) < 5 FROM change_field_sections'],
        ]],
    ],
    [
        'id'       => 'changes.hidden_fields',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Hide unused change fields',
        'what'     => 'Any field on the change form can be switched off, so it no longer appears for anyone.',
        'why'      => 'A form full of boxes nobody fills in teaches people to skip boxes. Hiding the ones you never use keeps attention on the ones that matter, such as the rollback plan.',
        'done'     => 'At least one field on the change form has been switched off.',
        'link'     => 'change-management/settings/',
        'check'    => ['rows', 'change_field_layout', 'is_visible = 0'],
    ],
    [
        'id'       => 'changes.approver',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Named change approver',
        'what'     => 'Each change can name the person who signs it off, alongside the requester and the analyst doing the work.',
        'why'      => 'A named approver is the audit answer to "who authorised this?" - without one, a change that goes wrong has nobody who agreed it should happen.',
        'done'     => 'At least one real (non-demo) change has an approver set.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', 'approver_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'changes.cab_review',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'CAB review',
        'what'     => 'A Change Advisory Board: a panel of analysts added to a change, each of whom votes Approve, Reject or Abstain, with the status moving to Approved automatically when the threshold is met.',
        'why'      => 'Higher-risk changes deserve more than one pair of eyes. A recorded vote shows who reviewed what, and one rejection sends the change back to Draft before it can do damage.',
        'done'     => 'At least one real (non-demo) change requires CAB review or has CAB members added.',
        'link'     => 'change-management/',
        'check'    => ['any', [
            ['rows', 'changes', 'cab_required = 1 AND is_demo = 0'],
            ['rows', 'change_cab_members', 'is_demo = 0'],
        ]],
    ],
    [
        'id'       => 'changes.cab_votes',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'CAB votes cast',
        'what'     => 'CAB members vote from the change itself or from the Approvals view, and can add a comment explaining their vote.',
        'why'      => 'A board that is set up but never votes is a formality. Votes with comments are the record that the review actually happened.',
        'done'     => 'At least one real (non-demo) CAB vote has been cast.',
        'link'     => 'change-management/approvals.php',
        'check'    => ['rows', 'change_cab_members', 'vote IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'changes.cab_majority',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Majority CAB approval',
        'what'     => 'Instead of every required member having to approve, a change can be approved once more than half of its required CAB members vote Approve.',
        'why'      => 'On a large board, waiting for every last vote can stall a change for days. Majority keeps it moving while one rejection still sends it back.',
        'done'     => 'At least one real (non-demo) change uses the Majority approval type.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', "cab_approval_type = 'majority' AND is_demo = 0"],
    ],
    [
        'id'       => 'changes.risk_assessment',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Risk assessment',
        'what'     => 'A likelihood score and an impact score from 1 to 5 that multiply into a risk level, shown on a colour-coded matrix on the change.',
        'why'      => 'A number gives a consistent basis for deciding which changes go to CAB and which need a detailed rollback plan, instead of relying on how nervous the requester sounds.',
        'done'     => 'At least one real (non-demo) change has a calculated risk score.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', 'risk_score IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'changes.rollback_plan',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Rollback plans',
        'what'     => 'A written plan for how to undo the change if it goes wrong, kept on the change record.',
        'why'      => 'The time to work out how to back a change out is before it starts, not at 2am when it has failed. A rollback plan turns a failed change into an inconvenience.',
        'done'     => 'At least one real (non-demo) change has a rollback plan written.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', "rollback_plan IS NOT NULL AND rollback_plan <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'changes.test_plan',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Test plans',
        'what'     => 'A description of how you will confirm the change worked, kept alongside the description, reason and risk evaluation.',
        'why'      => 'Agreeing in advance what "working" looks like stops a change being declared done because nobody has complained yet.',
        'done'     => 'At least one real (non-demo) change has a test plan written.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', "test_plan IS NOT NULL AND test_plan <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'changes.pir',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Post-implementation review',
        'what'     => 'Once a change is Completed or Failed, a review section records whether it succeeded, when it actually started and ended, lessons learned and follow-up actions.',
        'why'      => 'This is how a team gets better at changes. Even a successful change often ran late or surprised someone, and that is worth writing down for next time.',
        'done'     => 'At least one real (non-demo) change has a post-implementation review with its success recorded.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', 'pir_was_successful IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'changes.calendar',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Change calendar',
        'what'     => 'Changes with a scheduled work window appear on the Change Management calendar, so the whole team can see what is planned and when.',
        'why'      => 'Two changes to the same system on the same night is how outages happen. A shared calendar makes clashes visible before they are made.',
        'done'     => 'At least one real (non-demo) change has a scheduled work start.',
        'link'     => 'change-management/calendar.php',
        'check'    => ['rows', 'changes', 'work_start_datetime IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'changes.outage_window',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Expected outage windows',
        'what'     => 'Separate from the work window, a change can record when the service is actually expected to be unavailable.',
        'why'      => 'The work may take four hours while the outage lasts ten minutes. Recording the outage separately is what lets you tell users the truth about when they will be affected.',
        'done'     => 'At least one real (non-demo) change has an expected outage start.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'changes', 'outage_start_datetime IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'changes.linked_incidents',
        'module'   => 'changes',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Link incidents to changes',
        'what'     => 'Tickets can be linked to the change that caused them or the change that fixes them, visible from both sides.',
        'why'      => 'Linking shows which changes generate incidents and proves which changes resolved them - the evidence for tightening, or loosening, your change process.',
        'done'     => 'At least one ticket is linked to a change.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'change_tickets'],
    ],
    [
        'id'       => 'changes.attachments',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Change attachments',
        'what'     => 'Screenshots, configuration backups, vendor instructions or approval emails uploaded to the change itself.',
        'why'      => 'The config backup you took before the change is only useful if you can find it when the change fails. Keeping it on the record means it is where people will look.',
        'done'     => 'At least one file has been attached to a change.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'change_attachments'],
    ],
    [
        'id'       => 'changes.comments',
        'module'   => 'changes',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Discuss changes in Activity',
        'what'     => 'Comments on a change, shown in its Activity timeline alongside the automatic audit of every field that changed.',
        'why'      => 'Discussion kept on the change stays with the change. An email thread about it is gone the moment someone leaves.',
        'done'     => 'At least one real (non-demo) comment has been added to a change.',
        'link'     => 'change-management/',
        'check'    => ['rows', 'change_comments', 'is_demo = 0'],
    ],
];
