<?php
/** Feature Bingo cards - Checklists & SOPs: templates, keywords, closure gates, step roles and inputs, categories, roles and company templates. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'checklists.first_template',
        'module'   => 'checklists',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Write your first checklist',
        'what'     => 'A checklist template - a standard operating procedure such as a new starter, a leaver or a server patch - as a list of steps that can be attached to a ticket.',
        'why'      => 'A procedure done from memory skips a step sooner or later, usually the one that matters, such as removing a leaver\'s VPN access. A checklist makes every run the same.',
        'done'     => 'At least one checklist template exists that was not created by the demo data importer.',
        'link'     => 'checklists/',
        'check'    => ['rows', 'checklist_templates', 'is_demo = 0'],
    ],
    [
        'id'       => 'checklists.used_on_ticket',
        'module'   => 'checklists',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Attach a checklist to a ticket',
        'what'     => 'A checklist attached to a ticket, where each step is ticked off with who did it and when.',
        'why'      => 'The ticket then shows exactly which steps were done and by whom, which is the record you need when someone asks months later whether an account was really disabled.',
        'done'     => 'At least one ticket has a checklist attached that was not created by the demo data importer.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_checklists', 'is_demo = 0'],
    ],
    [
        'id'       => 'checklists.keywords',
        'module'   => 'checklists',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Suggest checklists by keyword',
        'what'     => 'Keywords on a template, such as "vpn, remote access, token". When a ticket\'s subject matches, FreeITSM offers that checklist at the top as the best match.',
        'why'      => 'The right procedure turns up on the ticket before anyone goes looking for it, so analysts who did not know a checklist existed still follow it.',
        'done'     => 'At least one checklist template has keywords.',
        'link'     => 'checklists/',
        'check'    => ['rows', 'checklist_templates', "keywords IS NOT NULL AND TRIM(keywords) <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'checklists.critical_gate',
        'module'   => 'checklists',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Block closure until done',
        'what'     => 'A template set to Critical, so a ticket carrying it cannot be closed until every mandatory step is complete. Standard templates only warn and record who overrode them.',
        'why'      => 'For leaver offboarding, regulated procedures or critical infrastructure changes, a ticket closed with steps outstanding is a real risk, not an untidy record.',
        'done'     => 'At least one checklist template uses the Critical (block closure) gate.',
        'link'     => 'checklists/',
        'check'    => ['rows', 'checklist_templates', "closure_mode = 'block' AND is_demo = 0"],
    ],
    [
        'id'       => 'checklists.input_steps',
        'module'   => 'checklists',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Steps that ask for a value',
        'what'     => 'A step that asks the analyst to type something when they tick it - an asset tag, a serial number, a reference - which is stored beside the step on the ticket.',
        'why'      => '"Laptop returned" is better evidence with the asset tag next to it. It captures the detail at the moment it is known, instead of in a note nobody writes.',
        'done'     => 'At least one checklist step asks for a value.',
        'link'     => 'checklists/',
        'check'    => ['rows', 'checklist_template_items', 'requires_input = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'checklists.step_roles',
        'module'   => 'checklists',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Suggested roles on steps',
        'what'     => 'A suggested role beside a step - IT, HR, Facilities - saying who normally does it. It is guidance, not a permission: anyone can tick any step.',
        'why'      => 'On a procedure that crosses teams, everyone can see at a glance which steps are theirs to do and which they are waiting on.',
        'done'     => 'At least one checklist step has a suggested role.',
        'link'     => 'checklists/',
        'check'    => ['rows', 'checklist_template_items', "suggested_role IS NOT NULL AND suggested_role <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'checklists.categories',
        'module'   => 'checklists',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Checklist categories',
        'what'     => 'Categories that group templates on the list and colour their pills. One is created automatically the first time a template uses it, and they can be renamed in Settings.',
        'why'      => 'Once you have more than a handful of procedures, grouping them - Network, HR & IT, Security - is how people find the right one quickly.',
        'done'     => 'At least one checklist category other than "General" exists that was not created by the demo data importer.',
        'link'     => 'checklists/settings/?tab=categories',
        'check'    => ['rows', 'checklist_categories', "name <> 'General' AND is_demo = 0"],
    ],
    [
        'id'       => 'checklists.roles',
        'module'   => 'checklists',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own suggested roles',
        'what'     => 'The list of roles offered when building a step. FreeITSM ships eight common ones, from Tier 1 Support to HR & IT; add or rename them to match your teams.',
        'why'      => 'If your teams are called "Service Desk" and "Platform", steps should say so, so nobody has to translate a generic role into a real team.',
        'done'     => 'At least one checklist role exists other than the eight shipped ones.',
        'link'     => 'checklists/settings/?tab=roles',
        'check'    => ['rows', 'checklist_roles', "is_demo = 0 AND name NOT IN ('Tier 1 Support','Tier 2 Support','Network Admin','Systems Administrator','Security Team','Database Admin','DevOps / Cloud','HR & IT')"],
    ],
];
