<?php
/** Feature Bingo cards - CMDB: classes and properties, objects, relationships, impact analysis, ticket links, AI. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'cmdb.classes',
        'module'   => 'cmdb',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Configuration item classes',
        'what'     => 'The kinds of thing your CMDB records - Server, Database, Application, Service, Firewall - each with its own icon.',
        'why'      => 'Classes are the CMDB\'s schema. Nothing can be recorded until at least one exists, and a sensible set keeps like things together.',
        'done'     => 'At least one CMDB class exists (demo data not counted).',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_classes', 'is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.class_properties',
        'module'   => 'cmdb',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Class properties',
        'what'     => 'The fields each class carries - text, number, date, yes/no, pick-list, or a reference to another object.',
        'why'      => 'A Server with no fields is just a name. Properties are where the version, IP address, owner and support contract live.',
        'done'     => 'At least one class property exists (demo data not counted).',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_class_properties', 'is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.property_options',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Pick-list properties',
        'what'     => 'A dropdown property with a fixed, optionally colour-coded, list of choices - such as Environment: Production, Test, Development.',
        'why'      => 'Free text drifts into "Prod", "prod" and "Live". A pick-list keeps values filterable and makes Production stand out in colour.',
        'done'     => 'At least one property has options defined (demo data not counted).',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_class_property_options', 'is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.required_properties',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Required properties',
        'what'     => 'A property that must be filled in before an object of that class can be saved.',
        'why'      => 'Makes the details you rely on - an owner, an environment - impossible to leave blank, so the CMDB can be trusted when it matters.',
        'done'     => 'At least one property is marked required (demo data not counted).',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_class_properties', 'is_required = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.object_references',
        'module'   => 'cmdb',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Properties that point at other objects',
        'what'     => 'An object-reference property, such as a Database\'s "Host server", that links to another CMDB object instead of holding text.',
        'why'      => 'A typed link can be followed and kept up to date; the name of a server typed as text goes stale the day the server is renamed.',
        'done'     => 'At least one object-reference property exists (demo data not counted).',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_class_properties', "property_type = 'object_ref' AND is_demo = 0"],
    ],
    [
        'id'       => 'cmdb.dependency_properties',
        'module'   => 'cmdb',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Dependencies in properties',
        'what'     => 'An object-reference property ticked "This is a dependency", so a failure of the referenced object is counted as affecting this one.',
        'why'      => 'Impact analysis only follows links it is told carry a failure. Ticking this is what makes "if this host goes down, what breaks" come back with an answer.',
        'done'     => 'At least one property is marked as a dependency (demo data not counted).',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_class_properties', 'spreads_impact = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.custom_relationship_types',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own relationship types',
        'what'     => 'Relationship verbs beyond the three supplied (depends on, connects to, managed by) - for example "replicates to" or "backed up by".',
        'why'      => 'The words your team already uses about the estate make the relationships readable to everyone, not just whoever drew them.',
        'done'     => 'At least one relationship type exists other than the three supplied.',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_relationship_types', "verb NOT IN ('depends on', 'connects to', 'managed by') AND is_demo = 0"],
    ],
    [
        'id'       => 'cmdb.impact_relationships',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Relationships that carry a failure',
        'what'     => 'Setting "When something fails" on a relationship type so impact travels along it. Out of the box only "depends on" does.',
        'why'      => 'If a relationship such as "runs on" or "backed up by" means a failure spreads, saying so makes the blast radius match reality rather than under-claim.',
        'done'     => 'A relationship type other than "depends on" carries impact.',
        'link'     => 'cmdb/settings/',
        'check'    => ['rows', 'cmdb_relationship_types', "impact_direction <> 'none' AND verb <> 'depends on'"],
    ],
    [
        'id'       => 'cmdb.objects',
        'module'   => 'cmdb',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Configuration items',
        'what'     => 'The actual objects in your CMDB - each server, application, service and network device, filled in against its class.',
        'why'      => 'This is the record everything else points at: tickets, impact analysis and network diagrams all start from an object.',
        'done'     => 'At least one CMDB object exists (demo data not counted).',
        'link'     => 'cmdb/',
        'check'    => ['rows', 'cmdb_objects', 'is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.hierarchy',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Object hierarchy',
        'what'     => 'Nesting objects under a parent - a virtual machine under its host, a database under its server, a service under its platform.',
        'why'      => 'The tree lets you browse the estate the way it is built, and collapse a whole platform to one line.',
        'done'     => 'At least one object has a parent (demo data not counted).',
        'link'     => 'cmdb/',
        'check'    => ['rows', 'cmdb_objects', 'parent_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.relationships',
        'module'   => 'cmdb',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Relationships between objects',
        'what'     => 'Named links between objects outside the hierarchy - this application depends on that database, this switch connects to that firewall.',
        'why'      => 'Without relationships the CMDB is a list. With them, the object page can tell you what else breaks when this one fails.',
        'done'     => 'At least one relationship between objects exists (demo data not counted).',
        'link'     => 'cmdb/',
        'check'    => ['rows', 'cmdb_object_relationships', 'is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.planned_objects',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Planned objects',
        'what'     => 'Marking an object as planned - part of the future design but not yet real. It shows dashed and amber on network diagrams.',
        'why'      => 'You can draw the target architecture alongside what exists today, then flip the flag off when it goes live, rather than keeping the plan in a separate drawing.',
        'done'     => 'At least one object is marked planned (demo data not counted).',
        'link'     => 'cmdb/',
        'check'    => ['rows', 'cmdb_objects', 'is_planned = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'cmdb.impact_diagram',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Impact diagrams',
        'what'     => 'Turning an object\'s blast radius into a Network Mapper diagram in one click from its object page.',
        'why'      => 'A picture of everything that fails with a component is what you put in front of a change board or a manager during an outage.',
        'done'     => 'At least one impact diagram has been created from the CMDB.',
        'link'     => 'cmdb/',
        'check'    => ['rows', 'network_diagrams', "title LIKE 'Impact: %' AND is_demo = 0"],
    ],
    [
        'id'       => 'cmdb.ai',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI for the CMDB',
        'what'     => 'An AI provider and API key for the CMDB, used to suggest properties for a class and to write plain-English summaries of an object.',
        'why'      => 'Designing a class from a blank page is slow; the AI asks about your environment and suggests the fields worth recording.',
        'done'     => 'A CMDB AI API key has been saved.',
        'link'     => 'cmdb/settings/',
        'check'    => ['setting', 'cmdb_ai_api_key', 'nonempty'],
    ],
    [
        'id'       => 'cmdb.ai_instructions',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'CMDB AI custom instructions',
        'what'     => 'Standing instructions added to every CMDB AI request - your naming conventions, your platforms, what to leave out.',
        'why'      => 'Suggestions that already know you run Azure and name servers by site need far less correcting.',
        'done'     => 'Custom instructions for the CMDB AI have been saved.',
        'link'     => 'cmdb/settings/',
        'check'    => ['setting', 'cmdb_ai_custom_instructions', 'nonempty'],
    ],
    [
        'id'       => 'cmdb.ai_summaries',
        'module'   => 'cmdb',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI object summaries',
        'what'     => 'A short generated summary on an object page, drawn from its properties, parent and children, relationships and what depends on it.',
        'why'      => 'Somebody on call at 2am gets the gist of an unfamiliar system in a paragraph instead of reading every property and relationship.',
        'done'     => 'At least one object has an AI summary.',
        'link'     => 'cmdb/',
        'check'    => ['rows', 'cmdb_objects', 'ai_summary IS NOT NULL AND is_demo = 0'],
    ],
];
