<?php
/** Feature Bingo cards - Contracts: lookup lists, suppliers and contacts, contract records, renewals, data protection, equipment, RFP Builder. See includes/feature_bingo.php for the format. */
return [
    // --- The lookup lists (Contracts settings) ---------------------------
    [
        'id'       => 'contracts.supplier_types',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Supplier types',
        'what'     => 'The kinds of supplier you deal with - software vendor, hardware reseller, managed service, consultancy.',
        'why'      => 'Lets you filter the supplier directory down to "every managed service provider" when a question about outsourcing comes up.',
        'done'     => 'At least one supplier type exists (demo data not counted).',
        'link'     => 'contracts/settings/',
        'check'    => ['rows', 'supplier_types', 'is_demo = 0'],
    ],
    [
        'id'       => 'contracts.supplier_statuses',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Supplier statuses',
        'what'     => 'Where a supplier stands with you - for example Prospective, Approved, Under review, Do not use.',
        'why'      => 'Stops somebody placing an order with a supplier that failed due diligence or has been dropped.',
        'done'     => 'At least one supplier status exists (demo data not counted).',
        'link'     => 'contracts/settings/',
        'check'    => ['rows', 'supplier_statuses', 'is_demo = 0'],
    ],
    [
        'id'       => 'contracts.contract_statuses',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Contract statuses',
        'what'     => 'The stages a contract moves through - Draft, Active, In renewal, Expired, Terminated.',
        'why'      => 'Separates the contracts you are paying for today from the history, so the renewal list is not cluttered with agreements that ended years ago.',
        'done'     => 'At least one contract status exists (demo data not counted).',
        'link'     => 'contracts/settings/',
        'check'    => ['rows', 'contract_statuses', 'is_demo = 0'],
    ],
    [
        'id'       => 'contracts.payment_schedules',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Payment schedules',
        'what'     => 'How often a contract is paid - monthly, quarterly, annually, in advance.',
        'why'      => 'Knowing when the money goes out helps finance plan cash flow and spot a contract billed more often than agreed.',
        'done'     => 'At least one payment schedule exists (demo data not counted).',
        'link'     => 'contracts/settings/',
        'check'    => ['rows', 'payment_schedules', 'is_demo = 0'],
    ],
    [
        'id'       => 'contracts.term_tabs',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Contract term tabs',
        'what'     => 'The tabs a contract\'s terms are organised into - SLA terms, KPI targets, obligations, exit terms - each holding rich text.',
        'why'      => 'When a supplier misses a target you can find what they actually promised in seconds, without digging the PDF out of a shared drive.',
        'done'     => 'At least one contract term tab exists (demo data not counted).',
        'link'     => 'contracts/settings/',
        'check'    => ['rows', 'contract_term_tabs', 'is_demo = 0'],
    ],

    // --- Suppliers and contacts ------------------------------------------
    [
        'id'       => 'contracts.suppliers',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Supplier directory',
        'what'     => 'A record for each organisation you do business with - legal and trading name, company and VAT numbers, address, type and status.',
        'why'      => 'One directory shared by Contracts and Asset Management means a supplier\'s details are entered once and kept right in one place.',
        'done'     => 'At least one supplier exists (demo data not counted).',
        'link'     => 'contracts/suppliers/',
        'check'    => ['rows', 'suppliers', 'is_demo = 0'],
    ],
    [
        'id'       => 'contracts.supplier_questionnaires',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Supplier due diligence',
        'what'     => 'Recording when a due-diligence questionnaire was sent to a supplier and when it came back.',
        'why'      => 'Auditors and data-protection reviews ask which suppliers were vetted and when; this is the answer, recorded against the supplier.',
        'done'     => 'At least one supplier has a questionnaire issue date (demo data not counted).',
        'link'     => 'contracts/suppliers/',
        'check'    => ['rows', 'suppliers', 'questionnaire_date_issued IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'contracts.contacts',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Supplier contacts',
        'what'     => 'The people at each supplier - account manager, support desk, escalation - with job title, email and phone numbers.',
        'why'      => 'When a service is down or a renewal needs negotiating, the right name and direct dial are already on the supplier\'s record.',
        'done'     => 'At least one supplier contact exists (demo data not counted).',
        'link'     => 'contracts/contacts/',
        'check'    => ['rows', 'contacts', 'is_demo = 0'],
    ],

    // --- Contract records ------------------------------------------------
    [
        'id'       => 'contracts.contracts',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Contracts',
        'what'     => 'A record for each supplier agreement - who it is with, when it starts and ends, what it costs and who owns it.',
        'why'      => 'Most organisations cannot list their IT contracts without a week of digging. One register means you know what you have and when each one ends.',
        'done'     => 'At least one contract exists (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', 'is_demo = 0'],
    ],
    [
        'id'       => 'contracts.end_dates',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Contract end dates',
        'what'     => 'The date each contract ends, which drives the renewals shown in Contracts and on Watchtower.',
        'why'      => 'An end date is what turns a filing cabinet into a warning. Without it, a contract rolls over unnoticed.',
        'done'     => 'At least one contract has an end date (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', 'contract_end IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'contracts.notice_periods',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Contract notice periods',
        'what'     => 'How much notice a contract needs to be cancelled, and the resulting notice date.',
        'why'      => 'Many contracts renew automatically unless you give notice months ahead. The notice date is the deadline that actually matters.',
        'done'     => 'At least one contract has a notice period or notice date (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', '(notice_period_days IS NOT NULL OR notice_date IS NOT NULL) AND is_demo = 0'],
    ],
    [
        'id'       => 'contracts.owners',
        'module'   => 'contracts',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Contract owners',
        'what'     => 'The person responsible for each contract.',
        'why'      => 'A renewal warning needs somebody to act on it. A named owner means it is never "someone else\'s" job.',
        'done'     => 'At least one contract has an owner (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', 'contract_owner_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'contracts.values',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Contract values and cost centres',
        'what'     => 'What a contract is worth, its currency, payment schedule and the cost centre it is charged to.',
        'why'      => 'Lets you total supplier spend and answer finance\'s questions without going back to the invoices.',
        'done'     => 'At least one contract has a value (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', 'contract_value IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'contracts.terms_recorded',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Contract terms written up',
        'what'     => 'The substance of a contract - service levels, targets, obligations - written into its term tabs.',
        'why'      => 'When a dispute starts, the promised response time is on screen rather than in a document nobody can find.',
        'done'     => 'At least one contract has content in a term tab (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contract_term_values', "content IS NOT NULL AND content <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'contracts.document_links',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Links to signed documents',
        'what'     => 'A link from the contract record to the signed copy in your document management system.',
        'why'      => 'The record and the legal document stay one click apart, so nobody works from an out-of-date draft.',
        'done'     => 'At least one contract has a document link (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', "dms_link IS NOT NULL AND dms_link <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'contracts.data_protection',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Data protection on contracts',
        'what'     => 'Recording whether personal data is passed to the supplier, whether a DPIA is needed, and when it was completed.',
        'why'      => 'GDPR expects you to know which suppliers process personal data and to have assessed them. This keeps the answer on the contract itself.',
        'done'     => 'At least one contract records whether personal data is transferred (demo data not counted).',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contracts', 'personal_data_transferred IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'contracts.equipment',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Equipment covered by contracts',
        'what'     => 'Linking assets to the contract that covers them - handsets on a mobile agreement, the router on an internet contract, machines under maintenance.',
        'why'      => 'The link shows from both ends, so a broken device leads straight to who fixes it, and a contract lists exactly what it covers when it is up for renewal.',
        'done'     => 'At least one asset is linked to a contract.',
        'link'     => 'contracts/',
        'check'    => ['rows', 'contract_assets'],
    ],
    [
        'id'       => 'contracts.customer_contracts',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Contracts with customers',
        'what'     => 'A contract you sell rather than buy - a support agreement, a managed service - recorded against the customer\'s company, a person, or both.',
        'why'      => 'The renewals you are owed sit beside the ones you owe, with the same reminders, and only the people who look after that customer see them.',
        'done'     => 'At least one contract is with a customer (demo data not counted).',
        'link'     => 'contracts/edit.php',
        'check'    => ['rows', 'contracts', "party_type = 'customer' AND is_demo = 0"],
    ],

    // --- RFP Builder -----------------------------------------------------
    [
        'id'       => 'contracts.rfp_ai',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI for the RFP Builder',
        'what'     => 'An AI provider, model and API key used to extract requirements from documents, consolidate them and draft the RFP.',
        'why'      => 'Turning a pile of departmental wish-lists into one structured request for proposal is days of work by hand; the RFP Builder cannot run without a key.',
        'done'     => 'An RFP Builder AI API key has been saved.',
        'link'     => 'contracts/settings/',
        'check'    => ['setting', 'rfp_ai_api_key', 'nonempty'],
    ],
    [
        'id'       => 'contracts.rfp_style_guide',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'RFP default style guide',
        'what'     => 'Writing rules applied to every RFP the AI drafts - tone, British or US English, heading case, preferred terms.',
        'why'      => 'A document that goes to suppliers under your name should read like your organisation wrote it, not like a generic template.',
        'done'     => 'A default RFP style guide has been saved.',
        'link'     => 'contracts/settings/',
        'check'    => ['setting', 'rfp_default_style_guide', 'nonempty'],
    ],
    [
        'id'       => 'contracts.rfp_departments',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'RFP departments',
        'what'     => 'The internal departments that contribute requirements to an RFP, such as IT, Finance and HR, used to tag their source documents.',
        'why'      => 'Shows whose requirement is whose, so a conflict between Finance and IT can be taken back to the right people.',
        'done'     => 'At least one RFP department exists.',
        'link'     => 'contracts/settings/',
        'check'    => ['rows', 'rfp_departments'],
    ],
    [
        'id'       => 'contracts.rfp',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'An RFP in the RFP Builder',
        'what'     => 'A request for proposal built from uploaded requirement documents, with invited suppliers and scoring.',
        'why'      => 'Keeps a tender in one place from first requirement to the supplier you chose, with the reasoning recorded.',
        'done'     => 'At least one RFP exists.',
        'link'     => 'contracts/rfp-builder/',
        'check'    => ['rows', 'rfps'],
    ],
    [
        'id'       => 'contracts.rfp_scoring',
        'module'   => 'contracts',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Supplier scoring',
        'what'     => 'Scoring each invited supplier against each consolidated requirement, per analyst, then comparing them side by side.',
        'why'      => 'A scored comparison is a decision you can defend to procurement and to the suppliers who lost.',
        'done'     => 'At least one RFP score has been recorded.',
        'link'     => 'contracts/rfp-builder/',
        'check'    => ['rows', 'rfp_scores'],
    ],
];
