<?php
/**
 * Feature Bingo cards - Domains (#154). See includes/feature_bingo.php for the format.
 *
 * Demo rows never count (is_demo = 0): a card lights for something the operator
 * set up, not for sample data they imported to look around.
 */

$real = 'is_demo = 0';

return [
    [
        'id'       => 'domains.first_domain',
        'module'   => 'domains',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Your domains in the register',
        'what'     => 'The organisation\'s domain names, added one at a time, pasted as a list, or imported from a spreadsheet. Each is looked up at its registry and checked straight away.',
        'why'      => 'A lapsed domain takes the website and every email address with it, and renewals are usually remembered only by whoever registered it years ago.',
        'done'     => 'At least one domain is in the register.',
        'link'     => 'domains/',
        'check'    => ['rows', 'domains', $real],
    ],
    [
        'id'       => 'domains.every_owner',
        'module'   => 'domains',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Every domain has an owner',
        'what'     => 'A named analyst on each domain, who receives its renewal reminders and its notifications.',
        'why'      => 'An ownerless domain\'s reminders go to a shared list at best. Renewals slip exactly when "everybody" is responsible.',
        'done'     => 'There are domains, and none of them is without an owner.',
        'link'     => 'domains/?view=all',
        'check'    => ['sql', "SELECT CASE WHEN COUNT(*) > 0 AND SUM(owner_analyst_id IS NULL) = 0 THEN 1 ELSE 0 END FROM domains WHERE $real", 1],
    ],
    [
        'id'       => 'domains.alerts',
        'module'   => 'domains',
        'tier'     => 'essential',
        'category' => 'governance',
        'title'    => 'Domain expiry alerts',
        'what'     => 'Email reminders before a domain or its certificate expires - one digest per person, sent once per window.',
        'why'      => 'They are off until switched on. Without them the register only helps somebody who remembers to open it.',
        'done'     => 'Email alerts are switched on in Domains settings.',
        'link'     => 'domains/settings/?tab=alerts',
        'check'    => ['setting', 'domain_alerts_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'domains.alert_list',
        'module'   => 'domains',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'A shared address for domain alerts',
        'what'     => 'A team mailbox that also receives the alerts, alongside (or instead of) each domain\'s owner.',
        'why'      => 'People go on holiday and leave. A shared mailbox does not.',
        'done'     => 'At least one address is on the alert list.',
        'link'     => 'domains/settings/?tab=alerts',
        'check'    => ['setting', 'domain_alert_emails', 'nonempty'],
    ],
    [
        'id'       => 'domains.schedule',
        'module'   => 'domains',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'The Domains schedule is running',
        'what'     => 'cron/domains.php run hourly: refreshes registry details, runs the daily checks, and sends the alerts.',
        'why'      => 'Without it, dates only refresh and alerts only go out when somebody happens to open Domains.',
        'done'     => 'The scheduled run has completed at least once.',
        'link'     => 'domains/settings/?tab=monitoring',
        'check'    => ['setting', 'domain_cron_last_run', 'nonempty'],
    ],
    [
        'id'       => 'domains.all_locked',
        'module'   => 'domains',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Every domain transfer-locked',
        'what'     => 'The registrar\'s transfer lock switched on for every domain whose registry reports it.',
        'why'      => 'Without it, anybody holding a domain\'s auth code can move it to another registrar - and with it the website and email.',
        'done'     => 'There are domains, and none reports its transfer lock as off.',
        'link'     => 'domains/?view=unlocked',
        'check'    => ['sql', "SELECT CASE WHEN COUNT(*) > 0 AND SUM(transfer_lock = 0) = 0 THEN 1 ELSE 0 END FROM domains WHERE $real", 1],
    ],
    [
        'id'       => 'domains.no_weak_grades',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'No domain graded D or F',
        'what'     => 'Every checked domain scores C or better on the security grade: DNS, email authentication, certificates and locks.',
        'why'      => 'A D or F usually means a domain anyone can send phishing email from, or one about to lapse.',
        'done'     => 'At least one domain has been checked, and none is graded D or F.',
        'link'     => 'domains/?view=weak',
        'check'    => ['sql', "SELECT CASE WHEN SUM(security_grade IS NOT NULL) > 0 AND SUM(security_grade IN ('D', 'F')) = 0 THEN 1 ELSE 0 END FROM domains WHERE $real", 1],
    ],
    [
        'id'       => 'domains.registrar_accounts',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Registrar accounts recorded',
        'what'     => 'The accounts at registrars that hold the domains: which login, who owns it, who holds the second factor.',
        'why'      => 'When a domain lapses at 11pm, "which account is it in and who has the phone?" is the question that decides how long it stays down.',
        'done'     => 'At least one registrar account exists.',
        'link'     => 'domains/accounts/',
        'check'    => ['rows', 'domain_registrar_accounts', $real],
    ],
    [
        'id'       => 'domains.renewal_action',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Renewals raise a task or ticket',
        'what'     => 'At the renewal window, a task or ticket is raised for the domain\'s owner, due on the expiry date.',
        'why'      => 'An email is easy to read and forget; a task with a due date sits in somebody\'s queue until it is done.',
        'done'     => 'The renewal action is set to raise a task or a ticket.',
        'link'     => 'domains/settings/?tab=alerts',
        'check'    => ['setting', 'domain_renewal_action', 'in', ['task', 'ticket']],
    ],
    [
        'id'       => 'domains.ct_watch',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Certificate Transparency watch',
        'what'     => 'A weekly look through the public certificate logs for every certificate issued for your domains.',
        'why'      => 'A certificate you did not ask for is often the first visible sign of a phishing site being built on your name.',
        'done'     => 'The Certificate Transparency watch is switched on.',
        'link'     => 'domains/settings/?tab=monitoring',
        'check'    => ['setting', 'domain_ct_watch', 'eq', '1'],
    ],
    [
        'id'       => 'domains.lookalikes',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Look-alike domain scan',
        'what'     => 'A weekly search for registered names one slip away from your main domains - and whether they can receive email.',
        'why'      => 'A look-alike that receives email can collect invoices and password resets meant for you.',
        'done'     => 'The look-alike scan is switched on.',
        'link'     => 'domains/settings/?tab=monitoring',
        'check'    => ['setting', 'domain_lookalike_scan', 'eq', '1'],
    ],
    [
        'id'       => 'domains.calendar',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Domain renewals in the Calendar',
        'what'     => 'Every domain\'s expiry date as an all-day Calendar entry, alongside contract and warranty dates.',
        'why'      => 'Renewals then show up in the same place as everything else the team plans around.',
        'done'     => 'Where renewals are shown includes the Calendar.',
        'link'     => 'domains/settings/?tab=alerts',
        'check'    => ['setting', 'domain_expiry_surface', 'in', ['calendar', 'both']],
    ],
    [
        'id'       => 'domains.workflow',
        'module'   => 'domains',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'A workflow on a domain event',
        'what'     => 'A workflow triggered by a domain expiring, a certificate expiring, a change being detected, or a look-alike appearing.',
        'why'      => 'Post a lock being removed straight to Teams, or raise a priority ticket - whatever your process is.',
        'done'     => 'At least one active workflow is triggered by a domain event.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', "is_active = 1 AND is_demo = 0 AND trigger_event LIKE 'domain.%'"],
    ],
];
