<?php
/** Feature Bingo cards - Forms: forms, designer features (sections, notes, images, conditional questions, lookups, tables, layout), the portal catalogue, audiences, approval, submission actions, collections and settings. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'forms.first_form',
        'module'   => 'forms',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Build your first form',
        'what'     => 'A form built in the drag-and-drop designer - a new starter request, an equipment order, an inspection - with its own questions and required fields.',
        'why'      => 'A request that arrives as a free-text email is missing the one detail you need half the time. A form asks for everything up front, in the same shape every time.',
        'done'     => 'At least one form exists that was not created by the demo data importer.',
        'link'     => 'forms/',
        'check'    => ['rows', 'forms', 'is_demo = 0'],
    ],
    [
        'id'       => 'forms.portal_catalogue',
        'module'   => 'forms',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Forms in the portal catalogue',
        'what'     => 'A form offered in the self-service portal\'s request catalogue, so customers can fill it in themselves. It is off per form by default.',
        'why'      => 'Customers request what they need in a structured way, any time, without emailing the desk and waiting to be asked the follow-up questions.',
        'done'     => 'At least one active form that was not created by the demo data importer is offered in the portal.',
        'link'     => 'forms/',
        'check'    => ['rows', 'forms', 'is_portal_visible = 1 AND is_active = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'forms.approval',
        'module'   => 'forms',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Approval before a request goes ahead',
        'what'     => 'A named approver on a catalogue form. A portal submission waits in their approvals list until they approve or reject it, with a comment.',
        'why'      => 'Requests that cost money or grant access need someone to say yes first. Approval inside the form means the desk only ever sees requests that are allowed to proceed.',
        'done'     => 'At least one form requires approval and has an approver set.',
        'link'     => 'forms/',
        'check'    => ['rows', 'forms', 'requires_approval = 1 AND approver_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'forms.submission_actions',
        'module'   => 'forms',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Actions when a form is submitted',
        'what'     => 'Actions a form runs by itself when it is submitted, approved or rejected - raise a ticket, create a task, send an email or call a webhook, using the same actions as Workflows.',
        'why'      => 'A form that only files its answers still needs someone to read it and act. With actions, a submitted request turns into the right ticket for the right team straight away.',
        'done'     => 'At least one form has at least one submission action configured.',
        'link'     => 'forms/',
        'check'    => ['rows', 'forms', "submission_actions LIKE '%\"type\"%' AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.sections',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Sections on a long form',
        'what'     => 'Section headings that split a form into named parts, such as "About the new starter" and "Equipment needed".',
        'why'      => 'A form of thirty questions in one run looks like a chore. Sections make it readable and tell the person where they are.',
        'done'     => 'At least one form has a section heading.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "field_type = 'section' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.notes',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Notes on a form',
        'what'     => 'A block of guidance text between questions - an instruction, a warning or a link to a policy - styled as plain, information, warning, danger or success.',
        'why'      => 'Explaining at the point of filling in ("ask your manager for the cost code first") saves a returned form and a round of email.',
        'done'     => 'At least one form has a note block.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "field_type = 'note' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.images',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Pictures on a form',
        'what'     => 'An image block on a form - a diagram, a floor plan, a photo of where to find the serial number.',
        'why'      => 'Some questions are far easier to answer with a picture in front of you. "Which desk?" is simple with the floor plan on the form.',
        'done'     => 'At least one form has an image block.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "field_type = 'image' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.conditional_questions',
        'module'   => 'forms',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Questions that appear when needed',
        'what'     => 'Show-when rules on a question, so it only appears when earlier answers call for it - for example, "Which phone model?" only when "Needs a phone" is ticked.',
        'why'      => 'One form can serve several cases without showing everyone every question. Shorter forms get filled in properly.',
        'done'     => 'At least one form question has a show-when rule.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "config LIKE '%visible_if%' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.lookups',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Lookup questions',
        'what'     => 'A question that asks "which one?" against FreeITSM\'s own records - an asset, a CMDB item or a person - instead of a free-text box.',
        'why'      => 'A picked asset is a real link to the record, not a hostname typed from memory with a typo in it. The answer keeps both the id and the name it had at the time.',
        'done'     => 'At least one form has a lookup question.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "field_type = 'lookup' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.portal_lookups',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Lookups customers can use',
        'what'     => 'A lookup on an asset or CMDB item that has been allowed on the portal, so a customer can pick "which laptop" from their own company\'s records. The people directory is never offered.',
        'why'      => 'Customers rarely know a hostname. Letting them pick their device means the request arrives already linked to the right asset.',
        'done'     => 'At least one lookup question has been allowed on the portal.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "field_type = 'lookup' AND config LIKE '%\"portal_lookup\":true%' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.tables',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Table questions',
        'what'     => 'A question answered as a table of rows and columns, each column its own type - text, number, dropdown, date and so on.',
        'why'      => 'An equipment order or a list of accounts to create is naturally a table. One table question beats ten numbered copies of the same three fields.',
        'done'     => 'At least one form has a table question.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "field_type = 'grid' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.field_widths',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Questions side by side',
        'what'     => 'Narrower question widths, so short questions such as first name and surname sit on one line instead of each taking a full row.',
        'why'      => 'A form laid out like the paper one people are used to is quicker to fill in and fits on fewer pages when exported to PDF.',
        'done'     => 'At least one form question has a width other than full.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_fields', "config LIKE '%\"width\"%' AND is_deleted = 0 AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.grid_layout',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Grid layout for a form',
        'what'     => 'A form laid out as a grid, where a question can span rows and a cell can be left empty, rather than simply flowing top to bottom.',
        'why'      => 'Recreating an existing paper or PDF form exactly - an inspection sheet, a site survey - is easier to get accepted than asking people to learn a new shape.',
        'done'     => 'At least one form uses the grid layout.',
        'link'     => 'forms/',
        'check'    => ['rows', 'forms', "layout LIKE '%\"type\":\"grid\"%' AND is_demo = 0"],
    ],
    [
        'id'       => 'forms.collections',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Form collections',
        'what'     => 'A named collection - "2026 annual audit", "Office move" - that new submissions of its forms are stamped into, so they can be read and reported on together and closed when the exercise is over.',
        'why'      => 'A recurring exercise keeps each round\'s answers separate without copying the forms, and closing it can stop late submissions arriving.',
        'done'     => 'At least one collection has at least one form paired with it.',
        'link'     => 'forms/settings/?tab=collections',
        'check'    => ['sql', 'SELECT COUNT(*) FROM forms f JOIN form_collections c ON c.id = f.collection_id WHERE c.is_demo = 0'],
    ],
    [
        'id'       => 'forms.collection_close_effect',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'What closing a collection does',
        'what'     => 'Whether closing a collection is only a label, stops its forms accepting new submissions, or also hides them from the portal.',
        'why'      => 'If a closed survey should really be closed, set it here, so nobody has to remember to switch each form off by hand on the last day.',
        'done'     => 'An administrator has saved a choice for what closing a collection does (any option counts).',
        'link'     => 'forms/settings/?tab=collections',
        'check'    => ['setting', 'forms_collection_close_effect', 'nonempty'],
    ],
    [
        'id'       => 'forms.logo_alignment',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Logo position on forms',
        'what'     => 'Whether your company logo sits on the left, centre or right at the top of every form. It is centred by default.',
        'why'      => 'Matching your existing letterhead makes forms look like your own documents rather than a system printout.',
        'done'     => 'An administrator has saved the logo alignment (any value, including centre).',
        'link'     => 'forms/settings/?tab=layout',
        'check'    => ['setting', 'forms_logo_alignment', 'nonempty'],
    ],
    [
        'id'       => 'forms.ai_assist',
        'module'   => 'forms',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Build forms with AI',
        'what'     => 'An AI provider and key for the designer\'s AI assist, which drafts a whole form - title, questions and options - from a sentence describing what you need.',
        'why'      => 'Describe "a leaver form for HR" and start from a sensible draft to edit, instead of adding twenty questions one at a time.',
        'done'     => 'An API key has been saved for the Forms AI provider.',
        'link'     => 'forms/settings/?tab=ai',
        'check'    => ['setting', 'forms_ai_api_key', 'nonempty'],
    ],
];
