<?php
/** Feature Bingo cards - Knowledge: articles, folders and permissions, audiences, tags, owners and review dates, sharing, AI, embeddings, the assistant and settings. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'knowledge.first_article',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Write your first article',
        'what'     => 'A knowledge article: a how-to, a fix or a procedure written once in the rich-text editor, searchable by everyone on the desk.',
        'why'      => 'Every answer that lives only in one analyst\'s head gets worked out again from scratch the next time. An article turns a repeat call into a two-minute job.',
        'done'     => 'At least one published article exists that is not in the recycle bin and was not created by the demo data importer.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_articles', 'is_demo = 0 AND is_archived = 0 AND is_published = 1'],
    ],
    [
        'id'       => 'knowledge.twenty_articles',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'A knowledge base worth searching',
        'what'     => 'Twenty or more live articles - enough that searching the knowledge base is the first thing an analyst does, not the last.',
        'why'      => 'A knowledge base with three articles in it teaches people not to look. Past a couple of dozen, a search usually finds something and the habit sticks.',
        'done'     => 'At least 20 published articles exist outside the recycle bin that were not created by the demo data importer.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_articles', 'is_demo = 0 AND is_archived = 0 AND is_published = 1', 20],
    ],
    [
        'id'       => 'knowledge.folders',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Folders for articles',
        'what'     => 'A folder tree in the left panel. Each article lives in exactly one folder, and folders can hold their own permissions.',
        'why'      => 'A flat list stops being browsable after a few dozen articles. Folders by team, service or topic let people find things by looking as well as by searching.',
        'done'     => 'At least one knowledge folder exists.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_folders'],
    ],
    [
        'id'       => 'knowledge.nested_folders',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Folders inside folders',
        'what'     => 'Sub-folders, so a top-level area such as "Infrastructure" can be broken down into "Network", "Servers" and "Backups".',
        'why'      => 'Once a single folder holds more than a screenful, a second level keeps it navigable without inventing ever-longer folder names.',
        'done'     => 'At least one knowledge folder sits inside another folder.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_folders', 'parent_id IS NOT NULL'],
    ],
    [
        'id'       => 'knowledge.shortcuts',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Article shortcuts',
        'what'     => 'A pointer that makes one article appear in a second folder without copying it. The shortcut carries no permissions of its own - the original article\'s rules still decide who can read it.',
        'why'      => 'An article that belongs in two places stays one article, so an edit is never made to one copy and missed on the other.',
        'done'     => 'At least one knowledge shortcut exists.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_shortcuts'],
    ],
    [
        'id'       => 'knowledge.restricted_content',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Folder and article permissions',
        'what'     => 'Named analysts, teams, portal users or user groups on a folder or article, either as the only people allowed in (Restricted) or as the people kept out (Open).',
        'why'      => 'Some documents - HR procedures, security runbooks, break-glass passwords - should not be readable by everyone who has the Knowledge module. Permissions narrow access without a separate system.',
        'done'     => 'At least one folder or article is marked Restricted, or has at least one person or group on its access list.',
        'link'     => 'knowledge/',
        'check'    => ['any', [
            ['rows', 'knowledge_acl'],
            ['rows', 'knowledge_folders', 'is_restricted = 1'],
            ['rows', 'knowledge_articles', 'is_restricted = 1 AND is_demo = 0'],
        ]],
    ],
    [
        'id'       => 'knowledge.group_permissions',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Permissions by user group',
        'what'     => 'A user group named on a folder or article\'s access list, instead of listing each person one by one.',
        'why'      => 'Three contractors on site for a week go into one group with an end date, and the folder is closed to them again by the clock rather than by somebody remembering.',
        'done'     => 'At least one knowledge access list entry names a user group.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'knowledge_acl', "principal_type = 'user_group'"],
    ],
    [
        'id'       => 'knowledge.permission_model',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'How folder permissions apply',
        'what'     => 'Whether a folder\'s permissions protect everything inside it at every level (containers), or only what inherits from it (filing). Before it changes, FreeITSM counts how many readings would be gained or lost.',
        'why'      => 'It decides whether a document someone files into a restricted folder is automatically protected. Choosing deliberately avoids discovering the answer after a sensitive document has been read.',
        'done'     => 'An administrator has saved a choice on the Permissions tab (either option counts).',
        'link'     => 'knowledge/settings/',
        'check'    => ['setting', 'knowledge_folder_permission_model', 'nonempty'],
    ],
    [
        'id'       => 'knowledge.customer_articles',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Articles in the portal Help Centre',
        'what'     => 'Articles whose audience is "Analysts and signed-in customers", which appear in the Help Centre of the self-service portal.',
        'why'      => 'A customer who can find "how do I connect to the VPN" themselves never raises the ticket. Self-help deflects the easiest calls off the desk entirely.',
        'done'     => 'At least one article is set to the customer or public audience.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_articles', "audience IN ('customer','public') AND is_demo = 0"],
    ],
    [
        'id'       => 'knowledge.public_articles',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Public articles for web chat',
        'what'     => 'Articles marked "Also allow anyone on the internet", which the web chat widget on your website can answer visitors from.',
        'why'      => 'An anonymous visitor asking a common question gets an answer straight away instead of waiting for a person. Only ever mark things public you would show a stranger.',
        'done'     => 'At least one article is set to the public audience.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_articles', "audience = 'public' AND is_demo = 0"],
    ],
    [
        'id'       => 'knowledge.company_articles',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Company-specific articles',
        'what'     => 'Articles and folders that belong to one company rather than being shared with all of them. Leaving the company blank shares it with everyone.',
        'why'      => 'If you support several organisations, one client\'s network diagram or procedures should never appear to another client\'s staff.',
        'done'     => 'At least one article or folder is assigned to a specific company.',
        'link'     => 'knowledge/',
        'check'    => ['any', [
            ['rows', 'knowledge_articles', 'tenant_id IS NOT NULL AND is_demo = 0'],
            ['rows', 'knowledge_folders', 'tenant_id IS NOT NULL'],
        ]],
    ],
    [
        'id'       => 'knowledge.tags',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Tag your articles',
        'what'     => 'Short labels such as "VPN", "Outlook" or "Onboarding" on articles, which cut across folders.',
        'why'      => 'An article about Outlook on a phone belongs in one folder but is relevant to two topics. Tags let people filter to everything about a subject wherever it is filed.',
        'done'     => 'At least one article has a tag that was not created by the demo data importer.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_article_tags', 'is_demo = 0'],
    ],
    [
        'id'       => 'knowledge.owners',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Article owners',
        'what'     => 'A named owner on an article - the person responsible for keeping it accurate.',
        'why'      => 'An article that belongs to everyone is maintained by no one. An owner is who gets asked when it is wrong and who reviews it when it comes due.',
        'done'     => 'At least one article that was not created by the demo data importer has an owner.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_articles', 'owner_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'knowledge.review_dates',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Article review dates',
        'what'     => 'A next-review date on an article. When it arrives, the article shows up on the Review page so its owner can check it is still right.',
        'why'      => 'Knowledge goes stale quietly: a screenshot of the old portal, a server that has been retired. A review date makes someone look before a customer follows out-of-date steps.',
        'done'     => 'At least one article that was not created by the demo data importer has a next review date.',
        'link'     => 'knowledge/review/',
        'check'    => ['rows', 'knowledge_articles', 'next_review_date IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'knowledge.recycle_bin',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Recycle bin retention',
        'what'     => 'How many days a deleted article stays in the recycle bin before it is removed for good. The default is 30.',
        'why'      => 'Long enough to recover from a mistaken delete, short enough that the bin does not become a second, hidden knowledge base. Set it to match your records policy.',
        'done'     => 'An administrator has saved the recycle bin retention period (any value, including the default).',
        'link'     => 'knowledge/settings/',
        'check'    => ['setting', 'knowledge_recycle_bin_days', 'nonempty'],
    ],
    [
        'id'       => 'knowledge.email_sharing',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Email articles out',
        'what'     => 'How the Share button sends an article by email - through your own SMTP server or one of your Microsoft 365 mailboxes. It is off until one is chosen. Change Management\'s share button uses the same settings.',
        'why'      => 'Sending a customer the article itself, formatted, is quicker and clearer than pasting steps into a reply, and it points them at the knowledge base for next time.',
        'done'     => 'The email method on the Email tab is set to SMTP or a mailbox.',
        'link'     => 'knowledge/settings/',
        'check'    => ['setting', 'knowledge_email_method', 'in', ['smtp', 'mailbox']],
    ],
    [
        'id'       => 'knowledge.ai_chat',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'ai',
        'title'    => 'Ask AI over your articles',
        'what'     => 'An AI provider (Anthropic, OpenAI, OpenRouter or Azure OpenAI) and key for the Ask AI panel, which answers questions from your own articles and says which ones it used.',
        'why'      => 'Analysts ask in plain words - "why can\'t Sarah print from home?" - and get an answer drawn from what the team has already written, instead of guessing the right search term.',
        'done'     => 'An API key has been saved for the Knowledge AI provider.',
        'link'     => 'knowledge/settings/',
        'check'    => ['setting', 'knowledge_ai_api_key', 'nonempty'],
    ],
    [
        'id'       => 'knowledge.openai_embeddings_key',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Semantic search key',
        'what'     => 'An OpenAI key used to turn articles into embeddings, so Ask AI, the web chat widget and the Knowledge assistant pick the relevant articles by meaning rather than by matching words.',
        'why'      => 'A question about "can\'t get on the Wi-Fi" is answered from the article titled "Wireless connection problems", even though none of the words match. It also sharpens how the assistant groups tickets into gaps.',
        'done'     => 'An OpenAI key for embeddings has been saved.',
        'link'     => 'knowledge/settings/',
        'check'    => ['setting', 'knowledge_openai_api_key', 'nonempty'],
    ],
    [
        'id'       => 'knowledge.embeddings_generated',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Generate article embeddings',
        'what'     => 'Running Generate on the Embeddings tab, which sends each article to OpenAI once and stores the result for meaning-based matching.',
        'why'      => 'The key alone does nothing until articles are embedded. Doing it once after setup, and again after a big import, means every article can be found by meaning.',
        'done'     => 'At least one article has an embedding stored.',
        'link'     => 'knowledge/settings/',
        'check'    => ['rows', 'knowledge_articles', 'embedding IS NOT NULL AND is_archived = 0'],
    ],
    [
        'id'       => 'knowledge.assistant_key',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'A separate key for the assistant',
        'what'     => 'Its own AI provider, model and key for the Knowledge assistant, which drafts articles from closed tickets. Left blank, it reuses the Ask AI key.',
        'why'      => 'A separate key puts the assistant\'s spend on its own line of your provider\'s bill, and lets you give it a stronger model than day-to-day chat needs.',
        'done'     => 'An API key has been saved for the Knowledge assistant.',
        'link'     => 'knowledge/settings/',
        'check'    => ['setting', 'knowledge_writeup_api_key', 'nonempty'],
    ],
    [
        'id'       => 'knowledge.gap_analysis',
        'module'   => 'knowledge',
        'tier'     => 'recommended',
        'category' => 'ai',
        'title'    => 'Find what the knowledge base is missing',
        'what'     => 'The Knowledge assistant reads your closed tickets, groups the questions the desk keeps answering, and lists the ones no article covers - each with the evidence and a draft.',
        'why'      => '"You have answered this fourteen times and have no article" is the most useful thing a knowledge manager can be told. It aims writing effort where it saves the most calls.',
        'done'     => 'The assistant has been run at least once and found or analysed something.',
        'link'     => 'knowledge/assistant/',
        'check'    => ['any', [
            ['rows', 'knowledge_gap_clusters'],
            ['rows', 'knowledge_gap_tickets'],
        ]],
    ],
    [
        'id'       => 'knowledge.gap_written',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Close a knowledge gap',
        'what'     => 'Writing the article for a gap the assistant found, which marks that gap as written.',
        'why'      => 'This is where the analysis pays off: the next customer with that question gets an article instead of a ticket.',
        'done'     => 'At least one knowledge gap has been marked written.',
        'link'     => 'knowledge/assistant/',
        'check'    => ['rows', 'knowledge_gap_clusters', "status = 'written'"],
    ],
    [
        'id'       => 'knowledge.gap_tuning',
        'module'   => 'knowledge',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Tune when the assistant speaks up',
        'what'     => 'How many times a question must come up, how far back to read, and how alike tickets and articles must be before the assistant suggests an article.',
        'why'      => 'A small internal team wants an article for anything asked twice; a busy MSP desk wants a higher bar. The defaults are a middle ground, not a fit for everyone.',
        'done'     => 'At least one of the assistant\'s tuning settings has been saved.',
        'link'     => 'knowledge/settings/',
        'check'    => ['any', [
            ['setting', 'knowledge_gap_min_cluster', 'nonempty'],
            ['setting', 'knowledge_gap_lookback_days', 'nonempty'],
            ['setting', 'knowledge_gap_article_threshold', 'nonempty'],
            ['setting', 'knowledge_gap_cluster_threshold', 'nonempty'],
            ['setting', 'knowledge_gap_min_richness', 'nonempty'],
        ]],
    ],
];
