<?php
/** Feature Bingo cards - LMS: courses (SCORM and native), knowledge checks, learning groups, assignments, deadlines, portal training, reminders and AI authoring. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'lms.first_course',
        'module'   => 'lms',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Add your first course',
        'what'     => 'A training course in the LMS, either an uploaded SCORM package or one written directly in FreeITSM.',
        'why'      => 'Training that lives next to the service desk gets done: analysts see it where they already work, and progress is tracked without a separate LMS or login.',
        'done'     => 'At least one course exists that was not created by the demo data importer.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_courses', 'is_demo = 0'],
    ],
    [
        'id'       => 'lms.native_course',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Write a course in FreeITSM',
        'what'     => 'A course authored here - lessons in a rich-text editor, questions at the end of each one - rather than built in an external tool and uploaded.',
        'why'      => 'You do not need Articulate, Rise or any other authoring licence to publish training. A short how-to course can be written in the time it takes to write the email announcing it.',
        'done'     => 'At least one native (authored in FreeITSM) course exists that was not created by the demo data importer.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_courses', "content_type = 'native' AND is_demo = 0"],
    ],
    [
        'id'       => 'lms.scorm_course',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Upload a SCORM package',
        'what'     => 'A SCORM 1.1, 1.2 or 2004 course from an authoring tool or a training vendor, uploaded as a ZIP and played in FreeITSM\'s built-in player.',
        'why'      => 'Security awareness and compliance courses you have already bought usually come as SCORM. Running them here puts completions beside the rest of your training records.',
        'done'     => 'At least one SCORM course exists that was not created by the demo data importer.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_courses', "content_type = 'scorm' AND is_demo = 0"],
    ],
    [
        'id'       => 'lms.knowledge_checks',
        'module'   => 'lms',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Knowledge checks in a course',
        'what'     => 'Questions at the end of a lesson in a native course. Marking happens on the server, so the answer key never reaches the learner\'s browser.',
        'why'      => 'Reaching the last page proves someone clicked Next. A few questions prove they took it in, and show you which lesson needs rewriting when everyone gets the same one wrong.',
        'done'     => 'At least one course question exists that was not created by the demo data importer.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_questions', 'is_demo = 0'],
    ],
    [
        'id'       => 'lms.pass_mark',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'A pass mark on a course',
        'what'     => 'A minimum score for a native course. Learners are marked Passed or Not passed against it and can retake the course; without one, finishing is enough.',
        'why'      => 'For mandatory training - data protection, security - "completed" should mean "understood". A pass mark gives you a record you can show an auditor.',
        'done'     => 'At least one course that was not created by the demo data importer has a pass mark set.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_courses', 'pass_mark IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'lms.learning_groups',
        'module'   => 'lms',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Learning groups',
        'what'     => 'Named groups of analysts - "Tier 1", "New starters" - that courses are assigned to. Anyone added to a group later picks up its courses automatically.',
        'why'      => 'Assigning to a group instead of a list of names means a new starter gets the right training the day they are added, without anyone remembering to do it.',
        'done'     => 'At least one learning group has at least one member, neither created by the demo data importer.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_learning_group_members', 'is_demo = 0'],
    ],
    [
        'id'       => 'lms.assignments',
        'module'   => 'lms',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Assign a course',
        'what'     => 'An assignment that says who a course is for. As soon as it is saved, those people see it and appear on the Progress tab as Not Started.',
        'why'      => 'A course nobody is assigned to is a course nobody takes. Assignments turn a library into a training plan with a progress report.',
        'done'     => 'At least one course assignment exists that was not created by the demo data importer.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_course_assignments', 'is_demo = 0'],
    ],
    [
        'id'       => 'lms.deadlines',
        'module'   => 'lms',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Training deadlines',
        'what'     => 'A due date on an assignment. It drives the Overdue filter on the Progress tab and the reminder emails.',
        'why'      => 'Without a date, "please complete your training" has no end and is never urgent. A deadline makes overdue training visible and chaseable.',
        'done'     => 'At least one course assignment that was not created by the demo data importer has a deadline.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_course_assignments', 'deadline IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'lms.portal_training',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Training for portal users',
        'what'     => 'A course assigned to a user group or to everyone on the portal. Portal users take it in the self-service portal, with the same player and the same marking.',
        'why'      => 'Training is not only for IT. Staff who only ever use the portal can be given the new-starter or security course, and their passes sit on the same Progress tab as everyone else\'s.',
        'done'     => 'At least one course is assigned to a user group or to everyone on the portal.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_course_assignments', "target_type IN ('user_group','all_users') AND is_demo = 0"],
    ],
    [
        'id'       => 'lms.everyone_training',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Mandatory training for everyone',
        'what'     => 'A course assigned to "Everyone on the portal", which reaches every active self-service account, including people added later.',
        'why'      => 'This is how organisation-wide training such as security awareness is pushed in one instruction, rather than through a list someone has to keep up to date by hand.',
        'done'     => 'At least one course is assigned to everyone on the portal.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_course_assignments', "target_type = 'all_users' AND is_demo = 0"],
    ],
    [
        'id'       => 'lms.reminders',
        'module'   => 'lms',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Training reminder emails',
        'what'     => 'Emails to people whose training is nearly due, a set number of days before the deadline. The settings screen tells you how many would go out before you switch it on.',
        'why'      => 'Portal users have no reason to sign in unless they are told to. Reminders are what make assigned training actually get done, without someone chasing by hand.',
        'done'     => 'Training reminders are switched on (they are off by default).',
        'link'     => 'lms/settings/',
        'check'    => ['setting', 'lms_reminders_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'lms.reminder_chase',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Chase overdue training',
        'what'     => 'Keep reminding people after the deadline has passed, every so many days, until the course is done.',
        'why'      => 'One reminder before the deadline is easy to ignore. A polite repeat after it is what closes the last ten per cent of a compliance campaign.',
        'done'     => 'Reminders are switched on and chasing overdue training has been saved as on.',
        'link'     => 'lms/settings/',
        'check'    => ['all', [
            ['setting', 'lms_reminders_enabled', 'eq', '1'],
            ['setting', 'lms_reminder_chase_overdue', 'eq', '1'],
        ]],
    ],
    [
        'id'       => 'lms.ai_authoring',
        'module'   => 'lms',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI course authoring',
        'what'     => 'An AI provider and key for the course editor\'s helpers: draft a course outline from a topic, a lesson from a title or a knowledge article, and quiz questions from a lesson.',
        'why'      => 'The blank page is the slowest part of writing training. The AI drafts, you review and press Save, so a course that would take an afternoon takes an hour.',
        'done'     => 'An API key has been saved for the LMS AI provider.',
        'link'     => 'lms/settings/',
        'check'    => ['setting', 'lms_ai_api_key', 'nonempty'],
    ],
];
