<?php
/** Feature Bingo cards - Morning Checks: the checks, statuses, groups and routing, and using the round. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'morning-checks.checks',
        'module'   => 'morning-checks',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Define your morning checks',
        'what'     => 'The list of operational checks your team works through each day - backups completed, disk space, replication, certificate expiry - each marked with a status on the dashboard.',
        'why'      => 'A written round means the backup that failed overnight is found at 8am by the desk, not at 10am by the person who needed the restore.',
        'done'     => 'At least one check exists that was not created by the demo data importer.',
        'link'     => 'morning-checks/settings/',
        'check'    => ['rows', 'morningChecks_Checks', 'is_demo = 0'],
    ],
    [
        'id'       => 'morning-checks.descriptions',
        'module'   => 'morning-checks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Say what to look for',
        'what'     => 'An optional description on each check telling the analyst what to look at and what good looks like.',
        'why'      => 'The person covering the round on a Monday after a holiday should not have to guess where the backup report lives. A description turns the check into a mini runbook.',
        'done'     => 'At least one real (non-demo) check has a description.',
        'link'     => 'morning-checks/settings/',
        'check'    => ['rows', 'morningChecks_Checks', "CheckDescription IS NOT NULL AND CheckDescription <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'morning-checks.statuses_tailored',
        'module'   => 'morning-checks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Check statuses',
        'what'     => 'The buttons analysts press against each check, with a colour, an order and whether a note is required. FreeITSM ships Green, Amber and Red.',
        'why'      => 'Some checks have honest answers that are neither pass nor fail - "Not applicable", "Vendor notified". Adding them stops people forcing a Red or a Green that is not true.',
        'done'     => 'At least one check status has a label other than the shipped Green, Amber and Red, or one of those has been removed.',
        'link'     => 'morning-checks/settings/',
        'check'    => ['any', [
            ['rows', 'morningChecks_Statuses', "Label NOT IN ('Green','Amber','Red')"],
            ['sql', 'SELECT COUNT(*) < 3 FROM morningChecks_Statuses'],
        ]],
    ],
    [
        'id'       => 'morning-checks.groups',
        'module'   => 'morning-checks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Group the round',
        'what'     => 'Optional groups such as "Infrastructure" or "Business systems", so grouped checks appear together under a heading on the dashboard.',
        'why'      => 'A round of forty checks is easier to work through, and easier to hand over, in sections than as one long list.',
        'done'     => 'At least one check group exists.',
        'link'     => 'morning-checks/settings/',
        'check'    => ['rows', 'morningChecks_Groups'],
    ],
    [
        'id'       => 'morning-checks.group_routing',
        'module'   => 'morning-checks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Route groups to a team',
        'what'     => 'A group can be pointed at a team or a named analyst, and a Mine filter then lets each person narrow the board to their own part of the round.',
        'why'      => 'On a bigger desk it says who normally picks up which checks, without stopping anyone else completing them when that person is away.',
        'done'     => 'At least one check group is routed to a team or an analyst.',
        'link'     => 'morning-checks/settings/',
        'check'    => ['rows', 'morningChecks_Groups', 'AssignedTeamID IS NOT NULL OR AssignedAnalystID IS NOT NULL'],
    ],
    [
        'id'       => 'morning-checks.check_routing',
        'module'   => 'morning-checks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Route a check to someone',
        'what'     => 'A single check can be routed to one analyst, overriding its group - for the item in a shared group that really does belong to one person.',
        'why'      => 'The payroll interface check that only one person understands should say so on the board, so it is obvious who to ask when it goes amber.',
        'done'     => 'At least one real (non-demo) check is routed to an analyst.',
        'link'     => 'morning-checks/settings/',
        'check'    => ['rows', 'morningChecks_Checks', 'AssignedAnalystID IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'morning-checks.round_done',
        'module'   => 'morning-checks',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Complete a morning round',
        'what'     => 'Recording a status against each check on the dashboard, which feeds the 30-day trend chart and the daily PDF report.',
        'why'      => 'Results recorded every day are what make the trend chart useful - the backup that goes amber every Monday only shows up once there are Mondays to compare.',
        'done'     => 'At least one real (non-demo) check result has been recorded.',
        'link'     => 'morning-checks/',
        'check'    => ['rows', 'morningChecks_Results', 'is_demo = 0'],
    ],
    [
        'id'       => 'morning-checks.raise_from_check',
        'module'   => 'morning-checks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Raise tickets from checks',
        'what'     => 'The + action on a completed check raises a ticket or a task with the check name, status and notes already filled in, and links it to the result.',
        'why'      => 'A Red check is only useful if someone fixes it. Raising the work straight from the check means it is tracked, and the link shows what was done about it.',
        'done'     => 'At least one ticket or task has been raised from a morning check.',
        'link'     => 'morning-checks/',
        'check'    => ['rows', 'morningChecks_ResultLinks'],
    ],
];
