<?php
/** Feature Bingo cards - Network Mapper: diagrams bound to the CMDB, connectors, versions, page layout and header/footer branding. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'network-mapper.diagram',
        'module'   => 'network-mapper',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'A network diagram',
        'what'     => 'A diagram drawn on top of the CMDB, where every node is bound to a real configuration item rather than a shape with a label.',
        'why'      => 'A diagram tied to the CMDB does not drift out of date the way a Visio file on a shared drive does, and each node opens the object\'s full record.',
        'done'     => 'At least one diagram exists (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagrams', 'is_demo = 0'],
    ],
    [
        'id'       => 'network-mapper.nodes',
        'module'   => 'network-mapper',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'CMDB objects placed on a diagram',
        'what'     => 'Dragging a class from the palette onto the canvas and binding it to a CMDB object, with "Add related objects" pulling in what it connects to.',
        'why'      => 'Related objects arrive with their connections already drawn from the CMDB, so a service map takes minutes rather than an afternoon.',
        'done'     => 'At least one node has been placed on a diagram (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagram_nodes', 'is_demo = 0'],
    ],
    [
        'id'       => 'network-mapper.traced_connectors',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Connectors traced to relationships',
        'what'     => 'Lines on a diagram that record the CMDB relationship they represent, drawn through "Add related objects".',
        'why'      => 'Every line can be traced back to a real link in the CMDB, so the picture and the data cannot quietly disagree.',
        'done'     => 'At least one connector is tied to a CMDB relationship (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagram_connectors', 'cmdb_relationship_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'network-mapper.connector_styles',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Labelled and styled connectors',
        'what'     => 'A label on a connector, such as "VPN" or "10 Gb", or a dashed or dotted line style.',
        'why'      => 'Tells a reader what kind of link it is - a backup path, a wireless hop - without opening anything.',
        'done'     => 'At least one connector has a label or a line style other than solid (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagram_connectors', "is_demo = 0 AND ((label IS NOT NULL AND label <> '') OR (line_style IS NOT NULL AND line_style <> 'solid'))"],
    ],
    [
        'id'       => 'network-mapper.icon_overrides',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Custom node icons',
        'what'     => 'Choosing a different icon for one node than its CMDB class uses.',
        'why'      => 'Makes the one load balancer or firewall that matters stand out on a busy diagram.',
        'done'     => 'At least one node has its icon overridden (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagram_nodes', 'icon_override IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'network-mapper.versions',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Diagram versions',
        'what'     => 'Saving a diagram as a new version, which copies it forward and keeps the old one as read-only history.',
        'why'      => 'You can show exactly what the network looked like before a change, and compare it with afterwards.',
        'done'     => 'At least one diagram has been saved as a new version (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagrams', 'parent_diagram_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'network-mapper.paper_size',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Page outline for printing',
        'what'     => 'A paper-size overlay on a diagram - A4, A3, A2, Letter or Tabloid, portrait or landscape - remembered per diagram.',
        'why'      => 'You compose inside the printable area as you go, so nothing is cropped when the diagram is printed or shared. It is also what the header and footer hang from.',
        'done'     => 'At least one diagram has a paper size set (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagrams', 'paper_size IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'network-mapper.header_footer_defaults',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Diagram header and footer',
        'what'     => 'Organisation-wide text for the six header and footer slots on a diagram page, mixing plain text with the logo, title, author, version and modified date.',
        'why'      => 'Every printed diagram carries your logo, who drew it and which version it is, so an old printout on a wall can be recognised as old.',
        'done'     => 'The header and footer defaults have been saved under System - Branding.',
        'link'     => 'system/branding/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key IN ('branding_header_left', 'branding_header_center', 'branding_header_right', 'branding_footer_left', 'branding_footer_center', 'branding_footer_right')"],
    ],
    [
        'id'       => 'network-mapper.header_footer_override',
        'module'   => 'network-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Per-diagram header and footer',
        'what'     => 'Overriding one or more header or footer slots on a single diagram, such as a classification or a project name.',
        'why'      => 'A diagram for a customer or a change board can say so on the page without changing every other diagram.',
        'done'     => 'At least one diagram overrides a header or footer slot (demo data not counted).',
        'link'     => 'network-mapper/',
        'check'    => ['rows', 'network_diagrams', 'is_demo = 0 AND (header_left IS NOT NULL OR header_center IS NOT NULL OR header_right IS NOT NULL OR footer_left IS NOT NULL OR footer_center IS NOT NULL OR footer_right IS NOT NULL)'],
    ],
];
