<?php
/** Feature Bingo cards - Problem Management: problems, known errors, root cause, the incident and change links, lookups and Problem AI. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'problems.first_problem',
        'module'   => 'problems',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Raise your first problem',
        'what'     => 'A problem record for the underlying cause behind one or more incidents, investigated separately from the tickets so the desk can keep closing them quickly.',
        'why'      => 'Fixing the same thing for the third time is the sign. A problem record is how you stop fixing it and start removing it, and how recurring incidents eventually stop arriving.',
        'done'     => 'At least one problem exists.',
        'link'     => 'problem-management/new/',
        'check'    => ['rows', 'problems'],
    ],
    [
        'id'       => 'problems.linked_incidents',
        'module'   => 'problems',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Link incidents to problems',
        'what'     => 'Tickets linked to the problem that explains them, from the Problem strip on a ticket or Link incident on the problem.',
        'why'      => 'A problem with no linked incidents has no evidence and no measurable impact. Linking shows how widespread it is and gives the root-cause work something real to go on.',
        'done'     => 'At least one ticket is linked to a problem.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'problem_tickets'],
    ],
    [
        'id'       => 'problems.root_cause',
        'module'   => 'problems',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Record root causes',
        'what'     => 'The Root cause field on a problem, where the conclusion of the analysis - 5 Whys, fishbone, timeline or whatever you used - is written down in plain words.',
        'why'      => 'Written down, the next analyst understands the cause without redoing the investigation. Left in someone\'s head, it leaves with them.',
        'done'     => 'At least one problem has a root cause recorded.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'problems', "root_cause IS NOT NULL AND root_cause <> ''"],
    ],
    [
        'id'       => 'problems.known_errors',
        'module'   => 'problems',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Known errors',
        'what'     => 'A problem marked as a known error: the cause is understood and there is a documented workaround, even though the permanent fix has not shipped yet.',
        'why'      => 'When a matching incident comes in, the analyst applies the workaround and closes it in minutes instead of diagnosing it again. Warbot\'s /known command finds them during an outage too.',
        'done'     => 'At least one problem is marked as a known error.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'problems', 'is_known_error = 1'],
    ],
    [
        'id'       => 'problems.workarounds',
        'module'   => 'problems',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Documented workarounds',
        'what'     => 'The Workaround field on a problem: the exact steps that get an affected user working again while the permanent fix is arranged.',
        'why'      => 'A specific, repeatable workaround is worth having on day one, long before the fix. "Restart it" is not a workaround; written steps are.',
        'done'     => 'At least one problem has a workaround written.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'problems', "workaround IS NOT NULL AND workaround <> ''"],
    ],
    [
        'id'       => 'problems.linked_change',
        'module'   => 'problems',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Link the fixing change',
        'what'     => 'Link change on a problem connects it to the Change Management record that delivers the permanent fix.',
        'why'      => 'It completes the chain - the incidents that hurt, the problem that explained them, and the change that fixed them - which is what an auditor or a post-incident review will ask to see.',
        'done'     => 'At least one change is linked to a problem as its fix.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'change_relations', "related_type = 'problem'"],
    ],
    [
        'id'       => 'problems.notes',
        'module'   => 'problems',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Investigation notes',
        'what'     => 'A dated journal of notes on a problem - what was tried, what was ruled out, what the vendor said - separate from the audit of field changes.',
        'why'      => 'Problems can stay open for weeks. A running journal means whoever picks it up next starts from where the investigation got to, not from the beginning.',
        'done'     => 'At least one note has been added to a problem.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'problem_notes'],
    ],
    [
        'id'       => 'problems.resolved',
        'module'   => 'problems',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Close the loop on a problem',
        'what'     => 'Moving a problem to a closed status once the fix is in place and the linked incidents have stopped recurring.',
        'why'      => 'A known error that is never resolved keeps having its workaround applied long after the cause is gone. Closing problems keeps the list of known errors honest.',
        'done'     => 'At least one problem has been closed.',
        'link'     => 'problem-management/',
        'check'    => ['rows', 'problems', 'closed_datetime IS NOT NULL'],
    ],
    [
        'id'       => 'problems.statuses_tailored',
        'module'   => 'problems',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Problem statuses',
        'what'     => 'The stages of the problem lifecycle. FreeITSM ships six ITIL-aligned ones, from New to Closed, which you can rename, recolour, add to or retire.',
        'why'      => 'If your process has a stage the defaults do not - "Awaiting vendor", say - adding it means the list shows where each investigation is really stuck.',
        'done'     => 'At least one problem status has a name other than the six shipped ones, or one of those has been removed.',
        'link'     => 'problem-management/settings/',
        'check'    => ['any', [
            ['rows', 'problem_statuses', "name NOT IN ('New','Investigating','Root Cause Identified','Known Error','Resolved','Closed')"],
            ['sql', 'SELECT COUNT(*) < 6 FROM problem_statuses'],
        ]],
    ],
    [
        'id'       => 'problems.priorities_tailored',
        'module'   => 'problems',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Problem priorities',
        'what'     => 'The priority scale for problems, with a colour for each and a default for new ones.',
        'why'      => 'Problems compete for the same people as tickets. A scale your team agrees on decides which root cause gets investigated first.',
        'done'     => 'At least one problem priority has a name other than the shipped Low, Medium, High and Critical, or one of those has been removed.',
        'link'     => 'problem-management/settings/',
        'check'    => ['any', [
            ['rows', 'problem_priorities', "name NOT IN ('Low','Medium','High','Critical')"],
            ['sql', 'SELECT COUNT(*) < 4 FROM problem_priorities'],
        ]],
    ],
    [
        'id'       => 'problems.ai_provider',
        'module'   => 'problems',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Problem AI',
        'what'     => 'Your own AI provider and key for two helpers: Draft root cause, which reads a problem\'s linked incidents and proposes a cause and workaround, and Detect problems, which scans recent open incidents for groups that share a cause.',
        'why'      => 'Detect problems catches a brewing problem from a cluster of tickets nobody had connected, and Draft root cause gives the investigation a first hypothesis. Nothing is saved without your review.',
        'done'     => 'An API key has been saved for Problem AI.',
        'link'     => 'problem-management/settings/',
        'check'    => ['setting', 'problem_ai_api_key', 'nonempty'],
    ],
];
