<?php
/** Feature Bingo cards - Process Mapper: process maps, swimlanes, groups, linked steps, labelled branches, notes and custom step types. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'process-mapper.first_map',
        'module'   => 'process-mapper',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Map your first process',
        'what'     => 'A flowchart of how something is actually done - onboarding, a major incident, a change approval - drawn with steps, decisions and connectors.',
        'why'      => 'A process that exists only in people\'s heads is different for everyone who follows it. A map is something to agree on, train new starters from and improve.',
        'done'     => 'At least one process map exists that was not created by the demo data importer.',
        'link'     => 'process-mapper/',
        'check'    => ['rows', 'processes', 'is_demo = 0'],
    ],
    [
        'id'       => 'process-mapper.swimlanes',
        'module'   => 'process-mapper',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Swimlanes for who does what',
        'what'     => 'Horizontal lanes on a map - HR, IT, Vendor - with each step dropped into the lane of whoever does it.',
        'why'      => 'Hand-offs between teams are where processes stall. Lanes make every hand-off visible as a line crossing from one band to another.',
        'done'     => 'At least one process map has a swimlane.',
        'link'     => 'process-mapper/',
        'check'    => ['sql', 'SELECT COUNT(*) FROM process_lanes l JOIN processes p ON p.id = l.process_id WHERE p.is_demo = 0'],
    ],
    [
        'id'       => 'process-mapper.groups',
        'module'   => 'process-mapper',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Group steps into phases',
        'what'     => 'A labelled box drawn around a set of steps, such as "Resolution phase" or "Approval".',
        'why'      => 'On a big map, phases let a reader see the shape of the process first and the detail second.',
        'done'     => 'At least one process map has a group.',
        'link'     => 'process-mapper/',
        'check'    => ['sql', 'SELECT COUNT(*) FROM process_groups g JOIN processes p ON p.id = g.process_id WHERE p.is_demo = 0'],
    ],
    [
        'id'       => 'process-mapper.linked_steps',
        'module'   => 'process-mapper',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Link steps to documents',
        'what'     => 'A link on a step to the page that explains it - a knowledge article, a form, a policy on the intranet.',
        'why'      => 'The map says what happens; the link says how. Someone following the process gets from "Create AD account" to the instructions in one click.',
        'done'     => 'At least one step on a map that was not created by the demo data importer has a link.',
        'link'     => 'process-mapper/',
        'check'    => ['rows', 'process_steps', "url IS NOT NULL AND url <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'process-mapper.labelled_branches',
        'module'   => 'process-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Label decision branches',
        'what'     => 'Text on a connector - Yes and No, or P1, P2 and P3 - saying which outcome of a decision it follows.',
        'why'      => 'A diamond with two unlabelled arrows leaving it is a guess. Labelled branches make a map something people can follow without asking its author.',
        'done'     => 'At least one connector on a map that was not created by the demo data importer has a label.',
        'link'     => 'process-mapper/',
        'check'    => ['rows', 'process_connectors', "label IS NOT NULL AND label <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'process-mapper.annotations',
        'module'   => 'process-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Notes on a map',
        'what'     => 'A sticky-note annotation on the canvas for context that is not a step - an assumption, an open question, a known weak spot.',
        'why'      => 'The "we still do this by hand because..." explanation sits next to the step it is about, rather than in an email thread nobody will find.',
        'done'     => 'At least one process map has a note.',
        'link'     => 'process-mapper/',
        'check'    => ['sql', 'SELECT COUNT(*) FROM process_annotations a JOIN processes p ON p.id = a.process_id WHERE p.is_demo = 0'],
    ],
    [
        'id'       => 'process-mapper.custom_step_types',
        'module'   => 'process-mapper',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Your own step types',
        'what'     => 'Step types beyond the four built in (Process, Decision, Terminal, Document), each with its own name, shape and colour, which then appear on the toolbar.',
        'why'      => 'If your maps need a "System" or "Manual check" step that looks different at a glance, a step type keeps it consistent across every map rather than recoloured by hand each time.',
        'done'     => 'At least one step type exists that is not one of the four built in.',
        'link'     => 'process-mapper/settings/',
        'check'    => ['rows', 'process_step_types', 'is_builtin = 0'],
    ],
];
