<?php
/** Feature Bingo cards - the self-service portal: System -> Self-service portal, Portal profile, Managers, the portal's sign-in screen, and what the portal offers (catalogue, help centre, training). See includes/feature_bingo.php for the format. */
return [

    // ---------------------------------------------------------------------
    // People who can use the portal at all
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.portal_users',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'People who can sign in',
        'what'     => 'The self-service portal is where the people you support raise tickets, follow them and read your help articles. Someone can use it once they have a portal password or a linked single sign-on or directory identity.',
        'why'      => 'Without it every request arrives by email or phone, and people chase the service desk for updates they could have read for themselves.',
        'done'     => 'At least one person has a portal password or a linked sign-in identity.',
        'link'     => 'tickets/users.php',
        'check'    => ['any', [
            ['rows', 'users', "password_hash IS NOT NULL AND password_hash <> ''"],
            ['rows', 'user_sso_identities'],
        ]],
    ],
    [
        'id'       => 'self-service.self_registration',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Self-registration',
        'what'     => 'Lets people create their own portal account from the sign-in page, confirmed by an emailed link. Off by default, under System -> Security.',
        'why'      => 'Saves the service desk setting up an account for everyone who wants to use the portal - worth it when your customers are too many or change too often to add by hand.',
        'done'     => 'Self-service registration is switched on.',
        'link'     => 'system/security/',
        'check'    => ['setting', 'self_service_registration_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'self-service.portal_single_sign_on',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Portal sign-in with your directory',
        'what'     => 'People sign in to the portal with the account they already have - a single sign-on button for an OpenID Connect provider, or their LDAP / Active Directory password.',
        'why'      => 'One password fewer for everyone, no portal passwords to reset, and a leaver loses portal access the moment their directory account is disabled.',
        'done'     => 'Single sign-on is switched on with an enabled OpenID Connect provider, or an LDAP / Active Directory provider is enabled.',
        'link'     => 'system/sso/',
        'check'    => ['any', [
            ['all', [
                ['setting', 'sso_enabled', 'eq', '1'],
                ['rows', 'auth_providers', "enabled = 1 AND protocol = 'oidc'"],
            ]],
            ['rows', 'auth_providers', "enabled = 1 AND protocol = 'ldap'"],
        ]],
    ],
    [
        'id'       => 'self-service.portal_landing_page',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Portal as the front door',
        'what'     => 'Makes the self-service portal sign-in the page a signed-out visitor lands on at your FreeITSM address, instead of the analyst sign-in. Set under System -> Branding.',
        'why'      => 'Most visitors to the address are customers, not analysts - sending them straight to the portal stops them trying to sign in to the wrong screen.',
        'done'     => 'The install-wide landing page is set to the portal.',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'default_landing_page', 'eq', 'portal'],
    ],

    // ---------------------------------------------------------------------
    // System -> Self-service portal: appearance
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.portal_logo',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'look',
        'title'    => 'Portal logo',
        'what'     => 'A logo for the portal only, separate from the main logo the app, the analyst sign-in and your emails use.',
        'why'      => 'The portal is often the only part of FreeITSM a customer ever sees. A service desk that trades under another name, or whose main logo was drawn for a dark header, can make it look like theirs.',
        'done'     => 'A portal logo has been uploaded.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_logo_path', 'nonempty'],
    ],
    [
        'id'       => 'self-service.portal_logo_on_page',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Large logo on the page',
        'what'     => 'Places the portal logo once at the top of the page, larger and on the page background, instead of small in the top bar.',
        'why'      => 'A detailed or square logo is unreadable at bar size - on the page it is shown properly, and the bar shows the portal name alone.',
        'done'     => 'The portal logo position is set to the top of the page.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_logo_position', 'eq', 'page'],
    ],
    [
        'id'       => 'self-service.portal_header_colour',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'look',
        'title'    => 'Portal header colour',
        'what'     => 'The colour of the bar across the top of every portal page, instead of following the colour theme.',
        'why'      => 'Your brand colour on the bar is the quickest way to make the portal feel like your organisation\'s own rather than a generic tool.',
        'done'     => 'A header bar colour is set for the portal.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_header_colour', 'nonempty'],
    ],
    [
        'id'       => 'self-service.portal_table_colour',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal table header colour',
        'what'     => 'The colour of the heading row on the portal\'s ticket and equipment lists.',
        'why'      => 'Matches the lists to your header colour, so the portal reads as one designed page rather than a branded bar over default tables.',
        'done'     => 'A table header colour is set for the portal.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_table_header_colour', 'nonempty'],
    ],
    [
        'id'       => 'self-service.portal_background_pattern',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal background pattern',
        'what'     => 'A light pattern behind portal pages - dots, grid, diagonal, flow or mesh - drawn in CSS and tinted from the theme so it works in light and dark.',
        'why'      => 'A little texture makes a mostly empty page look finished, without the weight or legibility problems of a background photo.',
        'done'     => 'A background pattern is chosen for the portal.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_background_pattern', 'in', ['dots', 'grid', 'diagonal', 'flow', 'mesh']],
    ],

    // ---------------------------------------------------------------------
    // System -> Self-service portal: what people may do
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.self_close',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'People close their own tickets',
        'what'     => 'Adds a No longer needed button to a ticket in the portal. The ticket is closed with a note saying the requester closed it.',
        'why'      => 'Tickets for problems that fixed themselves get closed by the person who knows, instead of sitting in the queue until an analyst chases them.',
        'done'     => 'Letting people close their own ticket is switched on.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_allow_self_close', 'eq', '1'],
    ],
    [
        'id'       => 'self-service.my_equipment',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'My equipment page',
        'what'     => 'A read-only My equipment page in the portal listing the assets assigned to the person signed in, and only theirs.',
        'why'      => 'People can find their laptop\'s serial number or asset tag themselves instead of raising a ticket to ask, and spot kit that is recorded against them but is not theirs.',
        'done'     => 'Showing people the equipment assigned to them is switched on.',
        'link'     => 'system/self-service/',
        'check'    => ['setting', 'self_service_show_my_assets', 'eq', '1'],
    ],

    // ---------------------------------------------------------------------
    // System -> Portal profile
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.profile_fields',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Editable contact details',
        'what'     => 'Chooses which of their own details - job title, office, phone, mobile - people may change under My Account in the portal. Until it is saved, all of them are editable.',
        'why'      => 'People keep their own phone number and office current, so the desk rings the right number and the asset search finds their location, while you keep hold of the details you would rather maintain yourself.',
        'done'     => 'The portal profile field choice has been saved.',
        'link'     => 'system/portal-profile/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'portal_profile_fields'"],
    ],
    [
        'id'       => 'self-service.profile_address_book',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Profile changes to the address book',
        'what'     => 'Lets people imported from a CardDAV address book change their details in the portal too, with the change sent back to the address book and saved only once the address book accepts it.',
        'why'      => 'Without it, an imported person cannot correct their own phone number, because the next import would put the old one back. With it, the correction reaches the address book everyone else reads.',
        'done'     => 'Address-book write-back from the portal is on and at least one CardDAV address book has Write changes back switched on.',
        'link'     => 'system/portal-profile/',
        'check'    => ['all', [
            ['setting', 'portal_profile_address_book', 'eq', '1'],
            ['rows', 'auth_providers', "protocol = 'carddav' AND carddav_write_back = 1"],
        ]],
    ],

    // ---------------------------------------------------------------------
    // The portal sign-in screen (System -> Branding, Portal)
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.signin_heading',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'look',
        'title'    => 'Portal sign-in heading',
        'what'     => 'Your own heading on the portal sign-in page, set in the sign-in screen designer under System -> Branding, on the Portal screen.',
        'why'      => 'A heading such as "Acme IT Help" tells people at a glance they are in the right place, instead of an unfamiliar product name.',
        'done'     => 'A heading is set for the portal sign-in page.',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'branding_portal_heading', 'nonempty'],
    ],
    [
        'id'       => 'self-service.signin_taglines',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in taglines',
        'what'     => 'One or two lines under the heading on the portal sign-in page. The second replaces "Sign in to view your tickets" when set.',
        'why'      => 'The place to tell people what the portal is for, or which account to sign in with, before they get it wrong.',
        'done'     => 'At least one tagline is set for the portal sign-in page.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_portal_subheading', 'nonempty'],
            ['setting', 'branding_portal_subheading2', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'self-service.signin_background',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in background',
        'what'     => 'The background behind the portal sign-in form: your own gradient colours and direction, a solid colour, the theme, or a photo.',
        'why'      => 'The standard purple gradient is the same on every FreeITSM install. Your own colours make the first screen customers see recognisably yours.',
        'done'     => 'The portal sign-in background has been changed from the standard gradient.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_portal_bg_style', 'neq', 'gradient'],
            ['setting', 'branding_portal_bg_from', 'neq', '#667eea'],
            ['setting', 'branding_portal_bg_to', 'neq', '#764ba2'],
            ['setting', 'branding_portal_bg_direction', 'neq', 'diagonal'],
        ]],
    ],
    [
        'id'       => 'self-service.signin_background_image',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in photo',
        'what'     => 'A photo behind the portal sign-in form - your building, your people - with an adjustable dimming so the form stays readable.',
        'why'      => 'A familiar picture reassures people they are signing in to the real thing, which matters when you are also teaching them to distrust look-alike pages.',
        'done'     => 'A background image is uploaded for the portal sign-in page.',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'branding_portal_bg_image_path', 'nonempty'],
    ],
    [
        'id'       => 'self-service.signin_layout',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in layout',
        'what'     => 'Where the sign-in form sits on the portal sign-in page - left, centre or right - and its panel style: solid, glass or flat.',
        'why'      => 'Moving the form aside leaves room for a background photo to be seen, and a glass panel lets it show through.',
        'done'     => 'The portal sign-in form position or panel style has been changed from centre and solid.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_portal_form_position', 'neq', 'centre'],
            ['setting', 'branding_portal_card_style', 'neq', 'solid'],
        ]],
    ],
    [
        'id'       => 'self-service.signin_logo',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in logo size',
        'what'     => 'How large the logo is on the portal sign-in page, the most height it may take, and where it sits - above the form, top left, top centre, or hidden.',
        'why'      => 'A square or tall logo at the default width can swamp the sign-in panel. Limiting its size or moving it keeps the form in view.',
        'done'     => 'The portal sign-in logo size, height limit or position has been changed from the defaults.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_portal_logo_size', 'neq', '250'],
            ['setting', 'branding_portal_logo_height', 'neq', '0'],
            ['setting', 'branding_portal_logo_position', 'neq', 'above'],
        ]],
    ],
    [
        'id'       => 'self-service.signin_accent',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in accent colour',
        'what'     => 'The colour of the sign-in button and highlights on the portal sign-in page.',
        'why'      => 'A button in your brand colour completes a branded sign-in page - the standard blue can clash with your own background.',
        'done'     => 'The portal sign-in accent colour has been changed from the standard blue.',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'branding_portal_accent', 'neq', '#2b88d8'],
    ],
    [
        'id'       => 'self-service.signin_banner',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Portal sign-in banner',
        'what'     => 'A strip of text across the top or bottom of the portal sign-in page, in colours you choose.',
        'why'      => 'Somewhere to put a notice everyone signing in will see - planned downtime, a new phone number, or "we will never ask for your password".',
        'done'     => 'The portal sign-in banner is switched on with some text in it.',
        'link'     => 'system/branding/',
        'check'    => ['all', [
            ['setting', 'branding_portal_banner_position', 'in', ['top', 'bottom']],
            ['setting', 'branding_portal_banner_text', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'self-service.signin_footer',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Portal sign-in footer',
        'what'     => 'A line of text along the bottom of the portal sign-in page.',
        'why'      => 'The usual home for a copyright line, an acceptable-use reminder or the service desk\'s opening hours.',
        'done'     => 'Footer text is set for the portal sign-in page.',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'branding_portal_footer_text', 'nonempty'],
    ],

    // ---------------------------------------------------------------------
    // What the portal offers
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.request_catalogue',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Request catalogue',
        'what'     => 'Forms offered in the portal\'s request catalogue - a new starter, a laptop, access to a system - each asking exactly the questions the service desk needs. A form is offered by ticking Show in the portal on it.',
        'why'      => 'Requests arrive complete the first time, instead of as a one-line email followed by three rounds of questions.',
        'done'     => 'At least one active form (its current version) is shown in the portal.',
        'link'     => 'forms/',
        'check'    => ['sql', 'SELECT COUNT(*) FROM forms f WHERE f.is_portal_visible = 1 AND f.is_active = 1 AND NOT EXISTS (SELECT 1 FROM forms ch WHERE ch.parent_form_id = f.id)'],
    ],
    [
        'id'       => 'self-service.catalogue_approval',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Approval on catalogue requests',
        'what'     => 'A catalogue form that needs a named approver to say yes before the request goes any further.',
        'why'      => 'Requests that cost money or grant access are signed off before anyone acts on them, with the decision recorded against the request.',
        'done'     => 'At least one portal catalogue form requires approval and has an approver.',
        'link'     => 'forms/',
        'check'    => ['rows', 'forms', 'is_portal_visible = 1 AND requires_approval = 1 AND approver_id IS NOT NULL'],
    ],
    [
        'id'       => 'self-service.catalogue_audiences',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Catalogue forms for chosen groups',
        'what'     => 'Restricts a catalogue form to one or more people groups. Everyone else does not see it in their catalogue at all.',
        'why'      => 'A manager-only request, such as a new starter or a leaver, stays off everyone else\'s menu, and the catalogue stays short for the people it is not for.',
        'done'     => 'At least one form is restricted to a group of people.',
        'link'     => 'forms/',
        'check'    => ['rows', 'form_audiences'],
    ],
    [
        'id'       => 'self-service.portal_people_groups',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'People groups for the portal',
        'what'     => 'Named groups of portal users, kept under Tickets -> Users, Groups. The same groups decide who sees a catalogue form, who is assigned a training course and who a manager can see.',
        'why'      => 'Set a group up once - "Finance", "Site managers" - and use it everywhere, instead of picking the same people out one at a time in three places.',
        'done'     => 'At least one people group has a portal user in it.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'knowledge_user_group_members', "member_type = 'user'"],
    ],
    [
        'id'       => 'self-service.help_centre',
        'module'   => 'self-service',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Help centre articles',
        'what'     => 'Knowledge articles published to the Customer (or Public) audience, which appear in the portal\'s Help centre and are suggested as someone types the subject of a new ticket.',
        'why'      => 'Every "how do I reset my password" that someone answers from an article is a ticket nobody has to handle.',
        'done'     => 'At least one published, unarchived knowledge article is visible to customers.',
        'link'     => 'knowledge/',
        'check'    => ['rows', 'knowledge_articles', "audience IN ('customer', 'public') AND is_published = 1 AND (is_archived = 0 OR is_archived IS NULL)"],
    ],
    [
        'id'       => 'self-service.portal_categories',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Categories on portal tickets',
        'what'     => 'A short list of ticket categories people can choose from when raising a ticket in the portal. Needs the category field switched on and categories marked visible in the portal.',
        'why'      => 'Tickets arrive already sorted, so they reach the right people sooner and your reports can say what people actually ask for.',
        'done'     => 'The ticket category field is on (for the install or a company) and at least one active, portal-visible category is not tied to a ticket type.',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['all', [
            ['any', [
                ['setting', 'ticket_category_enabled', 'eq', '1'],
                ['rows', 'tenant_settings', "setting_key = 'ticket_category_enabled' AND setting_value = '1'"],
            ]],
            ['rows', 'ticket_categories', 'is_portal_visible = 1 AND is_active = 1 AND ticket_type_id IS NULL'],
        ]],
    ],
    [
        'id'       => 'self-service.portal_training',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Training in the portal',
        'what'     => 'Courses from the LMS assigned to portal users - everyone, or a people group - which they take under Training in the portal.',
        'why'      => 'Security awareness or new-system training reaches the whole organisation, with completions recorded, without every learner needing an analyst account.',
        'done'     => 'At least one course is assigned to all portal users or to a people group.',
        'link'     => 'lms/',
        'check'    => ['rows', 'lms_course_assignments', "target_type IN ('user_group', 'all_users')"],
    ],

    // ---------------------------------------------------------------------
    // System -> Managers
    // ---------------------------------------------------------------------
    [
        'id'       => 'self-service.managers_enabled',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Managers see team tickets',
        'what'     => 'Gives managers a Team tickets tab in the portal showing the tickets raised by the people they manage, within their own company. Off until switched on under System -> Managers.',
        'why'      => 'A head of department can see what their team is waiting on without asking the service desk for a report or being copied into every email.',
        'done'     => 'Managers in the portal is switched on.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'self-service.managers_directory_field',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Line managers on people',
        'what'     => 'Each person\'s Manager field, filled in by hand or from your directory. When System -> Managers uses it, whoever someone reports to can see their tickets.',
        'why'      => 'The reporting lines you already keep in Active Directory become portal access with nothing else to set up, and stay right as people move.',
        'done'     => 'At least one person has a manager recorded.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'users', 'manager_id IS NOT NULL'],
    ],
    [
        'id'       => 'self-service.managers_whole_chain',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Managers see the whole chain',
        'what'     => 'Lets a manager see the tickets of everyone below them in the reporting line, not only their direct reports.',
        'why'      => 'A director sees their whole area in one list without a management line being set up for every team underneath them.',
        'done'     => 'How far down managers see is set to everyone below them.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_directory_depth', 'eq', 'all'],
    ],
    [
        'id'       => 'self-service.management_lines',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Management lines',
        'what'     => 'Manager access set up in FreeITSM for a portal user - everyone, named people, a people group, a department, or their reports - with the Manager access button on Tickets -> Users.',
        'why'      => 'Covers the people your directory does not: an office manager who looks after a site, or a team lead with no reports on paper.',
        'done'     => 'At least one management line exists.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'manager_grants', 'is_exclusion = 0'],
    ],
    [
        'id'       => 'self-service.management_exclusions',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Management exclusions',
        'what'     => 'Takes a person, a group or a department out of what a manager can see, whatever granted the access - including the directory.',
        'why'      => 'For the case the feature has to get right: someone raising a grievance about their own manager must not have that manager reading their tickets.',
        'done'     => 'At least one management exclusion exists.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'manager_grants', 'is_exclusion = 1'],
    ],
    [
        'id'       => 'self-service.managers_can_reply',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Managers reply to team tickets',
        'what'     => 'Lets a manager add replies to their team\'s tickets from the portal, not only read them.',
        'why'      => 'A manager can answer the question holding a ticket up - "yes, they need that access" - without the service desk chasing them separately.',
        'done'     => 'Managers may reply to their team\'s tickets.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_can_reply', 'eq', '1'],
    ],
    [
        'id'       => 'self-service.managers_can_close',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Managers close team tickets',
        'what'     => 'Lets a manager close their team\'s tickets from the portal.',
        'why'      => 'Requests that are no longer wanted - the new starter who never started - can be closed by the person who knows, instead of lingering in the queue.',
        'done'     => 'Managers may close their team\'s tickets.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_can_close', 'eq', '1'],
    ],
    [
        'id'       => 'self-service.managers_confidential',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Confidential tickets and managers',
        'what'     => 'What a manager sees of a ticket marked confidential: nothing at all (the default), a stub saying one exists, or everything.',
        'why'      => 'A diagnosis sent to HR or a complaint about the manager themselves must never be shown to them. Deciding this before switching managers on is the part that matters.',
        'done'     => 'The System -> Managers settings, including this choice, have been saved.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_confidential', 'nonempty'],
    ],
    [
        'id'       => 'self-service.confidential_by_default',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Confidential departments and mailboxes',
        'what'     => 'A department or mailbox - HR, say - whose tickets are marked confidential automatically, the moment they arrive, before anyone has read them.',
        'why'      => 'A grievance emailed to HR is kept from the requester\'s manager from the first second, not from whenever an analyst gets round to marking it.',
        'done'     => 'At least one department or mailbox makes its tickets confidential.',
        'link'     => 'tickets/settings/#departments',
        'check'    => ['any', [
            ['rows', 'departments', "default_sensitivity = 'confidential'"],
            ['rows', 'target_mailboxes', "default_sensitivity = 'confidential'"],
        ]],
    ],
    [
        'id'       => 'self-service.managers_notify',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Tell managers about new tickets',
        'what'     => 'Notifies a manager when someone on their team raises a ticket, by email or in the portal\'s notification bell. Never for a ticket they may not open.',
        'why'      => 'Managers hear about their team\'s problems as they happen instead of only when they remember to look at Team tickets.',
        'done'     => 'Managers are notified of new team tickets by email or the portal bell.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_notify', 'in', ['email', 'bell']],
    ],
    [
        'id'       => 'self-service.managers_edit_by_analysts',
        'module'   => 'self-service',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Analysts set up management lines',
        'what'     => 'Lets analysts who can edit people set up management lines, not only administrators.',
        'why'      => 'On a desk where the analysts maintain the people records, they can keep manager access in step with them instead of queueing every change for an administrator.',
        'done'     => 'Management lines may be set up by analysts who can edit people.',
        'link'     => 'system/managers/',
        'check'    => ['setting', 'managers_edit_by', 'eq', 'people_editors'],
    ],
];
