<?php
/** Feature Bingo cards - Software: inventory agent keys, discovered and manual applications, licences, renewals, dashboard. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'software.api_key',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'integrations',
        'title'    => 'Inventory agent API key',
        'what'     => 'A key generated under Software settings that the inventory script presents when it sends in a machine\'s hardware and installed software.',
        'why'      => 'The script cannot report anything without one. A separate key per site or deployment lets you revoke one without stopping the rest.',
        'done'     => 'At least one active inventory API key exists.',
        'link'     => 'software/settings/?tab=api-keys',
        'check'    => ['rows', 'apikeys', 'active = 1'],
    ],
    [
        'id'       => 'software.inventory',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Installed software inventory',
        'what'     => 'The list of every application found installed across your machines, with versions and which machines have it, reported by the inventory script or Intune.',
        'why'      => 'When a vulnerability is announced in a product, you can say within a minute which machines run the affected version.',
        'done'     => 'At least one application has been discovered by an agent or sync (demo data not counted).',
        'link'     => 'software/',
        'check'    => ['rows', 'software_inventory_apps', "source = 'agent' AND is_demo = 0"],
    ],
    [
        'id'       => 'software.manual_apps',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Cloud platforms added by hand',
        'what'     => 'Applications entered yourself - Xero, Canva, Figma and other browser-based services - with a publisher, admin web address and notes.',
        'why'      => 'Nothing installs a cloud platform, so nothing discovers it. Adding it is the only way to record what the subscription costs, how many seats it has and when it renews.',
        'done'     => 'At least one application has been added by hand (demo data not counted).',
        'link'     => 'software/',
        'check'    => ['rows', 'software_inventory_apps', "source = 'manual' AND is_demo = 0"],
    ],
    [
        'id'       => 'software.licences',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Software licences',
        'what'     => 'Your licence entitlements recorded against applications - type, quantity, key, cost and status - compared live against the number of installs.',
        'why'      => 'Shows at a glance where you are over-licensed and paying for nothing, or under-licensed and exposed in an audit.',
        'done'     => 'At least one software licence is recorded (demo data not counted).',
        'link'     => 'software/licences/',
        'check'    => ['rows', 'software_licences', 'is_demo = 0'],
    ],
    [
        'id'       => 'software.licence_quantities',
        'module'   => 'software',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Seat counts on licences',
        'what'     => 'The number of seats or devices a licence covers.',
        'why'      => 'Compliance - Compliant, Approaching limit, Over-licensed - can only be worked out when FreeITSM knows how many you bought.',
        'done'     => 'At least one licence has a quantity (demo data not counted).',
        'link'     => 'software/licences/',
        'check'    => ['rows', 'software_licences', 'quantity IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'software.licence_costs',
        'module'   => 'software',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Licence costs',
        'what'     => 'What each licence costs, in its currency, with its purchase date.',
        'why'      => 'Puts a number on software spend, so renewals can be challenged and unused seats show up as money rather than just a count.',
        'done'     => 'At least one licence has a cost (demo data not counted).',
        'link'     => 'software/licences/',
        'check'    => ['rows', 'software_licences', 'cost IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'software.renewal_dates',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Licence renewal dates',
        'what'     => 'The date each licence renews, recorded on the licence.',
        'why'      => 'A subscription that renews automatically for another year because nobody saw the date coming is one of the most common avoidable costs in IT.',
        'done'     => 'At least one licence has a renewal date (demo data not counted).',
        'link'     => 'software/licences/',
        'check'    => ['rows', 'software_licences', 'renewal_date IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'software.notice_periods',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Licence notice periods',
        'what'     => 'How many days before renewal you must give notice to cancel, from which FreeITSM works out the last day you can walk away.',
        'why'      => 'The notice deadline, not the renewal date, is the one that costs you if missed - it gets its own warning so you act while you still can.',
        'done'     => 'At least one licence has a notice period (demo data not counted).',
        'link'     => 'software/licences/',
        'check'    => ['rows', 'software_licences', 'notice_period_days IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'software.renewal_surface',
        'module'   => 'software',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Where licence renewals show',
        'what'     => 'Choosing whether renewals and notice deadlines appear as a Watchtower card, as all-day Calendar entries, both, or nowhere.',
        'why'      => 'A renewal date is only useful if somebody sees it in time. Putting it on the calendar puts it where people already look.',
        'done'     => 'The renewals setting has been saved (the default, Watchtower only, applies until then).',
        'link'     => 'software/settings/?tab=renewals',
        'check'    => ['setting', 'software_renewal_surface', 'nonempty'],
    ],
    [
        'id'       => 'software.portal_urls',
        'module'   => 'software',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Licence portal addresses',
        'what'     => 'The web address of the vendor portal where each licence is managed, and a vendor contact.',
        'why'      => 'When a seat needs adding or a renewal cancelling, nobody has to hunt for where the account lives or who to ring.',
        'done'     => 'At least one licence has a portal address (demo data not counted).',
        'link'     => 'software/licences/',
        'check'    => ['rows', 'software_licences', "portal_url IS NOT NULL AND portal_url <> '' AND is_demo = 0"],
    ],
    [
        'id'       => 'software.dashboard_widget',
        'module'   => 'software',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Your own software dashboard chart',
        'what'     => 'A chart you have added to the software dashboard library, such as the version spread of one application.',
        'why'      => 'A chart of the versions of your browser or VPN client shows how far a rollout has got without running a report.',
        'done'     => 'At least one software dashboard widget exists beyond the two supplied.',
        'link'     => 'software/dashboard/',
        'check'    => ['rows', 'software_dashboard_widgets', 'id > 2'],
    ],
];
