<?php
/** Feature Bingo cards - System core: analysts, teams, roles, module access, security, sign-in (SSO, LDAP, CardDAV), companies, encryption, database verification, date formats, colours, branding and search. See includes/feature_bingo.php for the format. */
return [

    // ───────────────────────── Analysts ─────────────────────────
    [
        'id'       => 'system.analyst_accounts',
        'module'   => 'system',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Analyst accounts for your team',
        'what'     => 'An account for each person who works tickets, assets and knowledge in FreeITSM, beyond the built-in admin account.',
        'why'      => 'Shared logins make every ticket, note and change untraceable - you cannot tell who did what, or take one person\'s access away without locking everyone out.',
        'done'     => 'At least two active analyst accounts exist (the install ships with one).',
        'link'     => 'system/analysts/',
        'check'    => ['rows', 'analysts', 'is_active = 1 AND is_demo = 0', 2],
    ],
    [
        'id'       => 'system.default_admin_secured',
        'module'   => 'system',
        'tier'     => 'essential',
        'category' => 'security',
        'title'    => 'Default admin password changed',
        'what'     => 'The seeded admin account starts with the published password admin / freeitsm and is flagged to change it at first sign-in.',
        'why'      => 'That password is in the public documentation, so an install still carrying it can be opened by anyone who can reach the login page.',
        'done'     => 'No active account called "admin" is still waiting for its first password change.',
        'link'     => 'system/analysts/',
        'check'    => ['sql', "SELECT CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END FROM analysts WHERE username = 'admin' AND must_change_password = 1 AND is_active = 1"],
    ],
    [
        'id'       => 'system.named_admin',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Named administrator accounts',
        'what'     => 'An administrator account that belongs to a real person, rather than relying on the generic "admin" login.',
        'why'      => 'Changes to SSO, security rules and companies are then attributable to someone, and the generic account can be kept locked away as a break-glass login.',
        'done'     => 'At least one active administrator has a username other than "admin".',
        'link'     => 'system/analysts/',
        'check'    => ['rows', 'analysts', "is_admin = 1 AND is_active = 1 AND username <> 'admin' AND is_demo = 0"],
    ],
    [
        'id'       => 'system.second_admin',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'A second administrator',
        'what'     => 'More than one active analyst holding the Administrator flag, which is the only way into the System module.',
        'why'      => 'If your only administrator is on holiday, leaves or loses their MFA device, nobody can reset a password, fix a mailbox or change a setting.',
        'done'     => 'At least two active analysts are administrators.',
        'link'     => 'system/analysts/',
        'check'    => ['rows', 'analysts', 'is_admin = 1 AND is_active = 1 AND is_demo = 0', 2],
    ],
    [
        'id'       => 'system.non_admin_analysts',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Analysts without admin rights',
        'what'     => 'Everyday analysts who work tickets but are not administrators, so they cannot open System at all.',
        'why'      => 'An administrator can change SSO, mint API keys and reset anyone\'s password - most of your team never needs that, and fewer admins means a smaller blast radius if an account is compromised.',
        'done'     => 'At least one active analyst is not an administrator.',
        'link'     => 'system/analysts/',
        'check'    => ['rows', 'analysts', 'is_admin = 0 AND is_active = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'system.analyst_mfa',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Two-factor sign-in for analysts',
        'what'     => 'An authenticator-app code (TOTP) asked for after the password, which each analyst turns on for their own account.',
        'why'      => 'A leaked or guessed password is no longer enough to get into your service desk, which holds your users\' details and often credentials for other systems.',
        'done'     => 'At least one active analyst has two-factor sign-in switched on.',
        'link'     => 'system/preferences/',
        'check'    => ['rows', 'analysts', 'totp_enabled = 1 AND is_active = 1'],
    ],
    [
        'id'       => 'system.analyst_profiles',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Analyst contact details',
        'what'     => 'Job title, department and phone numbers on analyst accounts, alongside the required name and email.',
        'why'      => 'Colleagues and requesters can see who they are dealing with and how to reach them, without a separate staff directory.',
        'done'     => 'At least one active analyst has a job title or phone number filled in.',
        'link'     => 'system/analysts/',
        'check'    => ['rows', 'analysts', "is_active = 1 AND ((job_title IS NOT NULL AND job_title <> '') OR (phone IS NOT NULL AND phone <> '') OR (mobile IS NOT NULL AND mobile <> ''))"],
    ],

    // ───────────────────────── Teams ─────────────────────────
    [
        'id'       => 'system.teams',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Teams',
        'what'     => 'Groups of analysts - service desk, infrastructure, applications - that you grant departments, companies, modules and roles to once instead of person by person.',
        'why'      => 'Onboarding becomes "add them to the team", and access stays consistent instead of drifting one analyst at a time.',
        'done'     => 'At least one active team exists.',
        'link'     => 'system/teams/',
        'check'    => ['rows', 'teams', 'is_active = 1 AND is_demo = 0'],
    ],
    [
        'id'       => 'system.team_members',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Analysts placed in teams',
        'what'     => 'Team membership for your analysts, edited from either System > Teams or Assign teams on System > Analysts.',
        'why'      => 'Membership is what makes a team do anything - its departments, company access, modules and sign-in method only reach the people in it.',
        'done'     => 'At least one analyst belongs to a team.',
        'link'     => 'system/teams/',
        'check'    => ['rows', 'analyst_teams', 'is_demo = 0'],
    ],
    [
        'id'       => 'system.team_sign_in_method',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Sign-in method per team',
        'what'     => 'A default sign-in method on a team - local password or a specific provider - that members set to "Follow team" pick up automatically.',
        'why'      => 'A new starter signs in the right way just by joining their team, instead of someone remembering to set it on every account.',
        'done'     => 'At least one team has a sign-in method set.',
        'link'     => 'system/teams/',
        'check'    => ['rows', 'teams', "auth_method IS NOT NULL AND auth_method <> ''"],
    ],

    // ───────────────────────── Module access ─────────────────────────
    [
        'id'       => 'system.module_access_restricted',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Module access limits',
        'what'     => 'Turning off "All access" for an analyst or granting a team a specific list of modules, so people only see the parts of FreeITSM they use.',
        'why'      => 'A contractor who only handles tickets does not need Contracts or the CMDB, and a shorter app launcher is easier for everyone.',
        'done'     => 'At least one active analyst is restricted to chosen modules, or a team grants specific modules.',
        'link'     => 'system/modules/',
        'check'    => ['any', [
            ['rows', 'analysts', 'can_access_all_modules = 0 AND is_active = 1 AND is_demo = 0'],
            ['rows', 'team_modules', 'is_demo = 0'],
        ]],
    ],
    [
        'id'       => 'system.module_permission_mode',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Module privilege mode',
        'what'     => 'Whether module access from an analyst and their teams is combined as a union ("most privilege") or an intersection ("least privilege").',
        'why'      => 'Least privilege lets a narrow team take modules away from its members, which suits tightly controlled installs; deciding it up front avoids modules vanishing unexpectedly after a team change.',
        'done'     => 'The privilege mode has been saved on System > Modules (either choice counts).',
        'link'     => 'system/modules/',
        'check'    => ['setting', 'module_permission_mode', 'nonempty'],
    ],

    // ───────────────────────── Roles (RBAC) ─────────────────────────
    [
        'id'       => 'system.rbac_roles',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Delegated admin roles',
        'what'     => 'A named bundle of settings capabilities - such as "Manage the LMS" - that lets a non-administrator configure one module.',
        'why'      => 'A training lead can build courses without also being able to change your SSO, security rules or companies.',
        'done'     => 'At least one active role grants at least one capability.',
        'link'     => 'system/roles/',
        'check'    => ['sql', 'SELECT COUNT(*) FROM rbac_roles r WHERE r.is_active = 1 AND r.is_demo = 0 AND EXISTS (SELECT 1 FROM rbac_role_capabilities c WHERE c.role_id = r.id)'],
    ],
    [
        'id'       => 'system.rbac_role_assigned',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Roles assigned to people',
        'what'     => 'A role given to specific analysts, or to a team so every member inherits it.',
        'why'      => 'A role does nothing until someone holds it - assigning it to a team means new members get the right admin reach automatically.',
        'done'     => 'At least one role is assigned to an analyst or a team.',
        'link'     => 'system/roles/',
        'check'    => ['any', [
            ['rows', 'rbac_analyst_roles'],
            ['rows', 'rbac_team_roles', 'is_demo = 0'],
        ]],
    ],

    // ───────────────────────── Security ─────────────────────────
    [
        'id'       => 'system.account_lockout',
        'module'   => 'system',
        'tier'     => 'essential',
        'category' => 'security',
        'title'    => 'Account lockout',
        'what'     => 'Locks a local account for a cooling-off period after too many failed sign-ins in a row.',
        'why'      => 'It stops password-guessing against one person\'s account; with it off, an attacker can try passwords for ever.',
        'done'     => 'Maximum failed attempts is above 0 (Database Verification switches it on at 5 by default).',
        'link'     => 'system/security/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'max_failed_logins' AND CAST(setting_value AS UNSIGNED) > 0"],
    ],
    [
        'id'       => 'system.ip_ban',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'IP ban for password spraying',
        'what'     => 'Blocks an address that racks up failed sign-ins across several different accounts.',
        'why'      => 'Account lockout only protects one account at a time; this catches the attacker trying one common password against every username you have.',
        'done'     => 'The first-ban threshold is above 0 (Database Verification switches it on at 5 by default).',
        'link'     => 'system/security/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'max_ip_attempts' AND CAST(setting_value AS UNSIGNED) > 0"],
    ],
    [
        'id'       => 'system.trusted_devices',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Trusted devices',
        'what'     => 'Lets a device that has signed in successfully skip the extra prompt for a set number of days.',
        'why'      => 'Analysts with two-factor sign-in are not asked for a code on their own work PC every morning, which keeps them willing to leave it switched on.',
        'done'     => 'Trust duration is set to more than 0 days.',
        'link'     => 'system/security/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'trusted_device_days' AND CAST(setting_value AS UNSIGNED) > 0"],
    ],
    [
        'id'       => 'system.password_expiry',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Password expiry',
        'what'     => 'Forces a local password to be changed once it reaches a set age.',
        'why'      => 'Some audits and policies still require periodic rotation - modern guidance generally prefers strong passwords plus lockout, so only switch it on if you need it.',
        'done'     => 'Password expiry is set to more than 0 days.',
        'link'     => 'system/security/',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'password_expiry_days' AND CAST(setting_value AS UNSIGNED) > 0"],
    ],
    [
        'id'       => 'system.attachment_allowed_types',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Narrowed attachment types',
        'what'     => 'A list of file extensions your install accepts, narrowing the built-in catalogue of types FreeITSM considers safe.',
        'why'      => 'If your policy only allows, say, documents and images, anything else arriving by email is kept inert or refused instead of stored as a normal attachment.',
        'done'     => 'An allowed-extensions list has been entered (empty means the full built-in catalogue).',
        'link'     => 'system/security/',
        'check'    => ['setting', 'attachment_allowed_extensions', 'nonempty'],
    ],
    [
        'id'       => 'system.attachment_drop_rejected',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Drop rejected attachments',
        'what'     => 'Changes what happens to an inbound file of a type you do not accept: instead of keeping an inert download-only copy, it is not stored at all.',
        'why'      => 'For installs that must not hold unknown files on disk; the ticket still records that a file was refused, so nothing vanishes silently.',
        'done'     => 'Rejected attachments are set to be dropped rather than stored.',
        'link'     => 'system/security/',
        'check'    => ['setting', 'attachment_rejected_behaviour', 'eq', 'drop'],
    ],

    // ───────────────────────── Single sign-on (OIDC) ─────────────────────────
    [
        'id'       => 'system.sso_provider',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Single sign-on provider',
        'what'     => 'An OpenID Connect identity provider - Entra, Google, Okta, Keycloak and others - that people sign in through instead of a FreeITSM password.',
        'why'      => 'People use the account they already have, your provider enforces its own MFA and password rules, and disabling a leaver there shuts them out here too.',
        'done'     => 'At least one enabled OIDC provider is configured.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'oidc' AND enabled = 1"],
    ],
    [
        'id'       => 'system.sso_enabled',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Single sign-on switched on',
        'what'     => 'The master switch that shows your providers\' buttons on the login pages. Turning it off falls back to local logins everywhere.',
        'why'      => 'Configured providers are not offered to anyone until this is on - and it doubles as the break-glass switch if a provider fails.',
        'done'     => 'Enable single sign-on is on.',
        'link'     => 'system/sso/',
        'check'    => ['setting', 'sso_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'system.sso_analysts_linked',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Analysts signing in with SSO',
        'what'     => 'Analyst accounts linked to an identity-provider account, which happens automatically by email on their first SSO sign-in.',
        'why'      => 'It shows single sign-on is actually in use by your team, not just configured.',
        'done'     => 'At least one analyst has signed in through an identity provider.',
        'link'     => 'system/analysts/',
        'check'    => ['rows', 'analyst_sso_identities'],
    ],
    [
        'id'       => 'system.sso_only',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'SSO-only login page',
        'what'     => 'Hides the username and password form so the login page offers only your identity provider. The ?local=1 escape hatch still brings it back.',
        'why'      => 'People stop keeping a second password for FreeITSM, and everyone goes through the provider\'s MFA and conditional access.',
        'done'     => 'Allow local login is switched off.',
        'link'     => 'system/sso/',
        'check'    => ['setting', 'local_login_enabled', 'eq', '0'],
    ],
    [
        'id'       => 'system.sso_auto_create',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Portal accounts created on first sign-in',
        'what'     => 'Auto-create portal requesters on a provider: a customer who signs in to the self-service portal for the first time gets an account automatically.',
        'why'      => 'No pre-provisioning - a client\'s new user can sign in and raise a ticket on day one without anyone creating them first.',
        'done'     => 'At least one enabled sign-in provider has Auto-create portal requesters switched on.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol IN ('oidc', 'ldap') AND enabled = 1 AND auto_create_users = 1"],
    ],
    [
        // Split out of the card above in discussion #155.
        'id'       => 'system.sso_auto_create_analysts',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Analyst accounts created on first sign-in',
        'what'     => 'Auto-create IT analysts on a provider: a member of staff who signs in on the analyst login for the first time gets an analyst account, with the default modules you chose.',
        'why'      => 'A new starter in IT can sign in on day one, and the same provider can still create customers on the portal without making them analysts.',
        'done'     => 'At least one enabled sign-in provider has Auto-create IT analysts switched on.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol IN ('oidc', 'ldap') AND enabled = 1 AND auto_create_analysts = 1"],
    ],
    [
        'id'       => 'system.sso_analyst_fallback',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Customers on the analyst login are sent to the portal',
        'what'     => 'When someone with no analyst account signs in on the analyst login, they are offered the self-service portal (or taken straight there) instead of seeing an error.',
        'why'      => 'With one company sign-in for everyone, people land on the wrong login all the time. This turns a dead end into the page they actually wanted.',
        'done'     => 'At least one enabled OIDC provider sends non-analysts to the portal (Warn and confirm, or Automatically switch).',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'oidc' AND enabled = 1 AND auto_create_analysts = 0 AND analyst_fallback_mode IN ('confirm', 'redirect')"],
    ],
    [
        'id'       => 'system.sso_profile_sync',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Profile details kept in step with your identity provider',
        'what'     => 'Job title, department, office and phone numbers are filled in from the identity provider at sign-in - once when the account is created, or at every sign-in.',
        'why'      => 'Signatures, ticket views and the people directory show the same details as everywhere else in the company, without anyone typing them twice.',
        'done'     => 'At least one enabled OIDC provider has Profile attribute sync set to On account creation or Always.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'oidc' AND enabled = 1 AND profile_sync_mode IN ('initial', 'always')"],
    ],
    [
        'id'       => 'system.sso_portal_email_domains',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Portal sends your staff straight to single sign-on',
        'what'     => 'On the self-service portal, typing an email address on one of your domains goes straight to your identity provider - even the first time - while everyone else gets the password box.',
        'why'      => 'One email box works for staff and outside customers alike, so nobody has to know which button is theirs.',
        'done'     => 'At least one enabled OIDC provider has Email domains set.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'oidc' AND enabled = 1 AND portal_email_domains IS NOT NULL AND portal_email_domains <> ''"],
    ],
    [
        'id'       => 'system.sso_default_modules',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Default modules for new accounts',
        'what'     => 'A list of modules that analysts created automatically by a provider are given, instead of full access to everything.',
        'why'      => 'Auto-created accounts start with the least they need, rather than every module until someone remembers to trim them.',
        'done'     => 'At least one sign-in provider has default modules set.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "default_modules IS NOT NULL AND default_modules <> ''"],
    ],
    [
        'id'       => 'system.sso_verified_email',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Require verified email',
        'what'     => 'Refuses a sign-in unless the provider says the person\'s email address has been verified.',
        'why'      => 'Accounts are matched by email, so on a provider that lets users self-register addresses this stops someone claiming another person\'s identity.',
        'done'     => 'At least one OIDC provider requires a verified-email claim.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'oidc' AND require_verified_email = 1"],
    ],
    [
        'id'       => 'system.sso_per_company',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Per-company identity providers',
        'what'     => 'An identity provider owned by one client company, offered only to that company\'s portal users and routed by their email domain.',
        'why'      => 'An MSP\'s clients each sign in with their own Entra or Okta, and no client ever sees another client\'s login button.',
        'done'     => 'At least one sign-in provider belongs to a specific company.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "tenant_id IS NOT NULL AND protocol IN ('oidc', 'ldap')"],
    ],

    // ───────────────────────── LDAP / Active Directory ─────────────────────────
    [
        'id'       => 'system.ldap_directory',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'LDAP / Active Directory sign-in',
        'what'     => 'Checks passwords against your Active Directory, OpenLDAP or FreeIPA directory, so people use the username and password they already have.',
        'why'      => 'No separate FreeITSM passwords to manage, and disabling someone in the directory stops them signing in here immediately.',
        'done'     => 'At least one enabled LDAP directory is configured.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'ldap' AND enabled = 1"],
    ],
    [
        'id'       => 'system.ldap_encrypted',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Encrypted directory connection',
        'what'     => 'LDAPS or STARTTLS on the connection to your directory.',
        'why'      => 'Without it, every sign-in sends the person\'s password across your network in clear text - and many domain controllers refuse unencrypted password binds anyway.',
        'done'     => 'At least one LDAP directory uses LDAPS or STARTTLS.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'ldap' AND ldap_encryption IN ('ldaps', 'starttls')"],
    ],
    [
        'id'       => 'system.ldap_group_gate',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Directory access by group',
        'what'     => 'Named directory groups that decide who becomes an analyst and who becomes a self-service user; everyone else is refused.',
        'why'      => 'Without a group, everyone your directory recognises can become an analyst - point that at a 500-person company and you get 500 analysts.',
        'done'     => 'At least one LDAP directory names an analyst group or a self-service user group.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'ldap' AND ((ldap_analyst_group IS NOT NULL AND ldap_analyst_group <> '') OR (ldap_user_group IS NOT NULL AND ldap_user_group <> ''))"],
    ],
    [
        'id'       => 'system.directory_import',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Import people from the directory',
        'what'     => 'Brings everyone in chosen parts of your directory into FreeITSM ahead of time, with job title, department, office and phones, and marks leavers.',
        'why'      => 'People exist before they ever sign in, so you can assign them equipment and raise tickets for them, and their details stay current.',
        'done'     => 'At least one LDAP directory has importing switched on.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'ldap' AND sync_enabled = 1"],
    ],
    [
        'id'       => 'system.directory_import_ous',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Import scoped to chosen OUs',
        'what'     => 'Ticked organisational units to import from, with carve-outs, rather than the whole directory.',
        'why'      => 'Service accounts, test users and disabled-user OUs stay out of your people list.',
        'done'     => 'At least one LDAP directory has OUs ticked to include in its import.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'ldap' AND sync_ou_includes IS NOT NULL AND sync_ou_includes <> ''"],
    ],
    [
        'id'       => 'system.directory_import_ran',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'A directory or address-book import',
        'what'     => 'A completed live import from a directory or CardDAV address book, run from the Import button or on a schedule.',
        'why'      => 'Importing is only switched on until it runs - this shows people have actually been brought in.',
        'done'     => 'At least one live import has finished successfully.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'directory_sync_runs', "mode = 'live' AND status = 'ok'"],
    ],
    [
        'id'       => 'system.directory_import_scheduled',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Scheduled directory import',
        'what'     => 'A scheduled task running php scripts/directory_sync.php --all, which imports every enabled directory and address book.',
        'why'      => 'Nothing imports on its own - without a schedule, new starters and changed phone numbers stop arriving the day after someone last pressed Import.',
        'done'     => 'At least one live import has run without an analyst starting it (that is, from the scheduled task).',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'directory_sync_runs', "mode = 'live' AND triggered_by_analyst_id IS NULL"],
    ],

    // ───────────────────────── CardDAV address books ─────────────────────────
    [
        'id'       => 'system.carddav_addressbook',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'CardDAV address book',
        'what'     => 'Reads a shared address book - Baikal, Nextcloud, Radicale and other CardDAV servers - and keeps your requesters\' contact details in step with it.',
        'why'      => 'Change someone\'s phone number or job title in the address book and the next import changes it in your service desk too, with no retyping.',
        'done'     => 'At least one enabled CardDAV address book is configured.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'carddav' AND enabled = 1"],
    ],
    [
        'id'       => 'system.carddav_scope',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Import chosen contacts only',
        'what'     => 'Limits an address-book import to the contact groups or categories you tick, instead of everyone in the book.',
        'why'      => 'Suppliers, family and the plumber stay out of your people list.',
        'done'     => 'At least one CardDAV address book imports by group or category.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'carddav' AND carddav_scope IN ('group', 'category')"],
    ],
    [
        'id'       => 'system.carddav_write_back',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Write changes back to contacts',
        'what'     => 'When an analyst corrects a contact\'s job title, department, office or phone on a ticket, the address-book card is updated too.',
        'why'      => 'The correction usually happens during the call - this saves the analyst fixing the same detail in a second application afterwards.',
        'done'     => 'At least one CardDAV address book has write-back switched on.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'carddav' AND carddav_write_back = 1"],
    ],
    [
        'id'       => 'system.carddav_allow_create',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Add people to the address book',
        'what'     => 'An "Add to address book" button on a person who emailed in but is not in your address book yet.',
        'why'      => 'It creates their contact card and links them in one step, so nobody types the same person in twice.',
        'done'     => 'At least one CardDAV address book lets analysts add people.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', "protocol = 'carddav' AND carddav_allow_create = 1"],
    ],

    // ───────────────────────── Companies (multi-company) ─────────────────────────
    [
        'id'       => 'system.multi_company',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Multiple companies',
        'what'     => 'More than one company (tenant) on one install, each with its own tickets, assets and users. Adding the second switches multi-company mode on.',
        'why'      => 'An MSP or group can support several separate client organisations from one service desk while keeping their data apart.',
        'done'     => 'At least two active companies exist (every install starts with one Default company).',
        'link'     => 'system/companies/',
        'check'    => ['rows', 'tenants', 'is_active = 1', 2],
    ],
    [
        'id'       => 'system.company_email_domains',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Company email domains',
        'what'     => 'Email domains owned by a company, such as acme.co.uk, so mail from anyone at that domain is filed under that company.',
        'why'      => 'Several clients can share one inbox and every ticket still lands in the right company, with no manual sorting from triage.',
        'done'     => 'At least one email domain is mapped to a company.',
        'link'     => 'system/companies/',
        'check'    => ['rows', 'tenant_domains'],
    ],
    [
        'id'       => 'system.company_specific_senders',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Specific senders per company',
        'what'     => 'Individual email addresses mapped to a company, for people who write in from Gmail, Outlook.com or another personal address.',
        'why'      => 'Contractors and small-business contacts on free email still reach the right company automatically, without mapping gmail.com to anybody.',
        'done'     => 'At least one sender address is mapped to a company.',
        'link'     => 'system/companies/',
        'check'    => ['rows', 'tenant_sender_addresses'],
    ],
    [
        'id'       => 'system.freemail_domains',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Extra public email domains',
        'what'     => 'Domains you add to the built-in list of personal and free email providers that are never matched to a company by domain.',
        'why'      => 'A regional or ISP mail domain your clients use gets the same protection as gmail.com, instead of being mapped to one company by mistake.',
        'done'     => 'At least one extra public email domain has been added.',
        'link'     => 'system/companies/',
        'check'    => ['rows', 'freemail_domains'],
    ],
    [
        'id'       => 'system.company_ticket_codes',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Company ticket codes',
        'what'     => 'A short code for a company that stands in for {COMPANY} in ticket numbers, instead of one derived from its name.',
        'why'      => 'Ticket numbers read cleanly for each client (ACME-1042), and two companies with similar names never share a prefix.',
        'done'     => 'At least one company has a ticket code set.',
        'link'     => 'system/companies/',
        'check'    => ['rows', 'tenants', "ticket_code IS NOT NULL AND ticket_code <> ''"],
    ],
    [
        'id'       => 'system.company_access_restricted',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Analysts limited to companies',
        'what'     => 'Analysts or teams granted a specific list of companies instead of access to all of them.',
        'why'      => 'A squad that looks after one client sees only that client\'s tickets and assets, which many clients expect and some contracts require.',
        'done'     => 'At least one active analyst is limited to chosen companies, or a team grants specific companies.',
        'link'     => 'system/analysts/',
        'check'    => ['any', [
            ['rows', 'analysts', 'can_access_all_tenants = 0 AND is_active = 1 AND is_demo = 0'],
            ['rows', 'team_tenant_access'],
        ]],
    ],
    [
        'id'       => 'system.company_overrides',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Per-company settings',
        'what'     => 'A company\'s own answer to an install-wide setting, or a shared list entry (ticket type, origin, asset type) hidden from one company\'s pickers.',
        'why'      => 'Each client can work the way it needs to - for example time tracking on for one, off for another - without a second install.',
        'done'     => 'At least one company has a setting override or a hidden shared entry.',
        'link'     => 'system/companies/',
        'check'    => ['any', [
            ['rows', 'tenant_settings'],
            ['rows', 'tenant_config_hidden'],
        ]],
    ],

    // ───────────────────────── Cost centres (GH #160) ─────────────────────────
    [
        'id'       => 'system.cost_centres',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Cost centres',
        'what'     => 'Your finance department\'s cost centres, for each company - with a hierarchy, kept in step with your accounting system by spreadsheet import or the API.',
        'why'      => 'With the list in place, what IT spends can be charged to the right budget, using the same codes finance already reports on.',
        'done'     => 'At least one active cost centre exists.',
        'link'     => 'system/cost-centres/',
        'check'    => ['rows', 'cost_centres', 'is_active = 1 AND is_demo = 0'],
    ],

    // ───────────────────────── Photo Album (just for fun) ─────────────────────────
    [
        'id'       => 'system.photo_album',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Photo Album',
        'what'     => 'Your webcam picture turned into ASCII art, live as you move - Braille, classic characters or blocks, on a green, amber, paper or full-colour screen.',
        'why'      => 'No reason at all, except that it is fun. The photo never leaves your browser; only the art is kept, and only if you save it.',
        'done'     => 'At least one picture has been saved to an album.',
        'link'     => 'system/photo-album/',
        'check'    => ['rows', 'photo_album'],
    ],

    // ───────────────────────── Encryption & maintenance ─────────────────────────
    [
        'id'       => 'system.encryption_key',
        'module'   => 'system',
        'tier'     => 'essential',
        'category' => 'security',
        'title'    => 'Encryption key',
        'what'     => 'The AES-256 key that FreeITSM encrypts stored secrets with - mailbox credentials, AI keys, SSO client secrets, directory passwords.',
        'why'      => 'Without it those secrets sit in the database as plain text, readable by anyone with a copy of a backup. Back the key file up - encrypted values cannot be recovered without it.',
        'done'     => 'At least one stored setting or provider secret is encrypted (carries the ENC: prefix).',
        'link'     => 'system/encryption/',
        'check'    => ['sql', "SELECT (SELECT COUNT(*) FROM system_settings WHERE setting_value LIKE 'ENC:%') + (SELECT COUNT(*) FROM auth_providers WHERE client_secret LIKE 'ENC:%' OR ldap_bind_password LIKE 'ENC:%' OR carddav_password LIKE 'ENC:%')"],
    ],
    [
        'id'       => 'system.db_verified',
        'module'   => 'system',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'Database up to date',
        'what'     => 'Database Verification compares your database with the schema this version expects and adds any missing tables, columns and indexes, without deleting data.',
        'why'      => 'Run after every update: a missing column is the usual cause of a screen that errors or a feature that quietly does nothing.',
        'done'     => 'Database Verification has been run since this version added Feature Bingo (its table exists).',
        'link'     => 'system/db-verify/',
        'check'    => ['sql', "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'feature_bingo_dismissed'"],
    ],

    // ───────────────────────── Date formats ─────────────────────────
    [
        'id'       => 'system.date_time_format',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Date and time format',
        'what'     => 'How dates and times are written across FreeITSM - 05 Aug 2026, 05/08/2026 or 2026-08-05, and 24-hour or 12-hour clock.',
        'why'      => 'It is what every analyst who has not chosen their own sees, and the only format your portal users get - so it should match how your organisation writes dates.',
        'done'     => 'The install-wide date or time format has been changed from the shipped default (DD MON YYYY, 24-hour).',
        'link'     => 'system/date-formats/',
        'check'    => ['any', [
            ['setting', 'date_format', 'neq', 'd_mon_y'],
            ['setting', 'time_format', 'neq', '24h'],
        ]],
    ],

    // ───────────────────────── Colours & branding ─────────────────────────
    [
        'id'       => 'system.module_colours',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Module colours',
        'what'     => 'The two-colour gradient on each module\'s icon in the app launcher and header.',
        'why'      => 'Matching them to your brand, or making the modules your team uses most stand out, helps people find their way at a glance.',
        'done'     => 'Module colours have been saved at least once.',
        'link'     => 'system/colours/',
        'check'    => ['rows', 'system_settings', "setting_key LIKE 'module\\_color\\_%'"],
    ],
    [
        'id'       => 'system.branding_logo',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'look',
        'title'    => 'Organisation logo',
        'what'     => 'Your logo, uploaded once and used on the sign-in screens and on branded output such as Network Mapper diagrams.',
        'why'      => 'People recognise the login page as yours rather than a generic one - which also makes a fake copy easier to spot.',
        'done'     => 'A logo has been uploaded.',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'branding_logo_path', 'nonempty'],
    ],
    [
        'id'       => 'system.branding_login_design',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Analyst sign-in screen design',
        'what'     => 'The background, form position, panel style, accent colour and wording of the page your team signs in on.',
        'why'      => 'A login page in your own colours and words feels like your service desk, not an off-the-shelf product.',
        'done'     => 'The analyst sign-in screen\'s background, layout, accent or heading has been changed from the default.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_login_bg_style', 'neq', 'gradient'],
            ['setting', 'branding_login_bg_from', 'neq', '#667eea'],
            ['setting', 'branding_login_bg_to', 'neq', '#764ba2'],
            ['setting', 'branding_login_form_position', 'neq', 'centre'],
            ['setting', 'branding_login_card_style', 'neq', 'solid'],
            ['setting', 'branding_login_accent', 'neq', '#2b88d8'],
            ['setting', 'branding_login_heading', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'system.branding_home_design',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Home page design',
        'what'     => 'The background, accent and wording of the landing page at the root of the site.',
        'why'      => 'If people arrive at the bare address, the first page they see carries your look rather than the theme default.',
        'done'     => 'The home page\'s background, accent or heading has been changed from the default.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_home_bg_style', 'neq', 'theme'],
            ['setting', 'branding_home_accent', 'neq', '#2b88d8'],
            ['setting', 'branding_home_heading', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'system.branding_background_image',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Sign-in background image',
        'what'     => 'A photograph or picture behind a sign-in screen, dimmed so the form stays readable.',
        'why'      => 'A picture of your building or your brand imagery makes the sign-in pages unmistakably yours.',
        'done'     => 'A background image has been uploaded for the analyst, portal or home screen.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_login_bg_image_path', 'nonempty'],
            ['setting', 'branding_portal_bg_image_path', 'nonempty'],
            ['setting', 'branding_home_bg_image_path', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'system.branding_banner',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Sign-in banner or footer text',
        'what'     => 'A coloured strip across the top or bottom of a sign-in screen, or footer text, carrying a message of your choosing.',
        'why'      => 'Useful for an acceptable-use notice, a support phone number, or "planned maintenance on Saturday" where everyone will see it.',
        'done'     => 'A banner is switched on, or footer text is set, on any sign-in screen.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_login_banner_position', 'in', ['top', 'bottom']],
            ['setting', 'branding_portal_banner_position', 'in', ['top', 'bottom']],
            ['setting', 'branding_home_banner_position', 'in', ['top', 'bottom']],
            ['setting', 'branding_login_footer_text', 'nonempty'],
            ['setting', 'branding_portal_footer_text', 'nonempty'],
            ['setting', 'branding_home_footer_text', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'system.branding_document_header_footer',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Header and footer for exports',
        'what'     => 'The default left, centre and right header and footer text on branded output such as diagrams, with tokens like {{title}} and {{author}}.',
        'why'      => 'Every exported diagram carries the same logo, title, author and version layout without setting it up each time.',
        'done'     => 'At least one saved export header or footer slot has text in it.',
        'link'     => 'system/branding/',
        'check'    => ['any', [
            ['setting', 'branding_header_left', 'nonempty'],
            ['setting', 'branding_header_center', 'nonempty'],
            ['setting', 'branding_header_right', 'nonempty'],
            ['setting', 'branding_footer_left', 'nonempty'],
            ['setting', 'branding_footer_center', 'nonempty'],
            ['setting', 'branding_footer_right', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'system.landing_page',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Front door of the site',
        'what'     => 'Which page someone reaching the bare site address is sent to - the analyst login or the self-service portal.',
        'why'      => 'If most visitors are requesters, sending them straight to the portal saves them landing on a login they cannot use.',
        'done'     => 'The default landing page has been saved on System > Branding (either choice counts).',
        'link'     => 'system/branding/',
        'check'    => ['setting', 'default_landing_page', 'nonempty'],
    ],

    // ───────────────────────── Search ─────────────────────────
    [
        'id'       => 'system.search_index',
        'module'   => 'system',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Full-text search index',
        'what'     => 'The index behind search across ticket subjects, emails, notes, knowledge articles and attachment text, kept up to date as things are created.',
        'why'      => 'Analysts can find the ticket where the same fault was fixed last year, including text inside attached documents.',
        'done'     => 'The search index holds at least one entry.',
        'link'     => 'system/search/',
        'check'    => ['rows', 'search_documents'],
    ],
    [
        'id'       => 'system.search_tika',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Apache Tika for attachments',
        'what'     => 'A connection to an Apache Tika server, which reads text out of PDFs, older Office formats and scanned documents for the search index.',
        'why'      => 'Word, Excel and PowerPoint are searchable without it, but PDFs - often the bulk of attachments - are not until Tika is connected.',
        'done'     => 'A Tika server address has been saved.',
        'link'     => 'system/integrations/tika.php',
        'check'    => ['setting', 'tika_url', 'nonempty'],
    ],
    [
        'id'       => 'system.desktop_notifications',
        'module'   => 'system',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Notifications on the desktop',
        'what'     => 'Preferences -> Notifications -> "Show desktop notifications", so new items in the bell pop up on your computer - in Edge on Windows, as Windows notifications - while FreeITSM is open in a tab.',
        'why'      => 'An assignment or a reply is noticed while you are working in another window, without watching the bell.',
        'done'     => 'Somebody has turned on desktop notifications.',
        'link'     => 'system/preferences/',
        'check'    => ['rows', 'user_preferences', "preference_key = 'desktop_notifications' AND preference_value = 'on'"],
    ],
];
