<?php
/** Feature Bingo cards - Tasks: statuses, priorities, tags, board and calendar settings, time, people, repeats, links and automation. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'tasks.first_task',
        'module'   => 'tasks',
        'tier'     => 'recommended',
        'category' => 'getting-started',
        'title'    => 'Tasks in use',
        'what'     => 'A lightweight work tracker for the jobs that are not tickets - project work, internal admin, follow-ups - shown as a board, list, calendar, timeline or table.',
        'why'      => 'Work that lives in personal notes or a spreadsheet is invisible to the rest of the team, and nobody notices when it stalls.',
        'done'     => 'At least one real task exists (demo data does not count).',
        'link'     => 'tasks/',
        'check'    => ['rows', 'tasks', 'is_demo = 0'],
    ],
    [
        'id'       => 'tasks.custom_statuses',
        'module'   => 'tasks',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Your own task statuses',
        'what'     => 'The states a task moves through, which become the columns of the Kanban board. Statuses flagged as Closed count as done, and one is the default for new tasks.',
        'why'      => 'The shipped To Do / In Progress / Blocked / Done list rarely matches how a team actually works - a status such as "Waiting on supplier" makes the board say where things really are.',
        'done'     => 'At least one task status exists beyond the five that ship with FreeITSM (a renamed one counts).',
        'link'     => 'tasks/settings/',
        'check'    => ['rows', 'task_statuses', "name NOT IN ('To Do', 'In Progress', 'Blocked', 'Done', 'Cancelled')"],
    ],
    [
        'id'       => 'tasks.custom_priorities',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own task priorities',
        'what'     => 'The priority bands shown on each task card, each with its own colour, and one marked as the default for new tasks.',
        'why'      => 'Priorities named in your own terms (or your own language) read at a glance on the board, and the card colour follows whatever you set here.',
        'done'     => 'At least one task priority exists beyond the four that ship with FreeITSM (a renamed one counts).',
        'link'     => 'tasks/settings/',
        'check'    => ['rows', 'task_priorities', "name NOT IN ('Low', 'Medium', 'High', 'Urgent')"],
    ],
    [
        'id'       => 'tasks.custom_tags',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own task tags',
        'what'     => 'Coloured labels for cross-cutting themes that do not fit a status or a priority. A task can carry any number of them.',
        'why'      => 'Tags let you pull out every task for an audit, a project or a site in one filter, however it is assigned or where it sits on the board.',
        'done'     => 'At least one task tag exists beyond the three examples that ship with FreeITSM (Security, ISO, Environment).',
        'link'     => 'tasks/settings/#tags',
        'check'    => ['rows', 'task_tags', "name NOT IN ('Security', 'ISO', 'Environment')"],
    ],
    [
        'id'       => 'tasks.tags_in_use',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Tasks tagged',
        'what'     => 'Tags applied to tasks, so they show as chips on cards and can be filtered and searched.',
        'why'      => 'A tag list nobody applies does nothing; tagged tasks are what make "show me everything for the ISO audit" a single click.',
        'done'     => 'At least one tag is applied to a task.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'task_tag_map'],
    ],
    [
        'id'       => 'tasks.tag_inline_create',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Create tags while editing',
        'what'     => 'Lets analysts type a brand-new tag straight onto a task instead of only picking from the list kept in Settings. Off by default.',
        'why'      => 'Saves a trip to Settings every time a new theme turns up - worth switching on if your team is trusted to keep the tag list tidy.',
        'done'     => 'The "create tags while editing" option is switched on in Tasks settings.',
        'link'     => 'tasks/settings/#tags',
        'check'    => ['sql', 'SELECT COUNT(*) FROM system_settings WHERE setting_key = \'tasks_tag_settings\' AND setting_value LIKE \'%"allow_create":1%\''],
    ],
    [
        'id'       => 'tasks.tags_on_calendar',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Tags on calendar and timeline',
        'what'     => 'Shows tag chips on the Tasks calendar and timeline views as well as on board cards. Off by default.',
        'why'      => 'When tags carry meaning - a project, a client, an audit - seeing them on the calendar tells you what a busy week is actually made of.',
        'done'     => 'The option to show tags on the calendar and timeline is switched on in Tasks settings.',
        'link'     => 'tasks/settings/#tags',
        'check'    => ['sql', 'SELECT COUNT(*) FROM system_settings WHERE setting_key = \'tasks_tag_settings\' AND setting_value LIKE \'%"surface_calendar":1%\''],
    ],
    [
        'id'       => 'tasks.card_fields',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'What a task card shows',
        'what'     => 'Chooses the extra detail on each board card - assignee, team, start and due dates, description, subtasks, links - and how priority reads (a dot, a pill, a coloured border or nothing).',
        'why'      => 'The right detail on the card lets people scan the board without opening every task; too much makes it unreadable.',
        'done'     => 'The card layout has been saved in Tasks settings at least once.',
        'link'     => 'tasks/settings/#card',
        'check'    => ['setting', 'tasks_card_fields', 'nonempty'],
    ],
    [
        'id'       => 'tasks.calendar_span_mode',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Multi-day tasks on the calendar',
        'what'     => 'Decides how a task with a start date and a later due date is drawn on the Tasks calendar: on its due date only, as one continuous bar, or as a chip on every day it covers.',
        'why'      => 'Teams that plan long pieces of work want to see the whole span; teams that care about deadlines want a calendar that only shows what must be finished.',
        'done'     => 'A calendar display mode has been saved in Tasks settings (the default, due date only, counts once saved).',
        'link'     => 'tasks/settings/#calendar',
        'check'    => ['setting', 'tasks_calendar_span_mode', 'nonempty'],
    ],
    [
        'id'       => 'tasks.time_scope',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Where task time is recorded',
        'what'     => 'Chooses whether scheduled work and time spent are offered on tasks, on subtasks, on both, or not at all.',
        'why'      => 'Recording time only at one level stops hours being counted twice and keeps the task panel free of fields your team never uses.',
        'done'     => 'The time recording setting has been saved in Tasks settings (the default, both, counts once saved).',
        'link'     => 'tasks/settings/#time',
        'check'    => ['setting', 'tasks_time_scope', 'nonempty'],
    ],
    [
        'id'       => 'tasks.time_logged',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Time logged on tasks',
        'what'     => 'Sessions of time actually spent on a task, as many as it took, each with notes.',
        'why'      => 'Knowing how long internal work really takes is what makes the next estimate - and the case for more staff - believable.',
        'done'     => 'At least one time entry has been recorded against a task.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'task_time_entries'],
    ],
    [
        'id'       => 'tasks.scheduled_work',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Work booked in on tasks',
        'what'     => 'A planned work window on a task - "being done 09:00 to 11:00 on Tuesday" - separate from its start and due dates.',
        'why'      => 'A booked slot turns a to-do into a plan, and with calendar sync it lands in the analyst\'s own calendar so nothing else gets booked over it.',
        'done'     => 'At least one real task has a scheduled work start time.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'tasks', 'work_start_datetime IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tasks.subtasks',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Subtasks',
        'what'     => 'Breaking a task into smaller steps, each with its own owner, status and dates, ticked off inside the parent task.',
        'why'      => 'A big job split into steps shows real progress on the card instead of sitting at "In Progress" for weeks.',
        'done'     => 'At least one real task has a subtask.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'tasks', 'parent_task_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tasks.collaborators',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Other people on a task',
        'what'     => 'Listing everyone else working on a task as Involved. The owner stays accountable, and the task also appears in each involved person\'s own list.',
        'why'      => 'Shared work stops falling through the gaps when every person on it sees it in their own list, not just the owner.',
        'done'     => 'At least one person has been added as involved on a real task.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'task_collaborators', 'is_demo = 0'],
    ],
    [
        'id'       => 'tasks.collaborator_completion',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Everyone ticks off their part',
        'what'     => 'Gives each person involved on a task a tick of their own, so you can see who has finished and who has not. Off by default.',
        'why'      => 'For sign-offs and multi-person checks, "done" should mean everyone has done their bit, and this shows exactly who is still outstanding.',
        'done'     => 'Per-person completion is switched on in Tasks settings.',
        'link'     => 'tasks/settings/#involved',
        'check'    => ['setting', 'tasks_collaborator_completion', 'eq', '1'],
    ],
    [
        'id'       => 'tasks.recurring',
        'module'   => 'tasks',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Repeating tasks',
        'what'     => 'A task that comes back on a pattern - weekly, monthly, yearly - with FreeITSM creating the next occurrence and carrying over the description, subtasks, assignee, tags and more.',
        'why'      => 'The monthly backup check or quarterly access review gets done because it appears on the board by itself, not because someone remembered it.',
        'done'     => 'At least one repeating task series exists.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'task_recurrences'],
    ],
    [
        'id'       => 'tasks.recurrence_cron',
        'module'   => 'tasks',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Scheduled job for repeats',
        'what'     => 'The server job cron/task_recurrence.php, which creates repeats set to run on a fixed schedule. Repeats that follow completion do not need it.',
        'why'      => 'Without it a fixed-schedule repeat never produces anything, with no error and no warning - it quietly does nothing.',
        'done'     => 'The repeat job has run at least once on this install.',
        'link'     => 'tasks/help.php',
        'check'    => ['setting', 'task_recurrence_last_run', 'nonempty'],
    ],
    [
        'id'       => 'tasks.linked_to_tickets',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Tasks linked to tickets',
        'what'     => 'Linking a task to the ticket it came from, so each can be reached from the other.',
        'why'      => 'Follow-up work raised from a ticket keeps its context, and whoever reads the ticket later can see the work it led to.',
        'done'     => 'At least one real task is linked to a ticket.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'tasks', 'ticket_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tasks.linked_to_changes',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Tasks linked to changes',
        'what'     => 'Linking a task to a change record, so the work needed to deliver a change is tracked on the board.',
        'why'      => 'A change is rarely one job; linked tasks show whether the pre-work and clean-up are actually finished.',
        'done'     => 'At least one real task is linked to a change.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'tasks', 'change_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tasks.linked_to_contracts',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Tasks linked to contracts',
        'what'     => 'Linking a task to a contract - a renewal review, a supplier meeting, a notice to give.',
        'why'      => 'Contract deadlines turn into owned pieces of work with a due date, instead of a date someone hopes to notice.',
        'done'     => 'At least one real task is linked to a contract.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'tasks', 'contract_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tasks.documents',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Documents on tasks',
        'what'     => 'Files and links attached to a task - a checklist, a quote, a screenshot of the finished job.',
        'why'      => 'The evidence and reference material for a piece of work stays with it rather than in someone\'s inbox.',
        'done'     => 'At least one document is attached to a task.',
        'link'     => 'tasks/',
        'check'    => ['rows', 'document_links', "parent_type = 'task'"],
    ],
    [
        'id'       => 'tasks.shared_table_views',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Shared task table views',
        'what'     => 'A saved arrangement of the Tasks table - columns, sort and filters - shared with a team or with everyone.',
        'why'      => 'One well-built view such as "Overdue, by owner" saves every analyst from building the same filters themselves.',
        'done'     => 'At least one saved Tasks table view is shared with a team or with everyone.',
        'link'     => 'tasks/table/',
        'check'    => ['rows', 'table_views', "table_key = 'tasks' AND visibility IN ('team', 'public')"],
    ],
    [
        'id'       => 'tasks.calendar_sync',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Tasks in your own calendar',
        'what'     => 'Sends an analyst\'s task work windows, due dates or both into their own calendar (Microsoft 365 or CalDAV) through calendar sync. Off for everyone until they choose it.',
        'why'      => 'Work booked on a task blocks out real time in the calendar people actually live in, so meetings do not get booked over it.',
        'done'     => 'At least one analyst has chosen to send tasks to their calendar.',
        'link'     => 'system/calendar-sync/',
        'check'    => ['rows', 'calendar_enrolments', "task_mode <> 'off'"],
    ],
    [
        'id'       => 'tasks.workflow_triggers',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on task events',
        'what'     => 'A workflow that runs when a task is created, assigned, commented on, changes status or due date, or is completed.',
        'why'      => 'Lets FreeITSM notify people, update tickets or start the next job automatically when task work moves on.',
        'done'     => 'At least one real workflow is triggered by a task event.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', "trigger_event LIKE 'task.%' AND is_demo = 0"],
    ],
    [
        'id'       => 'tasks.workflow_creates_tasks',
        'module'   => 'tasks',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows that create tasks',
        'what'     => 'A workflow with a "create task" action, so a ticket, change or other event produces a task on the board by itself.',
        'why'      => 'Standard follow-up work - a new starter\'s kit list, a post-change review - is raised every time without relying on memory.',
        'done'     => 'At least one real workflow has a create task action.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', "actions LIKE '%create_task%' AND is_demo = 0"],
    ],
];
