<?php
/** Feature Bingo cards - Tickets settings: departments, types, origins, categories, closure gates, statuses, priorities, SLA, numbering, general, privacy, row display, merging, indexing and time tracking. See includes/feature_bingo.php for the format. */

// Each card links to its Tickets -> Settings tab (the page opens #<tab>).
$link = 'tickets/settings/';

// Rows Database Verification seeds into an empty table (api/system/db_verify.php).
// A card counts rows OUTSIDE these, so a fresh install does not light up.
$seedStatuses    = "'Open','In Progress','On Hold','Awaiting Response','Closed'";
$seedPriorities  = "'Low','Normal','High','Critical','Urgent'";
$seedTypes       = "'Incident','Service Request','Question'";
$seedOrigins     = "'Email','Phone','Portal','Walk-up','WhatsApp','Web chat','Slack'";
$seedResolutions = "'Fixed remotely','Fixed on site','Hardware replaced','Configuration change','Training given','Access granted','No fault found','Duplicate','Withdrawn','Referred to supplier'";

// A per-company switch (tenant_settings) that has been turned on for at least one company.
$companyOn = function (string $key): array {
    return ['sql', "SELECT COUNT(*) FROM tenant_settings WHERE setting_key = '$key' AND setting_value = '1'"];
};

return [

    // ─── Departments ────────────────────────────────────────────────────────
    [
        'id'       => 'tickets.departments',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Departments',
        'what'     => 'The areas of your organisation tickets are filed under, such as IT, HR or Facilities.',
        'why'      => 'Departments decide which teams see which tickets and let SLA notifications and reports be split by area rather than lumping every request together.',
        'done'     => 'At least one department exists (demo data not counted).',
        'link'     => 'tickets/settings/#departments',
        'check'    => ['rows', 'departments', 'is_demo = 0'],
    ],
    [
        'id'       => 'tickets.department_teams',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'security',
        'title'    => 'Teams assigned to departments',
        'what'     => 'Each department is linked to the teams whose analysts may see and work its tickets.',
        'why'      => 'Without it everyone sees everything; with it an HR ticket stays with the HR team and the IT queue stays readable.',
        'done'     => 'At least one department has a team assigned to it (demo data not counted).',
        'link'     => 'tickets/settings/#departments',
        'check'    => ['rows', 'department_teams', 'is_demo = 0'],
    ],
    [
        'id'       => 'tickets.confidential_departments',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Confidential departments',
        'what'     => 'A department switched to "Tickets here are confidential" marks every ticket in it, or moved into it, as Confidential.',
        'why'      => 'Sensitive areas such as HR or grievances stay hidden from the requester\'s managers and out of AI features without relying on an analyst to remember to flag each ticket.',
        'done'     => 'At least one department is set to make its tickets confidential.',
        'link'     => 'tickets/settings/#departments',
        'check'    => ['rows', 'departments', "default_sensitivity = 'confidential'"],
    ],

    // ─── Ticket types and origins ───────────────────────────────────────────
    [
        'id'       => 'tickets.ticket_types',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Your own ticket types',
        'what'     => 'The list that says what kind of request a ticket is. FreeITSM starts you with Incident, Service Request and Question.',
        'why'      => 'Types that match how your desk actually works - Change, Access request, New starter - make the queue easier to triage and the reports worth reading.',
        'done'     => 'At least one ticket type exists beyond the three FreeITSM seeds (demo data not counted).',
        'link'     => 'tickets/settings/#ticket-types',
        'check'    => ['rows', 'ticket_types', "is_demo = 0 AND name NOT IN ($seedTypes)"],
    ],
    [
        'id'       => 'tickets.ticket_origins',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own ticket origins',
        'what'     => 'The list that records how a ticket came in. FreeITSM starts you with Email, Phone, Portal, Walk-up and its messaging channels.',
        'why'      => 'Adding the routes you really use, such as Teams chat or a supplier portal, shows where your work comes from and where self-service could take some of it.',
        'done'     => 'At least one ticket origin exists beyond the ones FreeITSM seeds (demo data not counted).',
        'link'     => 'tickets/settings/#ticket-origins',
        'check'    => ['rows', 'ticket_origins', "is_demo = 0 AND name NOT IN ($seedOrigins)"],
    ],
    [
        'id'       => 'tickets.company_specific_lists',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Per-company ticket lists',
        'what'     => 'On an install serving several companies, a company can add its own ticket types and origins or hide the shared ones it does not use.',
        'why'      => 'Each client sees a short list that fits its own service rather than every option every other client needed.',
        'done'     => 'At least one company has its own ticket type or origin, or has hidden a shared entry.',
        'link'     => $link,
        'check'    => ['any', [
            ['rows', 'tenant_config_hidden'],
            ['rows', 'ticket_types', 'tenant_id IS NOT NULL AND is_demo = 0'],
            ['rows', 'ticket_origins', 'tenant_id IS NOT NULL AND is_demo = 0'],
        ]],
    ],

    // ─── Categories and resolution codes ────────────────────────────────────
    [
        'id'       => 'tickets.categories',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Ticket categories',
        'what'     => 'A list of what tickets are about, such as "Printing" or "User onboarding", that sits alongside the ticket type.',
        'why'      => 'Categories are what let you see that a third of your tickets are about one system, which is how you decide what to fix, document or automate next.',
        'done'     => 'At least one ticket category exists (demo data not counted).',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['rows', 'ticket_categories', 'is_demo = 0'],
    ],
    [
        'id'       => 'tickets.sub_categories',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Sub-categories',
        'what'     => 'Categories nested under other categories, up to three levels deep, such as Hardware > Laptops > Battery.',
        'why'      => 'Reports can roll up to the top level for the big picture or drill down to the detail when you need to know exactly what keeps breaking.',
        'done'     => 'At least one category sits under another (demo data not counted).',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['rows', 'ticket_categories', 'parent_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tickets.categories_by_type',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Categories tied to a ticket type',
        'what'     => 'A top-level category can be limited to one ticket type, so it is only offered on tickets of that type.',
        'why'      => 'Analysts choosing a category for an incident are not wading through service request options, and the wrong combination cannot be picked.',
        'done'     => 'At least one category is tied to a ticket type (demo data not counted).',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['rows', 'ticket_categories', 'ticket_type_id IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tickets.analyst_only_categories',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Analyst-only categories',
        'what'     => 'Categories switched off for the portal are offered to analysts but never shown to requesters.',
        'why'      => 'Requesters get a short list in plain English while analysts keep the full technical tree.',
        'done'     => 'At least one category is hidden from the self-service portal (demo data not counted).',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['rows', 'ticket_categories', 'is_portal_visible = 0 AND is_demo = 0'],
    ],
    [
        'id'       => 'tickets.category_field',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Category field switched on',
        'what'     => 'Shows the Category field on tickets, so each one is filed under what it was reported as. It starts switched off until you have built the list.',
        'why'      => 'A category list nobody can pick from records nothing; switching the field on is what starts the data flowing into reports.',
        'done'     => 'The Category field is switched on for the installation or for at least one company.',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['any', [
            ['setting', 'ticket_category_enabled', 'eq', '1'],
            $companyOn('ticket_category_enabled'),
        ]],
    ],
    [
        'id'       => 'tickets.closure_category_field',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Category at close',
        'what'     => 'Asks for the category again when a ticket closes, recording what the problem turned out to be rather than what it was reported as.',
        'why'      => 'It is what tells you that 12 of your 37 "printer problems" were actually the network - the difference between guessing and knowing where to invest.',
        'done'     => 'The Category at close field is switched on for the installation or for at least one company.',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['any', [
            ['setting', 'ticket_closure_category_enabled', 'eq', '1'],
            $companyOn('ticket_closure_category_enabled'),
        ]],
    ],
    [
        'id'       => 'tickets.resolution_code_field',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Resolution codes on closure',
        'what'     => 'Asks how a ticket ended - "Fixed remotely", "Training given", "No fault found" - when it closes.',
        'why'      => 'Seeing that a fifth of tickets end in "Training given" points straight at the guide or course that would prevent them.',
        'done'     => 'The Resolution code field is switched on for the installation or for at least one company.',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['any', [
            ['setting', 'ticket_resolution_code_enabled', 'eq', '1'],
            $companyOn('ticket_resolution_code_enabled'),
        ]],
    ],
    [
        'id'       => 'tickets.resolution_codes',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Your own resolution codes',
        'what'     => 'The flat list of ways a ticket can end. FreeITSM seeds ten common ones.',
        'why'      => 'Codes in your own words, such as "Replaced under warranty", make closure reports match how your desk talks about its work.',
        'done'     => 'At least one resolution code exists beyond the ten FreeITSM seeds (demo data not counted).',
        'link'     => 'tickets/settings/#categories',
        'check'    => ['rows', 'ticket_resolution_codes', "is_demo = 0 AND name NOT IN ($seedResolutions)"],
    ],

    // ─── Closure gates: checklists and mandatory fields ─────────────────────
    [
        'id'       => 'tickets.checklist_closure_gate',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Checklist steps at closure',
        'what'     => 'Decides what happens when a ticket is closed with mandatory checklist steps still unticked: follow each checklist\'s own gate, or block every such close.',
        'why'      => 'Where procedures must be followed - leavers, access removal, audited processes - a blanket block makes sure no ticket closes with a step skipped.',
        'done'     => 'The checklist closure rule has been saved.',
        'link'     => 'tickets/settings/#checklists',
        'check'    => ['setting', 'ticket_checklist_closure_mode', 'nonempty'],
    ],
    [
        'id'       => 'tickets.checklist_required',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Checklist required to close',
        'what'     => 'Warns, or refuses the close, when a ticket has no checklist attached at all.',
        'why'      => 'For desks where every ticket must follow a procedure, it catches the ones where nobody attached one, and records who closed them anyway.',
        'done'     => 'Closing a ticket with no checklist is set to warn or to refuse.',
        'link'     => 'tickets/settings/#checklists',
        'check'    => ['setting', 'ticket_checklist_empty_closure_mode', 'in', ['warn', 'block']],
    ],
    [
        'id'       => 'tickets.mandatory_fields',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Mandatory fields at closure',
        'what'     => 'Pick which ticket fields - category, resolution code, owner, priority and so on - must be filled in before a ticket closes.',
        'why'      => 'Reports are only as good as the fields behind them; this stops tickets closing with the one field your monthly figures depend on left empty. It applies on screen, in bulk actions, the API and workflows.',
        'done'     => 'At least one field is ticked as required before closing.',
        'link'     => 'tickets/settings/#mandatory-fields',
        'check'    => ['setting', 'ticket_mandatory_fields', 'nonempty'],
    ],
    [
        'id'       => 'tickets.mandatory_fields_block',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Refuse closure with empty fields',
        'what'     => 'Instead of warning, a ticket cannot reach a closed status until every required field is filled in.',
        'why'      => 'A warning can be clicked past; a refusal guarantees the data is there for every closed ticket.',
        'done'     => 'The mandatory fields rule is set to refuse the close.',
        'link'     => 'tickets/settings/#mandatory-fields',
        'check'    => ['setting', 'ticket_mandatory_mode', 'eq', 'block'],
    ],
    [
        'id'       => 'tickets.mandatory_fields_notify',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Email about incomplete closures',
        'what'     => 'When a ticket is closed with required fields empty, the addresses you list are emailed the ticket, the empty fields and who closed it.',
        'why'      => 'A service delivery manager hears about gaps as they happen instead of discovering them in the month-end report.',
        'done'     => 'The mandatory fields rule is set to warn and email, and at least one address is saved.',
        'link'     => 'tickets/settings/#mandatory-fields',
        'check'    => ['all', [
            ['setting', 'ticket_mandatory_mode', 'eq', 'notify'],
            ['setting', 'ticket_mandatory_notify', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'tickets.mandatory_fields_record',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Record skipped fields on tickets',
        'what'     => 'Writes an internal note naming the empty fields, who closed the ticket and how, whenever a close goes ahead past the warning.',
        'why'      => 'An override that leaves no trace cannot be audited; the note shows exactly which closures skipped the rule.',
        'done'     => 'The "Record it on the ticket" option has been saved switched on.',
        'link'     => 'tickets/settings/#mandatory-fields',
        'check'    => ['setting', 'ticket_mandatory_record', 'eq', '1'],
    ],

    // ─── Statuses and priorities ────────────────────────────────────────────
    [
        'id'       => 'tickets.statuses',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Your own ticket statuses',
        'what'     => 'The states a ticket moves through. FreeITSM seeds Open, In Progress, On Hold, Awaiting Response and Closed.',
        'why'      => 'Statuses that match your real process, such as "Awaiting supplier" or "Scheduled", show at a glance why a ticket is not moving.',
        'done'     => 'At least one ticket status exists beyond the five FreeITSM seeds.',
        'link'     => 'tickets/settings/#statuses',
        'check'    => ['rows', 'ticket_statuses', "name NOT IN ($seedStatuses)"],
    ],
    [
        'id'       => 'tickets.statuses_pause_sla',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Statuses that pause the SLA',
        'what'     => 'A status marked "Pauses SLA clock" stops the SLA timer while a ticket sits in it.',
        'why'      => 'Time spent waiting on the requester or a supplier no longer counts against your team, so breach figures reflect work you could actually do.',
        'done'     => 'At least one status is set to pause the SLA clock.',
        'link'     => 'tickets/settings/#statuses',
        'check'    => ['rows', 'ticket_statuses', 'pauses_sla = 1'],
    ],
    [
        'id'       => 'tickets.priorities',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own ticket priorities',
        'what'     => 'The priority bands shown on tickets. FreeITSM seeds Low, Normal, High, Critical and Urgent.',
        'why'      => 'Priorities named to match your agreed service levels, such as P1 to P4, make every SLA target and report line up with what customers were promised.',
        'done'     => 'At least one priority exists beyond the five FreeITSM seeds.',
        'link'     => 'tickets/settings/#priorities',
        'check'    => ['rows', 'ticket_priorities', "name NOT IN ($seedPriorities)"],
    ],

    // ─── SLA ────────────────────────────────────────────────────────────────
    [
        'id'       => 'tickets.sla_enforcement',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'SLA enforcement switched on',
        'what'     => 'The "Enforce SLAs from" date turns SLA tracking on for every ticket created from that point.',
        'why'      => 'Until it is set, no ticket is measured, flagged or escalated, however carefully the targets are configured. The date lets you start clean without back-dating breaches on old tickets.',
        'done'     => 'An "Enforce SLAs from" date is saved.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['setting', 'sla_enforce_from', 'nonempty'],
    ],
    [
        'id'       => 'tickets.sla_targets',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'SLA targets per priority',
        'what'     => 'Response and resolution times, in business minutes, for each ticket priority.',
        'why'      => 'Targets are what the warning colours, breach emails and SLA reports measure against; without them there is nothing to hit or miss.',
        'done'     => 'At least one priority has a response or resolution target.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['rows', 'ticket_priorities', 'sla_response_minutes IS NOT NULL OR sla_resolution_minutes IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.sla_calendar',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Business hours for SLAs',
        'what'     => 'A calendar of your working days, hours and timezone that SLA clocks tick against. FreeITSM seeds Monday to Friday, 09:00 to 17:00, London time.',
        'why'      => 'If your desk works different hours or from another timezone, the seeded calendar breaches tickets while nobody is on shift, or lets them slide while you are.',
        'done'     => 'A calendar exists with a different name or timezone from the seed, or any calendar has hours other than Monday to Friday 09:00-17:00.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['sql', "SELECT (SELECT COUNT(*) FROM sla_calendars WHERE name <> 'Default Business Hours' OR timezone <> 'Europe/London') + (SELECT COUNT(*) FROM sla_calendar_hours WHERE start_time <> '09:00:00' OR end_time <> '17:00:00' OR weekday NOT IN (1,2,3,4,5))"],
    ],
    [
        'id'       => 'tickets.sla_holidays',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Holidays in the SLA calendar',
        'what'     => 'Public holidays and closure days added to a business calendar, so the SLA clock stops on them.',
        'why'      => 'Without them a ticket raised before a bank holiday weekend breaches while the office is shut.',
        'done'     => 'At least one holiday is saved on a business calendar.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['rows', 'sla_calendar_holidays'],
    ],
    [
        'id'       => 'tickets.sla_multiple_calendars',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Several business calendars',
        'what'     => 'More than one calendar, so different priorities can run on different hours - for example critical tickets on a 24x7 clock.',
        'why'      => 'An out-of-hours or follow-the-sun service can be measured honestly alongside a normal office-hours one.',
        'done'     => 'At least two active business calendars exist.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['rows', 'sla_calendars', 'is_active = 1', 2],
    ],
    [
        'id'       => 'tickets.sla_notification_rules',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'SLA breach notifications',
        'what'     => 'Rules that email the assignee, the department\'s teams, a named analyst or any address when a ticket nears or passes its SLA.',
        'why'      => 'No rules means no emails, even when a ticket breaches. A warning rule gives someone the chance to act before the target is missed.',
        'done'     => 'At least one active breach notification rule exists.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['rows', 'sla_notification_rules', 'is_active = 1'],
    ],
    [
        'id'       => 'tickets.sla_department_rules',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Department-specific SLA alerts',
        'what'     => 'A notification rule scoped to one department, which replaces the default rule for that department\'s tickets.',
        'why'      => 'A team with its own escalation path, such as infrastructure paging an on-call address, gets its own alerts without changing everybody else\'s.',
        'done'     => 'At least one active notification rule is scoped to a specific department.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['rows', 'sla_notification_rules', 'is_active = 1 AND department_id IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.sla_cron',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'SLA breach check scheduled',
        'what'     => 'The scheduled task cron/sla_breach_check.php, run from cron or Task Scheduler, which finds tickets nearing or past their SLA and sends the notification emails.',
        'why'      => 'Notification rules do nothing on their own; without the scheduled task no warning or breach email is ever sent.',
        'done'     => 'The breach-check task has completed successfully at least once in its retained history.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['rows', 'sla_cron_runs', "outcome = 'ok'"],
    ],
    [
        'id'       => 'tickets.sla_warning_threshold',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'SLA warning threshold',
        'what'     => 'The percentage of a ticket\'s SLA that must pass before it is flagged as at risk. The shipped value is 80%.',
        'why'      => 'Short targets may need an earlier warning to leave time to act; long ones may need a later one to avoid a sea of amber.',
        'done'     => 'The warning threshold has been changed from the shipped 80%.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['setting', 'sla_warning_threshold_percent', 'neq', '80'],
    ],
    [
        'id'       => 'tickets.sla_priority_change',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'SLA on priority change',
        'what'     => 'What happens to the SLA clock when a ticket\'s priority changes: apply the new target from that point, recompute from the start, or reset the clock.',
        'why'      => 'Matching your contracts here stops disputes over whether an upgraded ticket really breached.',
        'done'     => 'The priority-change rule has been changed from the shipped "apply from the change point forward".',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['setting', 'sla_priority_change_behaviour', 'neq', 'forward'],
    ],
    [
        'id'       => 'tickets.sla_reopen',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'SLA on reopened tickets',
        'what'     => 'Whether a reopened ticket starts a fresh SLA or continues from where its clock stopped.',
        'why'      => 'Continuing the clock stops a ticket that was closed too early from quietly earning a brand-new deadline.',
        'done'     => 'The reopen rule has been changed from the shipped "start the SLA fresh".',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['setting', 'sla_reopen_behaviour', 'neq', 'reset'],
    ],
    [
        'id'       => 'tickets.sla_first_response',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'What counts as first response',
        'what'     => 'Decides what stops the response clock: an outbound email, a status change away from the default, or whichever comes first.',
        'why'      => 'If your contracts promise a reply rather than an acknowledgement, counting only outbound email stops a status change from meeting the target on paper.',
        'done'     => 'The first-response rule has been changed from the shipped "either, whichever happens first".',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['setting', 'sla_first_response_definition', 'neq', 'either'],
    ],
    [
        'id'       => 'tickets.sla_warn_assignee',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Warn the assignee',
        'what'     => 'Emails the analyst a ticket is assigned to when it crosses the SLA warning threshold.',
        'why'      => 'The person who can fix it hears first, while there is still time to act.',
        'done'     => 'SLA enforcement is on and "Email the assignee at warning threshold" is switched on.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['all', [
            ['setting', 'sla_enforce_from', 'nonempty'],
            ['setting', 'sla_notify_assignee_at_warning', 'eq', '1'],
        ]],
    ],
    [
        'id'       => 'tickets.sla_breach_lead',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Tell the team lead at breach',
        'what'     => 'Emails the team lead when a ticket actually breaches its SLA.',
        'why'      => 'A missed target reaches someone who can reassign work or speak to the customer, not only the analyst already behind.',
        'done'     => 'SLA enforcement is on and "Email the team lead at breach" is switched on.',
        'link'     => 'tickets/settings/#sla',
        'check'    => ['all', [
            ['setting', 'sla_enforce_from', 'nonempty'],
            ['setting', 'sla_notify_lead_at_breach', 'eq', '1'],
        ]],
    ],

    // ─── Numbering ──────────────────────────────────────────────────────────
    [
        'id'       => 'tickets.numbering_sequential',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Readable ticket numbers',
        'what'     => 'Switches ticket references from random ones like CKQ-418-73926 to numbers that count up, such as TICKET-000042.',
        'why'      => 'A reference is read out on the phone and written on forms; one a person can say and remember saves time on every call.',
        'done'     => 'Ticket numbering is set to count up.',
        'link'     => 'tickets/settings/#numbering',
        'check'    => ['setting', 'ticket_number_style', 'eq', 'sequential'],
    ],
    [
        'id'       => 'tickets.numbering_format',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Custom ticket number format',
        'what'     => 'Your own shape for ticket numbers, using tokens for the digits, year, month, day, ticket type or company - for example INC-{YYYY}-{#####}.',
        'why'      => 'References that say what they are and when they were raised are easier to recognise at a glance and match what your staff are used to.',
        'done'     => 'Numbering counts up and the format differs from the shipped TICKET-{######}.',
        'link'     => 'tickets/settings/#numbering',
        'check'    => ['all', [
            ['setting', 'ticket_number_style', 'eq', 'sequential'],
            ['setting', 'ticket_number_format', 'neq', 'TICKET-{######}'],
        ]],
    ],
    [
        'id'       => 'tickets.numbering_start',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Carry on your old numbering',
        'what'     => 'Sets the number the ticket counter starts from.',
        'why'      => 'Moving from another system, your new tickets can carry on where the old ones left off instead of starting again at 1.',
        'done'     => 'The starting number has been changed from 1.',
        'link'     => 'tickets/settings/#numbering',
        'check'    => ['setting', 'ticket_number_start', 'neq', '1'],
    ],
    [
        'id'       => 'tickets.numbering_scope',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Separate number sequences',
        'what'     => 'Counts ticket numbers separately for each ticket type or each company, rather than one sequence for everything.',
        'why'      => 'Incidents and requests get their own runs of numbers - INC-00012, REQ-00012 - the way most large service desks work.',
        'done'     => 'Numbering is set to count per ticket type or per company.',
        'link'     => 'tickets/settings/#numbering',
        'check'    => ['setting', 'ticket_number_scope', 'in', ['per_type', 'per_company']],
    ],
    [
        'id'       => 'tickets.numbering_reset',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Yearly or monthly number reset',
        'what'     => 'Starts the ticket counter again every year or every month, used with a year or month in the format.',
        'why'      => 'Numbers such as INC-2026-00001 stay short and tell you at a glance when a ticket was raised.',
        'done'     => 'The counter is set to start again every year or every month.',
        'link'     => 'tickets/settings/#numbering',
        'check'    => ['setting', 'ticket_number_reset', 'in', ['yearly', 'monthly']],
    ],

    // ─── General ────────────────────────────────────────────────────────────
    [
        'id'       => 'tickets.reopen_on_reply',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Reopen on requester reply',
        'what'     => 'Decides whether a closed ticket reopens when the requester replies - from the portal, an email, WhatsApp or web chat.',
        'why'      => 'A requester saying "it is still broken" to a closed ticket should not go unread; turning it off suits desks that prefer a new ticket for every new problem.',
        'done'     => 'The reopening setting has been saved, on or off.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'reopen_on_customer_reply', 'nonempty'],
    ],
    [
        'id'       => 'tickets.snooze_wake_hour',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Start of the working day',
        'what'     => 'The hour a ticket snoozed until "Tomorrow" or "Next week" comes back, in each analyst\'s own timezone.',
        'why'      => 'Snoozed tickets reappear when your desk actually starts, rather than at the shipped 09:00.',
        'done'     => 'The start of the working day has been saved.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'snooze_wake_hour', 'nonempty'],
    ],
    [
        'id'       => 'tickets.collapse_long_messages',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Shorten long messages',
        'what'     => 'Messages taller than a set length are shortened with a Show more link. Nothing is deleted.',
        'why'      => 'Long email chains stop burying the line you opened the ticket to read.',
        'done'     => 'Shortening long messages has been saved switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_collapse_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.collapse_lines',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Length before shortening',
        'what'     => 'About how many lines a message may run before it is shortened. The shipped value is 12.',
        'why'      => 'A desk that lives in email may want more on screen; one that barely uses it may want less.',
        'done'     => 'The line limit has been saved.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_collapse_lines', 'nonempty'],
    ],
    [
        'id'       => 'tickets.collapse_expand_newest',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Newest message always in full',
        'what'     => 'The most recent message on a ticket is never shortened.',
        'why'      => 'The message you came to read is always there in full without an extra click.',
        'done'     => 'The option has been saved switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_collapse_expand_newest', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.collapse_quoted',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Shorten quoted history',
        'what'     => 'Quoted email history under a reply is shortened separately from the message length.',
        'why'      => 'A two-line reply with a long quoted chain beneath it becomes readable again.',
        'done'     => 'The option has been saved switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_collapse_quoted', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.collapse_remember',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Remember expanded messages',
        'what'     => 'Messages an analyst expands stay expanded on that device.',
        'why'      => 'Working through a long thread does not undo itself every time the ticket refreshes.',
        'done'     => 'The option has been saved switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_collapse_remember', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.group_older',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Fold older messages away',
        'what'     => 'On a long ticket, messages older than the most recent few fold into a single line you can open.',
        'why'      => 'A ticket with fifty messages opens at the latest part of the conversation instead of a long scroll.',
        'done'     => 'The option has been saved switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_group_older', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.group_show',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Recent messages kept open',
        'what'     => 'How many of the most recent messages stay open before older ones fold away. The shipped value is 6.',
        'why'      => 'Lets you tune how much context an analyst sees on a long ticket before anything is folded.',
        'done'     => 'The number of messages to keep open has been saved.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_group_show', 'nonempty'],
    ],
    [
        'id'       => 'tickets.flag_duplicates',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Point out repeated messages',
        'what'     => 'A resend, a duplicate delivery or a bounce carrying the original back is folded away with a note saying which message it matches.',
        'why'      => 'Analysts stop re-reading the same email three times to find out whether anything new was said.',
        'done'     => 'The option has been saved switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_flag_duplicates', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.ai_summary',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI ticket summary',
        'what'     => 'A short AI-written summary at the top of each ticket saying where it stands, written on request with every version kept. Uses the AI provider set on the Reply cleanup tab.',
        'why'      => 'Whoever picks up a long ticket - after a holiday, a handover or an escalation - knows where it stands in seconds instead of reading the whole thread.',
        'done'     => 'The AI summary is switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_ai_summary_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.ai_summary_auto_refresh',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Auto-refresh the AI summary',
        'what'     => 'Rewrites the summary automatically once a set number of new messages have arrived, when an analyst opens the ticket.',
        'why'      => 'The summary keeps up with the conversation without anyone pressing Refresh, and a queue nobody is reading still costs nothing.',
        'done'     => 'The AI summary is on and set to refresh after one or more new messages.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['all', [
            ['setting', 'ticket_ai_summary_enabled', 'eq', '1'],
            ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'ticket_ai_summary_auto_after' AND CAST(setting_value AS UNSIGNED) > 0"],
        ]],
    ],
    [
        'id'       => 'tickets.ai_summary_max_messages',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'How far AI summaries read',
        'what'     => 'The number of messages a summary reads, working back from the newest. The shipped value is 60.',
        'why'      => 'Balances cost against coverage: fewer messages is cheaper, more gives a fuller picture of very long tickets.',
        'done'     => 'The AI summary is on and the number of messages to read has been saved.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['all', [
            ['setting', 'ticket_ai_summary_enabled', 'eq', '1'],
            ['setting', 'ticket_ai_summary_max_messages', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'tickets.ai_summary_include_notes',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Internal notes in AI summaries',
        'what'     => 'Decides whether the AI summary may read internal notes as well as the conversation.',
        'why'      => 'Notes often hold what was actually tried, which makes summaries far more useful; turn it off if your notes hold things that should not leave the desk.',
        'done'     => 'The AI summary is on and the internal notes choice has been saved, on or off.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['all', [
            ['setting', 'ticket_ai_summary_enabled', 'eq', '1'],
            ['setting', 'ticket_ai_summary_include_notes', 'nonempty'],
        ]],
    ],
    [
        'id'       => 'tickets.ai_read_for_me',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Read it for me',
        'what'     => 'A button on a ticket that has AI read the whole thing and brief you: what happened, what is unresolved and what to do next. Nothing is stored.',
        'why'      => 'An analyst new to a ticket gets up to speed and a suggested next step without reading every message.',
        'done'     => '"Read it for me" is switched on.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_ai_read_enabled', 'eq', '1'],
    ],
    [
        'id'       => 'tickets.ai_confidential',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Confidential tickets and AI',
        'what'     => 'Decides whether confidential tickets may be sent to any AI feature - summaries, Read it for me, reply clean-up, merge summaries, the war room bot and the rest.',
        'why'      => 'Keeps HR and other sensitive tickets from ever reaching an outside AI provider, or deliberately allows it if your provider agreement covers them.',
        'done'     => 'The confidential tickets and AI choice has been saved.',
        'link'     => 'tickets/settings/#general',
        'check'    => ['setting', 'ticket_ai_confidential', 'nonempty'],
    ],

    // ─── Privacy ────────────────────────────────────────────────────────────
    [
        'id'       => 'tickets.portal_third_party',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Third-party messages in the portal',
        'what'     => 'Decides how much a requester sees in the self-service portal of messages sent to someone else on their ticket, such as a forward to a supplier: hidden, shown without attachments, or everything.',
        'why'      => 'Most people assume a forward to a supplier is private; choosing deliberately avoids a requester reading a conversation that was never meant for them.',
        'done'     => 'The third-party message policy has been saved.',
        'link'     => 'tickets/settings/#privacy',
        'check'    => ['setting', 'portal_third_party_visibility', 'nonempty'],
    ],

    // ─── Row display ────────────────────────────────────────────────────────
    [
        'id'       => 'tickets.row_display_default',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Default ticket row layout',
        'what'     => 'Sets, for everyone who has not chosen their own, how priority, status, assigned agent and the requester\'s name appear on each row of the ticket list.',
        'why'      => 'The whole desk starts from a layout suited to how you triage - a priority stripe to scan a long queue, initials to keep rows narrow.',
        'done'     => 'An installation-wide default row layout has been saved.',
        'link'     => 'tickets/settings/#row-display',
        'check'    => ['setting', 'inbox_row_display', 'nonempty'],
    ],

    // ─── Merge behaviour ────────────────────────────────────────────────────
    [
        'id'       => 'tickets.merge_reference',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Reference kept when merging',
        'what'     => 'Decides whether merging tickets keeps one of the existing references alive or creates a brand-new ticket holding them all.',
        'why'      => 'Keeping an existing reference means nothing a requester was told becomes a dead end; a new ticket gives a clean slate. It applies to every analyst alike.',
        'done'     => 'The merge reference choice has been saved.',
        'link'     => 'tickets/settings/#merge-behaviour',
        'check'    => ['setting', 'merge_reference_mode', 'nonempty'],
    ],
    [
        'id'       => 'tickets.merge_originals',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Conversations when merging',
        'what'     => 'Decides what happens to the original conversations when tickets merge: moved into the merged ticket, moved and attached as HTML copies, or attached as HTML only.',
        'why'      => 'Moving them keeps everything searchable in one place; HTML copies give a complete record you can hand to someone outside FreeITSM.',
        'done'     => 'The merged conversations choice has been saved.',
        'link'     => 'tickets/settings/#merge-behaviour',
        'check'    => ['setting', 'merge_originals_mode', 'nonempty'],
    ],
    [
        'id'       => 'tickets.merge_ai_summary',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI summary when merging',
        'what'     => 'Adds a note to a merged ticket summarising what each requester asked and what has already been done. Uses the AI provider set on the Reply cleanup tab.',
        'why'      => 'Whoever picks up the merged ticket does not have to read every original conversation to know where things stand.',
        'done'     => 'The merge AI summary has been saved switched on.',
        'link'     => 'tickets/settings/#merge-behaviour',
        'check'    => ['setting', 'merge_ai_summary', 'eq', '1'],
    ],

    // ─── Attachment indexing ────────────────────────────────────────────────
    [
        'id'       => 'tickets.attachment_extract_cron',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Attachment reading on a schedule',
        'what'     => 'The scheduled task cron/attachment_extract.php works through waiting PDFs, older Office files and scans in the background so their text can be searched.',
        'why'      => 'On a busy desk it keeps attachment search up to date without slowing anyone down; without it documents are only read a few at a time while people are working.',
        'done'     => 'The attachment reading task has run at least once.',
        'link'     => 'tickets/settings/#indexing',
        'check'    => ['setting', 'attachment_extract_last_run', 'nonempty'],
    ],
    [
        'id'       => 'tickets.attachment_extract_opportunistic',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Attachment reading while in use',
        'what'     => 'Reads a handful of waiting documents whenever someone is using FreeITSM, as well as or instead of the scheduled task.',
        'why'      => 'Attachment search works on an install with no scheduled tasks at all, a little at a time so nobody waits.',
        'done'     => 'The "read a few whenever FreeITSM is being used" choice has been saved, on or off.',
        'link'     => 'tickets/settings/#indexing',
        'check'    => ['setting', 'attachment_extract_opportunistic', 'nonempty'],
    ],
    [
        'id'       => 'tickets.attachment_search',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Search inside attachments',
        'what'     => 'The text inside ticket attachments - Word, Excel, PowerPoint and, with a document-reading service, PDFs and scans - is read and included in search.',
        'why'      => 'You can find the ticket with the error log or the quote in it, not only the one whose email happened to mention it.',
        'done'     => 'Text has been read from at least one ticket attachment.',
        'link'     => 'tickets/settings/#indexing',
        'check'    => ['rows', 'attachment_text', 'chars > 0'],
    ],

    // ─── Time tracking ──────────────────────────────────────────────────────
    [
        'id'       => 'tickets.time_tracking',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Time recorded on tickets',
        'what'     => 'A time panel on each ticket where analysts log how long they spent, with notes. It can be switched on or off for the installation or per company.',
        'why'      => 'Recorded time shows where effort really goes and is the basis for billing clients or justifying headcount.',
        'done'     => 'Time has been recorded against at least one ticket, or the time panel setting has been saved switched on.',
        'link'     => 'tickets/settings/#time-tracking',
        'check'    => ['any', [
            ['rows', 'ticket_time_entries', 'is_active = 1'],
            ['setting', 'time_tracking_enabled', 'eq', '1'],
        ]],
    ],
    [
        'id'       => 'tickets.time_tracking_api',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Time entries over the API',
        'what'     => 'Decides whether the REST API serves ticket time entries, separately from whether the panel shows on screen.',
        'why'      => 'Lets a billing or timesheet system pull logged time automatically - or deliberately closes that door if nothing should read it.',
        'done'     => 'The REST API time entries setting has been saved, on or off.',
        'link'     => 'tickets/settings/#time-tracking',
        'check'    => ['setting', 'time_tracking_api_enabled', 'nonempty'],
    ],
    [
        'id'       => 'tickets.per_company_ticket_settings',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Per-company ticket fields',
        'what'     => 'On an install serving several companies, the category fields and time recording can be switched on or off for each company rather than for everyone.',
        'why'      => 'A client billed by the hour can record time while another does not see the panel, and each company gets only the fields its service uses.',
        'done'     => 'At least one company has its own setting for categories, resolution codes or time tracking.',
        'link'     => $link,
        'check'    => ['sql', "SELECT COUNT(*) FROM tenant_settings WHERE setting_key IN ('ticket_category_enabled','ticket_closure_category_enabled','ticket_resolution_code_enabled','time_tracking_enabled','time_tracking_api_enabled')"],
    ],
];
