<?php
/**
 * Feature Bingo cards - Tickets: the channels tickets arrive and leave by (mailboxes,
 * WhatsApp, Slack, web chat), email and reply templates, reply cleanup AI, CSAT, the
 * rota, and the working features outside Settings (Users, groups, dashboard,
 * scheduling, snooze, merge/split, links, time). See includes/feature_bingo.php for
 * the format.
 *
 * Tickets -> Settings does not open a tab from the URL, so settings cards link to the
 * page itself.
 */
return [

    // ─── Mailboxes ──────────────────────────────────────────────────────────

    [
        'id'       => 'tickets.mailbox_connected',
        'module'   => 'tickets',
        'tier'     => 'essential',
        'category' => 'getting-started',
        'title'    => 'A service desk mailbox',
        'what'     => 'An email account FreeITSM reads, turning each new message into a ticket and threading replies back onto the ticket they belong to.',
        'why'      => 'Email is how most people ask for help. Without a mailbox every request has to be retyped by an analyst, and replies to your emails go nowhere.',
        'done'     => 'At least one active mailbox exists.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', 'is_active = 1'],
    ],
    [
        'id'       => 'tickets.mailbox_microsoft365',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Microsoft 365 mailbox',
        'what'     => 'A mailbox connected to Exchange Online through Microsoft Graph, with OAuth instead of a stored password.',
        'why'      => 'Microsoft has switched off basic authentication for Exchange Online, so Graph is the supported way to read a Microsoft 365 mailbox, and no password sits in your database.',
        'done'     => 'At least one mailbox uses the Microsoft provider.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "provider = 'microsoft'"],
    ],
    [
        'id'       => 'tickets.mailbox_app_only',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'App-only mailbox sign-in',
        'what'     => 'A Microsoft 365 mailbox that authenticates as the application (client credentials) rather than as a person who signed in once.',
        'why'      => 'A delegated sign-in stops working when that person changes their password, leaves, or has their session revoked. App-only keeps collecting mail regardless of who is still employed.',
        'done'     => 'At least one mailbox uses app-only authentication.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "provider = 'microsoft' AND auth_mode = 'app_only'"],
    ],
    [
        'id'       => 'tickets.mailbox_gmail',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Gmail mailbox',
        'what'     => 'A Google Workspace or Gmail mailbox connected with Google OAuth.',
        'why'      => 'If your organisation runs on Google Workspace, this reads the support inbox directly without an app password or IMAP being switched on.',
        'done'     => 'At least one mailbox uses the Google provider.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "provider = 'google'"],
    ],
    [
        'id'       => 'tickets.mailbox_imap',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'IMAP and SMTP mailbox',
        'what'     => 'A mailbox on any standard mail server, read over IMAP and sent through SMTP with a username and password.',
        'why'      => 'Hosted mail, on-premises servers and smaller providers rarely offer OAuth. IMAP lets FreeITSM work with almost any email account.',
        'done'     => 'At least one mailbox uses the IMAP provider.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "provider = 'imap'"],
    ],
    [
        'id'       => 'tickets.mailbox_separate_smtp_login',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Separate SMTP sending login',
        'what'     => 'Different credentials for sending mail than for reading it, on an IMAP mailbox.',
        'why'      => 'Some providers and relays issue a separate login for SMTP. Without it replies fail to send even though new mail is being collected perfectly.',
        'done'     => 'At least one IMAP mailbox has its own SMTP username.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "provider = 'imap' AND smtp_username IS NOT NULL AND smtp_username <> ''"],
    ],
    [
        'id'       => 'tickets.mailbox_sender_allowlist',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Mailbox sender allowlist',
        'what'     => 'A list of domains or addresses a mailbox will accept; mail from anyone else is not imported.',
        'why'      => 'A public support address attracts spam, marketing and phishing. An allowlist keeps the queue to your own people and customers.',
        'done'     => 'At least one mailbox has an allowlist entry.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'mailbox_email_whitelist'],
    ],
    [
        'id'       => 'tickets.mailbox_default_origin',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Origin per mailbox',
        'what'     => 'The ticket origin stamped on every ticket a mailbox opens, such as Email for the helpdesk address or Monitoring for an alerts address.',
        'why'      => 'Reports on how tickets arrive are only as good as the origin field. Setting it on the mailbox fills it in without anyone having to remember.',
        'done'     => 'At least one mailbox has a default origin set.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', 'default_origin_id IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.mailbox_confidential',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Confidential mailbox',
        'what'     => 'A mailbox, such as HR, whose tickets are marked Confidential the moment they arrive.',
        'why'      => 'Emailed tickets have no department yet, so this is the only thing that can hide a grievance from the requester\'s managers before anyone has read it.',
        'done'     => 'At least one mailbox marks its tickets as confidential.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "default_sensitivity = 'confidential'"],
    ],
    [
        'id'       => 'tickets.mailbox_move_imported',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Keep imported emails',
        'what'     => 'Moves each email to a folder of your choice once it has become a ticket, instead of deleting it.',
        'why'      => 'You keep the original messages in the mailbox as a record, while the inbox itself stays empty and easy to check.',
        'done'     => 'At least one mailbox moves imported emails to a folder.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "imported_action = 'move_to_folder'"],
    ],
    [
        'id'       => 'tickets.mailbox_rejected_handling',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Keep rejected emails',
        'what'     => 'What happens to mail a mailbox refuses to import: moved to Deleted Items or marked as read, rather than deleted outright.',
        'why'      => 'When a genuine request is caught by the allowlist, you can still find it and let the sender in, rather than it being gone for good.',
        'done'     => 'At least one mailbox does something other than delete rejected emails.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "rejected_action IN ('move_to_deleted', 'mark_read')"],
    ],
    [
        'id'       => 'tickets.mailbox_custom_folder',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Read from a specific folder',
        'what'     => 'Points a mailbox at a folder other than the inbox, such as one a mail rule files support requests into.',
        'why'      => 'If the address is also used by people, a rule can sort support mail into its own folder and FreeITSM will only ever read that.',
        'done'     => 'At least one mailbox reads from a folder other than INBOX.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', "email_folder <> 'INBOX'"],
    ],
    [
        'id'       => 'tickets.mailbox_batch_size',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Emails per mailbox check',
        'what'     => 'How many messages a mailbox imports each time it is checked, from 1 to 50.',
        'why'      => 'A busy desk can raise it so a morning backlog clears in one check; a slow server can lower it so each check finishes quickly.',
        'done'     => 'At least one mailbox imports a number other than the default 10 per check.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', 'max_emails_per_check <> 10'],
    ],
    [
        'id'       => 'tickets.mailbox_several',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'More than one mailbox',
        'what'     => 'Several addresses feeding the same service desk, such as support@, hr@ and facilities@.',
        'why'      => 'Each team keeps an address people already know, while every request still lands in one place with one set of statuses and SLAs.',
        'done'     => 'At least two active mailboxes exist.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', 'is_active = 1', 2],
    ],
    [
        'id'       => 'tickets.mailbox_pinned_company',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Mailbox pinned to a company',
        'what'     => 'On an install serving several companies, a mailbox dedicated to one of them: all its mail is filed to that company and replies go out from it.',
        'why'      => 'A client with its own support address sees its own help desk end to end, and none of its mail has to go through triage.',
        'done'     => 'At least one mailbox is assigned to a company.',
        'link'     => 'tickets/settings/#mailboxes',
        'check'    => ['rows', 'target_mailboxes', 'tenant_id IS NOT NULL'],
    ],

    // ─── Email templates ────────────────────────────────────────────────────

    [
        'id'       => 'tickets.template_new_ticket',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Acknowledgement email',
        'what'     => 'An automatic reply to anyone who emails in, confirming the request was received and giving its ticket reference.',
        'why'      => 'Without it people do not know whether their email arrived, so they email again or phone, and you get duplicates.',
        'done'     => 'An active email template exists for the New ticket from email event.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'new_ticket_email' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.template_ticket_assigned',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Ticket assigned email',
        'what'     => 'Tells the requester when their ticket has been picked up and by whom.',
        'why'      => 'Knowing a named person is working on it stops the "any update?" chasers that eat analysts\' time.',
        'done'     => 'An active email template exists for the Ticket assigned event.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'ticket_assigned' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.template_analyst_assigned',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Email the assigned analyst',
        'what'     => 'An email to the analyst themselves when a ticket is assigned to them.',
        'why'      => 'Analysts who are not watching the inbox all day still find out straight away that something new is theirs.',
        'done'     => 'An active email template exists for the Assigned to an analyst event.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'analyst_assigned' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.template_ticket_closed',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Ticket closed email',
        'what'     => 'Tells the requester their ticket has been closed, and how to reopen it if the problem is not fixed.',
        'why'      => 'A ticket closed silently looks like a ticket ignored. The email also gives the requester a clear moment to say it is not fixed.',
        'done'     => 'An active email template exists for the Ticket closed event.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'ticket_closed' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.template_closing_message',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'One-off closing message',
        'what'     => 'The [ticket_closed_message] placeholder in the Ticket closed template, which asks the analyst for a sentence when they close a ticket and puts it in the email.',
        'why'      => '"The spare charger is on your desk" tells the requester what actually happened, while you keep control of the wording around it.',
        'done'     => 'An active Ticket closed template contains [ticket_closed_message].',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'ticket_closed' AND is_active = 1 AND body_template LIKE '%[ticket_closed_message]%'"],
    ],
    [
        'id'       => 'tickets.template_note_shared',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Shared note email',
        'what'     => 'Emails the requester when an analyst adds a note and chooses to share it with them.',
        'why'      => 'Progress updates reach the requester without the analyst writing a separate reply for each one.',
        'done'     => 'An active email template exists for the Note shared with requester event.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'note_shared' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.template_csat_request',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Satisfaction survey email',
        'what'     => 'The email that carries the [csat_link] rating link to the requester.',
        'why'      => 'Surveys need it: with no active survey template the Feedback button refuses and the automatic survey quietly sends nothing.',
        'done'     => 'An active email template exists for the CSAT survey event.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "event_trigger = 'csat_request' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.template_sender_rules',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Templates per sender',
        'what'     => 'Email templates that apply only to particular addresses or domains, with the most specific match winning.',
        'why'      => 'A VIP client or a partner company can get wording, contact details or languages of their own, without changing what everyone else receives.',
        'done'     => 'At least one email template has an address or domain rule.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_template_rules'],
    ],
    [
        'id'       => 'tickets.template_ticket_link',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Ticket link in emails',
        'what'     => 'The [ticket_url] placeholder in an email template, which gives the requester a direct link to their ticket.',
        'why'      => 'One click takes the requester to the ticket in the portal, instead of them replying to ask what is happening.',
        'done'     => 'An active email template contains [ticket_url].',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['rows', 'ticket_email_templates', "is_active = 1 AND (body_template LIKE '%[ticket_url]%' OR subject_template LIKE '%[ticket_url]%')"],
    ],
    [
        'id'       => 'tickets.public_base_url',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Public web address',
        'what'     => 'The address people use to reach FreeITSM, used to build [ticket_url] and every other link FreeITSM emails out.',
        'why'      => 'Mail collected in the background has no browser request to work the address out from, so without this its links come out with no site name and do not work.',
        'done'     => 'A public web address has been saved.',
        'link'     => 'tickets/settings/#email-templates',
        'check'    => ['setting', 'public_base_url', 'nonempty'],
    ],

    // ─── Reply templates and signatures ────────────────────────────────────

    [
        'id'       => 'tickets.reply_templates_shared',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'productivity',
        'title'    => 'Shared reply templates',
        'what'     => 'Canned responses the whole team can drop into a reply, with merge codes such as [requester_first_name] filled in as they are inserted.',
        'why'      => 'The same few answers get typed dozens of times a day. Templates save that time and keep the answers consistent and correct.',
        'done'     => 'At least one active shared reply template exists.',
        'link'     => 'tickets/settings/#reply-templates',
        'check'    => ['rows', 'ticket_reply_templates', 'analyst_id IS NULL AND is_active = 1'],
    ],
    [
        'id'       => 'tickets.reply_templates_personal',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Personal reply templates',
        'what'     => 'An analyst\'s own private templates, saved from a draft with Save draft as template.',
        'why'      => 'Each analyst can keep the replies only they send, such as the steps for a system they look after, without cluttering the team list.',
        'done'     => 'At least one analyst has saved a private reply template.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_reply_templates', 'analyst_id IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.email_signatures',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Email signatures',
        'what'     => 'An analyst\'s signature, added to their replies automatically. Each analyst can keep several and pick a default.',
        'why'      => 'Replies go out with a name, role and contact details every time, without anyone typing them or pasting them from somewhere else.',
        'done'     => 'At least one analyst has a signature.',
        'link'     => 'system/preferences/',
        'check'    => ['rows', 'analyst_signatures'],
    ],

    // ─── Reply cleanup AI ───────────────────────────────────────────────────

    [
        'id'       => 'tickets.reply_cleanup_ai',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Reply cleanup AI',
        'what'     => 'An AI provider and key for the Cleanup button, which turns a rough draft or bullet points into a properly written reply. WhatsApp reply suggestions use it too.',
        'why'      => 'Analysts write replies faster and they read better, and the prompt is locked down so it does not invent technical details. Its own key shows its cost as a separate line.',
        'done'     => 'An API key has been saved for reply cleanup.',
        'link'     => 'tickets/settings/#reply-cleanup',
        'check'    => ['setting', 'tickets_reply_cleanup_api_key', 'nonempty'],
    ],
    [
        'id'       => 'tickets.reply_cleanup_tone',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Reply cleanup tone',
        'what'     => 'Whether cleaned-up replies come out Friendly, Formal or Brief.',
        'why'      => 'Replies should match your house style. A formal organisation should not be sending chatty emails, and a busy desk may prefer brief ones.',
        'done'     => 'A tone has been saved for reply cleanup (any choice counts).',
        'link'     => 'tickets/settings/#reply-cleanup',
        'check'    => ['setting', 'tickets_reply_cleanup_tone', 'nonempty'],
    ],
    [
        'id'       => 'tickets.reply_cleanup_instructions',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Reply cleanup instructions',
        'what'     => 'Your own instructions added to the reply cleanup prompt, such as the company name, a sign-off, or British spelling.',
        'why'      => 'The AI gets the details of your organisation right every time, instead of analysts correcting the same things after each cleanup.',
        'done'     => 'Custom instructions have been saved for reply cleanup.',
        'link'     => 'tickets/settings/#reply-cleanup',
        'check'    => ['setting', 'tickets_reply_cleanup_custom_instructions', 'nonempty'],
    ],

    // ─── Customer satisfaction (CSAT) ───────────────────────────────────────

    [
        'id'       => 'tickets.csat_enabled',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'customer',
        'title'    => 'Satisfaction surveys',
        'what'     => 'A 1 to 5 rating survey emailed to the requester, answered on a page with no sign-in, with results by analyst under Tickets -> CSAT.',
        'why'      => 'Closed tickets only tell you work was done. Ratings and comments tell you whether people were actually helped, and where to improve.',
        'done'     => 'The survey mode is set to automatic or manual.',
        'link'     => 'tickets/settings/#csat',
        'check'    => ['setting', 'csat_mode', 'in', ['auto', 'manual']],
    ],
    [
        'id'       => 'tickets.csat_auto',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Survey on every close',
        'what'     => 'Sends the survey automatically whenever a ticket moves to a closed status, with no analyst involved.',
        'why'      => 'You hear from everyone, not just the tickets an analyst chose to ask about, which gives you a fair picture.',
        'done'     => 'The survey mode is set to automatic.',
        'link'     => 'tickets/settings/#csat',
        'check'    => ['setting', 'csat_mode', 'eq', 'auto'],
    ],
    [
        'id'       => 'tickets.csat_delay',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Survey delay',
        'what'     => 'Waits a set number of minutes after a ticket closes before sending the survey.',
        'why'      => 'The requester has time to check the fix actually held before being asked to rate it, so the score reflects the outcome.',
        'done'     => 'A survey delay of more than zero minutes has been saved.',
        'link'     => 'tickets/settings/#csat',
        'check'    => ['all', [
            ['setting', 'csat_delay_minutes', 'nonempty'],
            ['setting', 'csat_delay_minutes', 'neq', '0'],
        ]],
    ],
    [
        'id'       => 'tickets.csat_one_per_ticket',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'One survey per ticket',
        'what'     => 'Decides whether a ticket that is reopened and closed again gets another survey automatically.',
        'why'      => 'A flaky ticket that keeps cycling should not keep asking the same person to rate it, unless you want a score for every close.',
        'done'     => 'The one-survey-per-ticket choice has been saved (on or off).',
        'link'     => 'tickets/settings/#csat',
        'check'    => ['setting', 'csat_one_per_ticket', 'nonempty'],
    ],
    [
        'id'       => 'tickets.csat_scale',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Survey style',
        'what'     => 'Whether the survey page shows five stars or five faces. Both record the same 1 to 5 score.',
        'why'      => 'Pick the style your requesters will respond to. Faces can feel friendlier; stars are familiar and more formal.',
        'done'     => 'A survey style has been saved (stars or faces).',
        'link'     => 'tickets/settings/#csat',
        'check'    => ['setting', 'csat_scale', 'nonempty'],
    ],
    [
        'id'       => 'tickets.csat_responses',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Survey responses coming in',
        'what'     => 'Requesters answering the survey, with ratings and comments feeding the CSAT page and its per-analyst table.',
        'why'      => 'This is the proof the surveys are reaching people and the links work end to end.',
        'done'     => 'At least one survey has been answered.',
        'link'     => 'tickets/csat/',
        'check'    => ['rows', 'ticket_csat_responses', 'responded_datetime IS NOT NULL'],
    ],

    // ─── Rota ───────────────────────────────────────────────────────────────

    [
        'id'       => 'tickets.rota_shifts',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Rota shifts',
        'what'     => 'The working patterns, such as Early, Late and On-call, that analysts are given on the staff rota.',
        'why'      => 'Shifts have to exist before the rota can be built. They let everyone see who covers which hours.',
        'done'     => 'At least one active rota shift exists.',
        'link'     => 'tickets/settings/#rota',
        'check'    => ['rows', 'ticket_rota_shifts', 'is_active = 1'],
    ],
    [
        'id'       => 'tickets.rota_locations',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Your own rota locations',
        'what'     => 'Where analysts work on a given day, shown as a coloured badge on the rota. Office and WFH are provided; add your own sites.',
        'why'      => 'With several offices, knowing who is at which site on a given day decides who can walk over to a broken printer.',
        'done'     => 'A rota location other than the provided Office and WFH exists.',
        'link'     => 'tickets/settings/#rota-locations',
        'check'    => ['rows', 'rota_locations', "name NOT IN ('Office', 'WFH')"],
    ],
    [
        'id'       => 'tickets.rota_built',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Staff rota',
        'what'     => 'The weekly grid of who is working which shift, and where, planned ahead.',
        'why'      => 'Everyone can see who is in and when, so gaps in cover show up before they hurt response times.',
        'done'     => 'At least one rota entry exists.',
        'link'     => 'tickets/rota.php',
        'check'    => ['rows', 'ticket_rota_entries'],
    ],
    [
        'id'       => 'tickets.rota_on_call',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'On-call on the rota',
        'what'     => 'Rota entries marked as on call.',
        'why'      => 'When something breaks out of hours, anyone can see at a glance who to ring.',
        'done'     => 'At least one rota entry is marked on call.',
        'link'     => 'tickets/rota.php',
        'check'    => ['rows', 'ticket_rota_entries', 'is_on_call = 1'],
    ],
    [
        'id'       => 'tickets.rota_weekends',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Weekends on the rota',
        'what'     => 'Shows Saturday and Sunday on the rota grid. It is off by default.',
        'why'      => 'A desk with weekend cover or weekend on-call needs to plan those days in the same place as the rest of the week.',
        'done'     => 'Include weekends on the rota is switched on.',
        'link'     => 'tickets/settings/#rota',
        'check'    => ['setting', 'rota_include_weekends', 'eq', '1'],
    ],

    // ─── Messaging channels (WhatsApp, Slack) ──────────────────────────────

    [
        'id'       => 'tickets.whatsapp_channel',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'WhatsApp channel',
        'what'     => 'A WhatsApp number, through Twilio or Meta, where each conversation becomes a ticket that analysts reply to from the inbox.',
        'why'      => 'People who would never email the service desk, such as field staff or customers on the move, can message it the way they message everyone else.',
        'done'     => 'At least one active WhatsApp channel exists.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['rows', 'messaging_channels', "channel_type = 'whatsapp' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.whatsapp_receiving',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'WhatsApp messages arriving',
        'what'     => 'The provider\'s webhook reaching this install, so inbound WhatsApp messages actually turn into tickets.',
        'why'      => 'A channel can be saved and still receive nothing if the webhook URL was never pasted into Twilio or Meta. This proves the whole path works.',
        'done'     => 'At least one WhatsApp channel has received a message.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['rows', 'messaging_channels', "channel_type = 'whatsapp' AND last_inbound_datetime IS NOT NULL"],
    ],
    [
        'id'       => 'tickets.whatsapp_relay',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'WhatsApp through a relay',
        'what'     => 'Receives WhatsApp messages from a hosted relay that forwards them here, instead of the provider calling this install directly.',
        'why'      => 'An install that is not reachable from the internet can still take WhatsApp messages, without opening a port to it.',
        'done'     => 'At least one messaging channel uses relay ingress.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['rows', 'messaging_channels', "ingress_mode = 'relay'"],
    ],
    // Telegram (PR #159, turbay-a).
    [
        'id'       => 'tickets.telegram_channel',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Telegram channel',
        'what'     => 'A Telegram bot where each conversation becomes a ticket that analysts reply to from the inbox - with no 24-hour reply window, and the bot speaking each person\'s own language.',
        'why'      => 'In much of the world Telegram, not WhatsApp, is how people message. A bot is free and live the moment @BotFather creates it.',
        'done'     => 'At least one active Telegram channel exists.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['rows', 'messaging_channels', "channel_type = 'telegram' AND is_active = 1"],
    ],
    [
        'id'       => 'tickets.telegram_receiving',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Telegram messages arriving',
        'what'     => 'Telegram delivering this bot\'s messages to this install, so they actually turn into tickets.',
        'why'      => 'A bot can be saved and still receive nothing until Connect has told Telegram where to deliver. This proves the whole path works.',
        'done'     => 'At least one Telegram channel has received a message.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['rows', 'messaging_channels', "channel_type = 'telegram' AND last_inbound_datetime IS NOT NULL"],
    ],
    [
        'id'       => 'tickets.channel_attachments',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Files sent over chat',
        'what'     => 'Attach in the chat reply box sends a picture or document straight into the customer\'s Telegram or WhatsApp conversation.',
        'why'      => 'A screenshot of where to click, or the form they need, answers in one message what would otherwise take five.',
        'done'     => 'At least one file has been sent to a customer over Telegram or WhatsApp.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'emails', "direction = 'Outbound' AND channel IN ('telegram', 'whatsapp') AND has_attachments = 1"],
    ],
    [
        'id'       => 'tickets.messaging_templates',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'WhatsApp message templates',
        'what'     => 'Templates approved by Meta or Twilio that an analyst can send once the 24-hour reply window has closed.',
        'why'      => 'WhatsApp only allows free text within 24 hours of the customer\'s last message. Without an approved template you cannot reply to a slow ticket at all.',
        'done'     => 'At least one active messaging template exists.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['rows', 'messaging_templates', 'is_active = 1'],
    ],
    [
        'id'       => 'tickets.messaging_base_url',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Messaging webhook address',
        'what'     => 'The public address WhatsApp providers use to reach this install, which makes the webhook URLs shown copy-and-paste ready.',
        'why'      => 'Webhook URLs built from the address you happen to be browsing from, such as localhost, will not work from the internet.',
        'done'     => 'A messaging public address has been saved.',
        'link'     => 'tickets/settings/#messaging',
        'check'    => ['setting', 'messaging_public_base_url', 'nonempty'],
    ],
    [
        'id'       => 'tickets.slack_channel',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Slack channel',
        'what'     => 'A Slack workspace connected as a ticket channel, so people raise and follow tickets from Slack.',
        'why'      => 'In organisations that live in Slack, asking for help there is easier than switching to email or a portal.',
        'done'     => 'At least one active Slack channel exists.',
        'link'     => 'system/integrations/slack.php',
        'check'    => ['rows', 'messaging_channels', "provider = 'slack' AND is_active = 1"],
    ],

    // ─── Web chat ───────────────────────────────────────────────────────────

    [
        'id'       => 'tickets.webchat_widget',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Website chat widget',
        'what'     => 'A chat window you embed on any website with a snippet. A visitor\'s message becomes a ticket that analysts answer from the inbox.',
        'why'      => 'Visitors get help while they are on your site, without finding an email address or creating an account.',
        'done'     => 'At least one web chat widget exists.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets'],
    ],
    [
        'id'       => 'tickets.webchat_origins',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Web chat allowed websites',
        'what'     => 'The websites a chat widget may appear on. Left blank, any site can show it.',
        'why'      => 'The widget key is public in your page source. Restricting the sites stops someone else putting your chat on theirs and filling your queue.',
        'done'     => 'At least one widget has its allowed websites set.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', "allowed_origins IS NOT NULL AND TRIM(allowed_origins) <> ''"],
    ],
    [
        'id'       => 'tickets.webchat_live',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Web chat in use',
        'what'     => 'Visitors actually starting conversations through a chat widget.',
        'why'      => 'This shows the snippet is on the live site and working, not just saved here.',
        'done'     => 'At least one web chat conversation has taken place.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_conversations'],
    ],
    [
        'id'       => 'tickets.webchat_office_hours',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Web chat office hours',
        'what'     => 'A business-hours calendar for a widget. Outside those hours it shows your offline message and takes the enquiry as a ticket to answer later.',
        'why'      => 'Visitors are not left waiting in a live chat at midnight for someone who has gone home.',
        'done'     => 'At least one widget has an office-hours calendar.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', 'business_calendar_id IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.webchat_offline_message',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Web chat offline message',
        'what'     => 'Your own wording for what the widget says when nobody is available.',
        'why'      => 'You can set expectations in your own words, such as when someone will reply and where else to go if it is urgent.',
        'done'     => 'At least one widget has an offline message.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', "offline_message IS NOT NULL AND offline_message <> ''"],
    ],
    [
        'id'       => 'tickets.webchat_branding',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Branded chat window',
        'what'     => 'Your own accent colour, launcher text and greeting on a chat widget.',
        'why'      => 'A chat window in your colours and your voice looks like part of your site, not something bolted on.',
        'done'     => 'At least one widget has an accent colour, launcher text or greeting set.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', "(accent_colour IS NOT NULL AND accent_colour <> '') OR (launcher_text IS NOT NULL AND launcher_text <> '') OR (greeting IS NOT NULL AND greeting <> '')"],
    ],
    [
        'id'       => 'tickets.webchat_email_when_away',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Email chat replies to leavers',
        'what'     => 'If an analyst replies after the visitor has closed the chat, the reply is sent to the email address they gave.',
        'why'      => 'Visitors rarely wait. Without this, an answer written ten minutes later is never seen.',
        'done'     => 'At least one widget emails replies to visitors who have left.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', 'email_when_away = 1'],
    ],
    [
        'id'       => 'tickets.webchat_ai',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'AI answers in web chat',
        'what'     => 'The chat widget drafts an answer from your published Knowledge articles before a person is involved, using the Knowledge AI provider.',
        'why'      => 'Common questions are answered instantly at any hour, and analysts see what the visitor was already told.',
        'done'     => 'At least one widget has AI answers switched on.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', 'ai_enabled = 1'],
    ],
    [
        'id'       => 'tickets.webchat_ai_deflect',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Web chat deflection',
        'what'     => 'AI answers mode that only raises a ticket when the visitor asks for a person or chooses to email, rather than for every chat.',
        'why'      => 'Questions the Knowledge base already answers never reach the queue, which frees analysts for the problems that need them.',
        'done'     => 'At least one widget uses AI answers in deflect mode.',
        'link'     => 'tickets/settings/#webchat',
        'check'    => ['rows', 'webchat_widgets', "ai_enabled = 1 AND ai_mode = 'deflect'"],
    ],

    // ─── Tickets -> Users ───────────────────────────────────────────────────

    [
        'id'       => 'tickets.people_groups',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Groups of people',
        'what'     => 'Named groups of analysts and portal users, made once under Tickets -> Users -> Groups and used across FreeITSM.',
        'why'      => 'Give a group access to a knowledge folder or assign it training in one step, instead of building the same list of names in each place.',
        'done'     => 'At least one active group exists.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'knowledge_user_groups', 'is_active = 1'],
    ],
    [
        'id'       => 'tickets.people_group_expiry',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Temporary group membership',
        'what'     => 'A group membership with an end date, after which the person drops out of the group by themselves.',
        'why'      => 'Contractors on site for a fortnight lose their access when they leave, without anyone having to remember to remove them.',
        'done'     => 'At least one group membership has an end date.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'knowledge_user_group_members', 'expires_at IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.manager_lines',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Management lines',
        'what'     => 'Who a portal manager may see the tickets of: everyone, particular people, groups, departments or their reporting line, with exclusions. Set from Manager access beside a person.',
        'why'      => 'Team leads can follow their people\'s requests in the portal without asking the service desk, and exclusions keep sensitive people out of view.',
        'done'     => 'At least one management line exists.',
        'link'     => 'tickets/users.php',
        'check'    => ['rows', 'manager_grants'],
    ],
    [
        'id'       => 'tickets.address_book_add',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Add people to an address book',
        'what'     => 'Lets analysts add someone who emailed in to a CardDAV address book from Tickets -> Users, creating their contact and linking them.',
        'why'      => 'New contacts end up in your shared address book, and in the next import, without anyone typing them in twice.',
        'done'     => 'At least one CardDAV address book allows analysts to add people.',
        'link'     => 'system/sso/',
        'check'    => ['rows', 'auth_providers', 'carddav_allow_create = 1'],
    ],

    // ─── Working features ───────────────────────────────────────────────────

    [
        'id'       => 'tickets.dashboard_built',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Ticket dashboard',
        'what'     => 'Chart widgets on the Tickets dashboard showing volumes, status, priority, analyst workload and trends. Each analyst arranges their own.',
        'why'      => 'You spot a growing backlog or a busy Monday from a glance, rather than finding out from complaints.',
        'done'     => 'At least one analyst has a widget on their ticket dashboard.',
        'link'     => 'tickets/dashboard/',
        'check'    => ['rows', 'analyst_ticket_dashboard_widgets', 'is_demo = 0'],
    ],
    [
        'id'       => 'tickets.dashboard_custom_widget',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Your own dashboard widget',
        'what'     => 'A widget you built in the dashboard library, choosing the chart type, what to count, date range, departments and grouping.',
        'why'      => 'The provided widgets cover the common questions. Your own answer the ones specific to your desk.',
        'done'     => 'A ticket dashboard widget exists beyond the 15 provided.',
        'link'     => 'tickets/dashboard/library.php',
        'check'    => ['rows', 'ticket_dashboard_widgets', 'id > 15 AND is_demo = 0'],
    ],
    [
        'id'       => 'tickets.schedule_work',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Scheduled ticket work',
        'what'     => 'Gives a ticket a time and length with Schedule work, so it appears on the ticket calendar.',
        'why'      => 'Visits, installs and changes booked for a set time are planned on a calendar instead of being remembered.',
        'done'     => 'At least one ticket has scheduled work.',
        'link'     => 'tickets/calendar.php',
        'check'    => ['rows', 'tickets', 'work_start_datetime IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tickets.snooze',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Snoozed tickets',
        'what'     => 'Takes a ticket out of the working queue until a date and time you choose, when it comes back by itself.',
        'why'      => 'A ticket waiting on a delivery next Tuesday stops cluttering the list every day until then, and cannot be forgotten.',
        'done'     => 'At least one ticket has been snoozed.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'tickets', 'snoozed_at IS NOT NULL AND is_demo = 0'],
    ],
    [
        'id'       => 'tickets.merge_used',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Merging duplicates',
        'what'     => 'Brings duplicate tickets together into one, keeping the old references working and able to be undone.',
        'why'      => 'When five people report the same outage, one analyst works one ticket and everyone still hears back.',
        'done'     => 'At least one merge has been done.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_merges'],
    ],
    [
        'id'       => 'tickets.split_used',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Splitting a ticket',
        'what'     => 'Moves a message, and optionally everything after it, onto a new ticket when someone raises a second, unrelated problem.',
        'why'      => 'Each problem gets its own ticket, owner and SLA, instead of the second one being lost at the bottom of the first.',
        'done'     => 'At least one split has been done.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_splits'],
    ],
    [
        'id'       => 'tickets.time_recorded',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Time recorded on tickets',
        'what'     => 'Minutes spent logged against a ticket, from the reading pane or by right-clicking the ticket.',
        'why'      => 'You can see where the desk\'s time actually goes, and bill or recharge it where that matters.',
        'done'     => 'At least one time entry exists.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_time_entries', 'is_active = 1'],
    ],
    [
        'id'       => 'tickets.ticket_tasks',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Tasks from a ticket',
        'what'     => 'Tasks created from a ticket and linked to it, such as ordering a part or a follow-up visit.',
        'why'      => 'The pieces of work behind a ticket are tracked and assigned properly, and the ticket shows what is still outstanding.',
        'done'     => 'At least one task is linked to a ticket.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'tasks', 'ticket_id IS NOT NULL'],
    ],
    [
        'id'       => 'tickets.asset_links',
        'module'   => 'tickets',
        'tier'     => 'recommended',
        'category' => 'organisation',
        'title'    => 'Assets on tickets',
        'what'     => 'Links a ticket to the device it is about.',
        'why'      => 'A device\'s history of faults builds up on its own, so a laptop on its fifth repair is easy to spot and replace.',
        'done'     => 'At least one ticket is linked to an asset.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_assets'],
    ],
    [
        'id'       => 'tickets.cmdb_links',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'CMDB objects on tickets',
        'what'     => 'Links a ticket to the services and configuration items it affects.',
        'why'      => 'You can see which services cause the most tickets, and what else was affected when something failed.',
        'done'     => 'At least one ticket is linked to a CMDB object.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_cmdb_objects'],
    ],
    [
        'id'       => 'tickets.related_tickets',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Linked tickets',
        'what'     => 'Links between tickets that are related to each other, without merging them.',
        'why'      => 'Whoever opens one ticket can see the others connected to it, and does not solve the same thing twice.',
        'done'     => 'At least one ticket link exists.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'ticket_links'],
    ],
    [
        'id'       => 'tickets.tracker_links',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Tickets linked to a tracker',
        'what'     => 'A ticket linked to an issue in an external tracker such as Jira, with its status and comments kept in step.',
        'why'      => 'When a fix needs the developers, the service desk sees the issue progress on the ticket without asking for updates.',
        'done'     => 'At least one ticket is linked to an external issue.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'integration_links', "entity_type = 'ticket'"],
    ],
    [
        'id'       => 'tickets.documents',
        'module'   => 'tickets',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'Documents on tickets',
        'what'     => 'Documents, either held in FreeITSM or links to another document system, attached to a ticket.',
        'why'      => 'Quotes, approvals and procedures sit on the ticket they belong to, not in someone\'s inbox.',
        'done'     => 'At least one document is attached to a ticket.',
        'link'     => 'tickets/',
        'check'    => ['rows', 'document_links', "parent_type = 'ticket'"],
    ],
];
