<?php
/** Feature Bingo cards - War Room: trying it out, channels, message retention, Warbot and the situation report. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'war-room.tried_out',
        'module'   => 'war-room',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Try the war room',
        'what'     => 'A chat that runs on your own FreeITSM server - channels, direct messages, mentions, search and attachments - for when Teams, Slack or the internet are down.',
        'why'      => 'It is the tool you open on the day everything else has failed. Posting in it once while things are calm means nobody is learning their way around mid-outage.',
        'done'     => 'At least one message has been posted in the war room by an analyst.',
        'link'     => 'war-room/',
        'check'    => ['rows', 'warroom_messages', 'is_bot = 0 AND analyst_id IS NOT NULL'],
    ],
    [
        'id'       => 'war-room.team_channels',
        'module'   => 'war-room',
        'tier'     => 'extra',
        'category' => 'organisation',
        'title'    => 'A channel per team',
        'what'     => 'Every team set up under System -> Teams gets its own war room channel automatically, visible to that team\'s members.',
        'why'      => 'There is nothing to create or manage: change the team and the channel follows. It gives each team a room of its own on the day it matters, alongside the all-hands channel.',
        'done'     => 'At least one team channel exists (one is created for each team).',
        'link'     => 'system/teams/',
        'check'    => ['rows', 'warroom_channels', "kind = 'team'"],
    ],
    [
        'id'       => 'war-room.custom_channel',
        'module'   => 'war-room',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Incident channels',
        'what'     => 'A channel any analyst can create, with a name and a topic, for one incident or piece of work, archived when it is over.',
        'why'      => 'One room per incident keeps the conversation about the database outage out of the conversation about the network one, and leaves a readable record of each afterwards.',
        'done'     => 'At least one channel has been created by an analyst.',
        'link'     => 'war-room/',
        'check'    => ['rows', 'warroom_channels', "kind = 'custom'"],
    ],
    [
        'id'       => 'war-room.private_channel',
        'module'   => 'war-room',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Private channels',
        'what'     => 'A channel marked Private is seen only by the analysts invited to it.',
        'why'      => 'Some incidents - a security breach, a disciplinary matter - should not be discussed in front of the whole desk. A private channel keeps the circle small without leaving FreeITSM.',
        'done'     => 'At least one private channel exists.',
        'link'     => 'war-room/',
        'check'    => ['rows', 'warroom_channels', "kind = 'custom' AND is_private = 1"],
    ],
    [
        'id'       => 'war-room.channel_topic',
        'module'   => 'war-room',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Channel topics',
        'what'     => 'A one-line topic on a channel saying what it is for, shown at the top of the conversation.',
        'why'      => 'Somebody arriving halfway through an incident reads the topic before anything else. A clear one saves the room from explaining itself again.',
        'done'     => 'At least one channel has a topic set.',
        'link'     => 'war-room/',
        'check'    => ['rows', 'warroom_channels', "topic IS NOT NULL AND topic <> ''"],
    ],
    [
        'id'       => 'war-room.retention',
        'module'   => 'war-room',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'Message retention',
        'what'     => 'How long war room messages are kept, from a week to forever. Old messages, and the files attached to them, are removed as new ones arrive.',
        'why'      => 'Chat during an incident is a record, and your data retention policy should decide how long it lives - not the fact that nobody ever chose. Keep forever is a valid answer when it is a decision.',
        'done'     => 'A retention period has been saved (Keep forever counts).',
        'link'     => 'war-room/settings/',
        'check'    => ['setting', 'warroom_retention_days', 'nonempty'],
    ],
    [
        'id'       => 'war-room.ai',
        'module'   => 'war-room',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Situation report and Warbot AI',
        'what'     => 'An AI provider and key that power the situation report, which drafts an update for the business from the chat, and Warbot\'s plain-English questions such as "how many P1s are open?".',
        'why'      => 'The person who has to brief the business cannot read four hundred messages first. Warbot\'s commands work without it, so it only adds to what the room can do.',
        'done'     => 'An API key has been saved for the war room AI.',
        'link'     => 'war-room/settings/',
        'check'    => ['setting', 'warroom_ai_api_key', 'nonempty'],
    ],
    [
        'id'       => 'war-room.warbot',
        'module'   => 'war-room',
        'tier'     => 'extra',
        'category' => 'productivity',
        'title'    => 'Ask Warbot',
        'what'     => 'A bot in the room that answers commands such as /p1, /status, /changes, /oncall and /known from your own database, so they work even when the internet does not.',
        'why'      => '"What changed recently?" and "who is on call?" are the first questions in most incidents. Warbot answers them in the room, where everybody can see the answer.',
        'done'     => 'Warbot has answered at least once in the war room.',
        'link'     => 'war-room/help.php',
        'check'    => ['rows', 'warroom_messages', 'is_bot = 1'],
    ],
];
