<?php
/** Feature Bingo cards - Watchtower: which cards appear, what each count includes, and the paused-too-long threshold. See includes/feature_bingo.php for the format. */
return [
    [
        'id'       => 'watchtower.cards',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'look',
        'title'    => 'Choose Watchtower cards',
        'what'     => 'Watchtower shows a card for every module by default. Any of them - Contracts, Software, Knowledge and so on - can be turned off for the whole install.',
        'why'      => 'An attention board is only useful if everything on it is something your team acts on. Hiding the cards nobody watches makes the red ones that matter harder to miss.',
        'done'     => 'At least one Watchtower card has been turned off.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key LIKE 'card.%' AND is_visible = 0"],
    ],
    [
        'id'       => 'watchtower.ticket_statuses',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Ticket statuses on Watchtower',
        'what'     => 'Which open ticket statuses the Tickets card lists, one figure each plus a total. Left alone it counts every open status, including ones added later.',
        'why'      => 'If a status such as "Awaiting customer" is not something the desk can act on, narrowing the list keeps the morning glance on the work that is actually yours.',
        'done'     => 'The ticket statuses shown on Watchtower have been narrowed to a chosen set.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'tickets.by_status' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.high_priority',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'What counts as high priority',
        'what'     => 'Which ticket priorities make up the red "high priority tickets" line. Left alone, it means any priority ranked above your default one.',
        'why'      => 'That line is the figure people read first each morning. Choosing exactly which priorities it covers makes it mean what your escalation policy says it means.',
        'done'     => 'The priorities counted as high priority have been chosen explicitly.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'tickets.high_priority' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.service_levels',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Service impacts on Watchtower',
        'what'     => 'Which impact levels put a service on the Service Status card. Left alone, anything other than your healthy level does.',
        'why'      => 'Planned maintenance is happening, but it is not a problem to chase. Unticking it keeps it off an attention board without pretending it is not there.',
        'done'     => 'The impact levels shown on Watchtower have been narrowed to a chosen set.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'service.levels' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.service_serious',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Which service problems show red',
        'what'     => 'Which impact levels turn the Service Status light red rather than amber. Left alone, it follows the levels that count towards downtime.',
        'why'      => 'It is kept separate from the downtime setting on purpose, so you can make a dashboard louder or quieter without distorting your uptime figures to do it.',
        'done'     => 'The impact levels that turn the light red have been chosen explicitly.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'service.serious' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.change_statuses',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Change statuses on Watchtower',
        'what'     => 'Which open change statuses the Changes card lists, one figure each plus a total. The scheduled, awaiting approval and in progress lines are worked out separately.',
        'why'      => 'A pile of Draft changes nobody has submitted may not be what the morning review needs to see. Narrowing it keeps the card on changes that are moving.',
        'done'     => 'The change statuses shown on Watchtower have been narrowed to a chosen set.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'changes.by_status' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.task_statuses',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'insight',
        'title'    => 'Task statuses on Watchtower',
        'what'     => 'Which open task statuses the Tasks card lists, one figure each plus a total.',
        'why'      => 'Backlog and someday tasks can swamp a card meant to show what needs attention now. Choosing the statuses keeps the figure honest.',
        'done'     => 'The task statuses shown on Watchtower have been narrowed to a chosen set.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'tasks.by_status' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.morning_check_attention',
        'module'   => 'watchtower',
        'tier'     => 'recommended',
        'category' => 'insight',
        'title'    => 'Which morning checks need attention',
        'what'     => 'Which of your morning-check statuses count as a problem on the Morning Checks card.',
        'why'      => 'Nothing else in FreeITSM records which of your statuses is a pass. Until you say, the card treats only the first status as good and can only report that checks were done, not that they passed.',
        'done'     => 'The morning-check statuses that need attention have been chosen.',
        'link'     => 'watchtower/settings/',
        'check'    => ['rows', 'watchtower_items', "analyst_id = 0 AND item_key = 'mc.attention' AND is_customised = 1"],
    ],
    [
        'id'       => 'watchtower.paused_threshold',
        'module'   => 'watchtower',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Paused too long threshold',
        'what'     => 'How many hours a ticket may sit in a status that stops the SLA clock, such as On Hold, before Watchtower flags it. The default is 24.',
        'why'      => 'Pausing the clock is legitimate; parking tickets to dodge an SLA is not. A threshold that fits how long your waits really are catches the second without nagging about the first.',
        'done'     => 'The threshold has been changed from its default of 24 hours.',
        'link'     => 'watchtower/settings/',
        'check'    => ['setting', 'watchtower_paused_too_long_hours', 'neq', '24'],
    ],
];
