<?php
/**
 * Feature Bingo cards - Workflows: having workflows, the trigger families, the
 * action types, webhook formats, scheduled triggers and the module's settings.
 * See includes/feature_bingo.php for the format.
 *
 * workflows.trigger_event is one event name; workflows.actions is JSON written by
 * json_encode() (api/workflow/save.php, create_from_template.php, api/v1), so an
 * action appears as "type":"send_email" with no spaces. Only ACTIVE workflows
 * that the demo importer did not create count.
 */

$live = 'is_active = 1 AND is_demo = 0';
$trigger = function (string $where) use ($live): array {
    return ['rows', 'workflows', "$live AND ($where)"];
};
$action = function (string $type) use ($live): array {
    return ['rows', 'workflows', "$live AND actions LIKE '%\"type\":\"$type\"%'"];
};
$preset = function (string $key) use ($live): array {
    return ['rows', 'workflows', "$live AND actions LIKE '%\"type\":\"send_webhook\"%' AND actions LIKE '%\"preset\":\"$key\"%'"];
};

return [
    // ── The module itself ───────────────────────────────────────────────────
    [
        'id'       => 'workflow.first_workflow',
        'module'   => 'workflow',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Your first workflow',
        'what'     => 'An automation rule: a trigger (something happens), optional conditions, and one or more actions that run in order. Ready-made templates are there to start from.',
        'why'      => 'The jobs you do by hand after a ticket arrives - assigning, notifying, escalating, telling another system - happen the same way every time, without anyone remembering.',
        'done'     => 'At least one workflow is switched on.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', $live],
    ],
    [
        'id'       => 'workflow.conditions',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflow conditions',
        'what'     => 'Filters on a workflow - priority is P1, the requester\'s company is X, the subject contains "outage" - so it only acts on the events you care about.',
        'why'      => 'A rule that fires on every ticket is noise. Conditions let one workflow page the on-call engineer for P1s only, and leave the rest alone.',
        'done'     => 'At least one active workflow has a condition.',
        'link'     => 'workflow/',
        'check'    => $trigger("conditions IS NOT NULL AND conditions NOT IN ('', '[]', 'null')"),
    ],
    [
        'id'       => 'workflow.ai_coauthor',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'ai',
        'title'    => 'Workflow AI co-author',
        'what'     => 'An AI provider for the Workflows module: describe the rule you want in a sentence and it is laid out on the canvas, ready to adjust.',
        'why'      => 'Building a rule from a plain description is quicker than hunting for the right trigger and field, especially for people new to the editor.',
        'done'     => 'An API key is saved for Workflow AI.',
        'link'     => 'workflow/settings/',
        'check'    => ['setting', 'workflow_ai_api_key', 'nonempty'],
    ],
    [
        'id'       => 'workflow.custom_message_format',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Your own webhook message format',
        'what'     => 'A webhook message format added alongside the built-in Slack, Teams and Discord ones - a JSON body with a {{message}} slot for Google Chat, Mattermost, ntfy or anything else.',
        'why'      => 'Workflows can post to the chat tool your team actually uses, without waiting for a release that adds it.',
        'done'     => 'At least one message format you added yourself exists.',
        'link'     => 'workflow/settings/',
        'check'    => ['rows', 'webhook_message_formats', 'is_builtin = 0'],
    ],
    [
        'id'       => 'workflow.scheduled_job',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Time-based trigger job',
        'what'     => 'The scheduled job (cron/workflow_scheduled.php) that looks for contracts nearing their end date and assets nearing warranty expiry, and fires the matching triggers.',
        'why'      => 'Nothing is saved when a date quietly approaches, so without this job the expiry workflows sit there, active, and never fire.',
        'done'     => 'The time-based trigger job has run in the last 7 days.',
        'link'     => 'workflow/help.php',
        'check'    => ['sql', "SELECT COUNT(*) FROM system_settings WHERE setting_key = 'workflow_cron_last_run' AND setting_value >= UTC_TIMESTAMP() - INTERVAL 7 DAY"],
    ],

    // ── Triggers ────────────────────────────────────────────────────────────
    [
        'id'       => 'workflow.trigger_tickets',
        'module'   => 'workflow',
        'tier'     => 'recommended',
        'category' => 'automation',
        'title'    => 'Workflows on ticket events',
        'what'     => 'A workflow that runs when a ticket is created, changes status or priority, is assigned to an analyst or a team, gets a note, or is trashed or restored.',
        'why'      => 'Tickets are where most repetitive work sits. Routing a new ticket or telling a manager about a P1 the moment it lands is the classic first automation.',
        'done'     => 'At least one active workflow uses a ticket trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'ticket.%'"),
    ],
    [
        'id'       => 'workflow.trigger_reply_received',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Act on requester replies',
        'what'     => 'A workflow that runs when the requester replies to a ticket.',
        'why'      => 'A reply on a ticket waiting for the customer can move it straight back into the queue or tell the assignee, so it is not left sitting on hold.',
        'done'     => 'At least one active workflow runs when a requester replies.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event = 'ticket.reply_received'"),
    ],
    [
        'id'       => 'workflow.trigger_sla',
        'module'   => 'workflow',
        'tier'     => 'recommended',
        'category' => 'governance',
        'title'    => 'SLA warning and breach workflows',
        'what'     => 'A workflow that runs when a ticket\'s SLA is close to its deadline or has been breached. These come from the SLA breach-check scheduled job.',
        'why'      => 'Escalating or reassigning before the clock runs out is what keeps you inside your SLAs, rather than finding out from next month\'s report.',
        'done'     => 'At least one active workflow uses an SLA trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'sla.%'"),
    ],
    [
        'id'       => 'workflow.trigger_tasks',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on task events',
        'what'     => 'A workflow that runs when a task is created, assigned, commented on, changes status or due date, gains or loses a collaborator, or is completed.',
        'why'      => 'Finishing one task can kick off the next or tell whoever was waiting on it, so project work does not stall between people.',
        'done'     => 'At least one active workflow uses a task trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'task.%'"),
    ],
    [
        'id'       => 'workflow.trigger_changes',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Workflows on change requests',
        'what'     => 'A workflow that runs when a change request is created, approved or deleted.',
        'why'      => 'An approved change can notify the implementer, post to the change channel or create the tasks to carry it out, the moment the CAB says yes.',
        'done'     => 'At least one active workflow uses a change trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'change.%'"),
    ],
    [
        'id'       => 'workflow.trigger_problems',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Workflows on problems',
        'what'     => 'A workflow that runs when a problem is created, changes status or is deleted.',
        'why'      => 'Telling the owning team when a problem is raised, or when a known error gets its fix, keeps problem management moving without status meetings.',
        'done'     => 'At least one active workflow uses a problem trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'problem.%'"),
    ],
    [
        'id'       => 'workflow.trigger_forms',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on form submissions',
        'what'     => 'A workflow that runs when a form submission is received, with every answer available by its field label.',
        'why'      => 'A starter form can raise the setup tickets, create the tasks and email HR in one go, instead of someone reading each submission and doing it by hand.',
        'done'     => 'At least one active workflow runs on a form submission.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event = 'form.submitted'"),
    ],
    [
        'id'       => 'workflow.trigger_catalogue_requests',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'customer',
        'title'    => 'Catalogue request approvals',
        'what'     => 'A workflow that runs when a catalogue request is submitted for approval, approved or rejected.',
        'why'      => 'The approver is told a request is waiting and the requester is told the outcome - without these, nobody hears anything.',
        'done'     => 'At least one active workflow uses a catalogue request trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'catalogue_request.%'"),
    ],
    [
        'id'       => 'workflow.trigger_assets',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on asset assignment',
        'what'     => 'A workflow that runs when an asset is assigned to or taken back from a user.',
        'why'      => 'Handing over a laptop can create the setup task or tell the user, and taking one back can start the wipe-and-reissue steps.',
        'done'     => 'At least one active workflow runs on asset assignment.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event IN ('asset.assigned', 'asset.unassigned')"),
    ],
    [
        'id'       => 'workflow.trigger_warranty_expiring',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Warranty expiry reminders',
        'what'     => 'A time-based workflow that runs as an asset\'s warranty approaches expiry, at 90, 30, 7 and 1 days out.',
        'why'      => 'You get time to renew cover or plan a replacement, instead of finding out when a broken device turns out to be out of warranty.',
        'done'     => 'At least one active workflow uses the warranty expiring trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event = 'asset.warranty_expiring'"),
    ],
    [
        'id'       => 'workflow.trigger_contract_expiring',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Contract expiry reminders',
        'what'     => 'A time-based workflow that runs as a contract approaches its end date, at 90, 30, 7 and 1 days out.',
        'why'      => 'Renewals are decided while there is still time to negotiate or give notice, rather than rolling over by default.',
        'done'     => 'At least one active workflow uses the contract expiring trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event = 'contract.expiring'"),
    ],
    [
        'id'       => 'workflow.trigger_contracts_suppliers',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on contracts and suppliers',
        'what'     => 'A workflow that runs when a contract, supplier or supplier contact is created, updated or deleted.',
        'why'      => 'Finance or procurement can be told when a contract is added or changed without watching the Contracts module themselves.',
        'done'     => 'At least one active workflow uses a contract or supplier record trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event REGEXP '^(contract|supplier|supplier_contact)[.](created|updated|deleted)$'"),
    ],
    [
        'id'       => 'workflow.trigger_cmdb',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on CMDB changes',
        'what'     => 'A workflow that runs when a CMDB object is created, updated or deleted.',
        'why'      => 'Changes to configuration items can be announced to their owners or pushed to another system, keeping the CMDB and its consumers in step.',
        'done'     => 'At least one active workflow uses a CMDB trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'cmdb.object.%'"),
    ],
    [
        'id'       => 'workflow.trigger_knowledge',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on knowledge articles',
        'what'     => 'A workflow that runs when a knowledge article is published, updated or archived.',
        'why'      => 'The team hears about a new fix the day it is written, instead of solving the same problem again from scratch.',
        'done'     => 'At least one active workflow uses a knowledge trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'knowledge.%'"),
    ],
    [
        'id'       => 'workflow.trigger_service_status',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Workflows on status-page incidents',
        'what'     => 'A workflow that runs when a status-page incident is opened, updated, resolved or deleted.',
        'why'      => 'An outage posted once can be pushed to Teams, Slack or an email list at the same moment, so everybody hears the same thing.',
        'done'     => 'At least one active workflow uses a service status trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'service_status.%'"),
    ],
    [
        'id'       => 'workflow.trigger_morning_checks',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on morning check results',
        'what'     => 'A workflow that runs when a morning check result is recorded.',
        'why'      => 'A failed backup or a red check can raise a ticket or alert someone straight away, rather than waiting for somebody to read the board.',
        'done'     => 'At least one active workflow runs when a morning check is recorded.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event = 'morning_check.recorded'"),
    ],
    [
        'id'       => 'workflow.trigger_software_discovered',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Alert on newly discovered software',
        'what'     => 'A workflow that runs when the software inventory discovers an application it has not seen before.',
        'why'      => 'Unapproved or unlicensed software is noticed the day it appears on a machine, not at the next audit.',
        'done'     => 'At least one active workflow runs when new software is discovered.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event = 'software.application_discovered'"),
    ],
    [
        'id'       => 'workflow.trigger_tracker',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Workflows on tracker updates',
        'what'     => 'A workflow that runs when a ticket is linked to a Jira or Azure DevOps issue, or when that issue changes status or gets a comment (found by the tracker poll).',
        'why'      => 'When development marks a bug done, the ticket can move on and the requester be told, without an analyst watching the tracker.',
        'done'     => 'At least one active workflow uses a tracker trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event LIKE 'tracker.%'"),
    ],
    [
        'id'       => 'workflow.trigger_other_records',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows on other records',
        'what'     => 'A workflow that runs when a calendar event, monitored service, morning check, software licence or network diagram is created, updated or deleted.',
        'why'      => 'Changes in the smaller modules can be announced or passed to another system in the same way as tickets.',
        'done'     => 'At least one active workflow uses one of these record triggers.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event REGEXP '^(calendar_event|status_service|morning_check|software_licence|network_diagram)[.](created|updated|deleted)$'"),
    ],
    [
        'id'       => 'workflow.trigger_settings_changes',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Watch for settings changes',
        'what'     => 'A workflow that runs when a lookup or setting - a ticket status, priority or type, an asset type, a change or problem status, a CMDB class and so on - is created, updated or deleted.',
        'why'      => 'Someone renaming a status or deleting a priority can quietly break reports and other workflows. An alert tells you when it happens.',
        'done'     => 'At least one active workflow uses a settings trigger.',
        'link'     => 'workflow/',
        'check'    => $trigger("trigger_event REGEXP '^(ticket_status|ticket_priority|ticket_type|ticket_origin|asset_type|asset_status|asset_location|change_status|change_type|change_priority|change_impact|problem_status|problem_priority|task_status|task_priority|task_tag|cmdb_class|cmdb_property|cmdb_relationship_type|contract_status|contract_term_tab|payment_schedule|supplier_status|supplier_type|calendar_category|incident_status|impact_level|morning_check_status)[.](created|updated|deleted)$'"),
    ],

    // ── Actions ─────────────────────────────────────────────────────────────
    [
        'id'       => 'workflow.action_send_email',
        'module'   => 'workflow',
        'tier'     => 'recommended',
        'category' => 'communication',
        'title'    => 'Workflow emails',
        'what'     => 'A workflow action that sends an email - to the requester by default or to any address - with details from the event merged into the subject and body.',
        'why'      => 'Managers, approvers and requesters hear about what matters to them automatically, in words you wrote once.',
        'done'     => 'At least one active workflow sends an email.',
        'link'     => 'workflow/',
        'check'    => $action('send_email'),
    ],
    [
        'id'       => 'workflow.action_assign_ticket',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Automatic ticket assignment',
        'what'     => 'A workflow action that assigns a ticket to an analyst.',
        'why'      => 'Tickets that always go to the same person - printers to Sam, payroll to Priya - reach them without waiting for someone to triage.',
        'done'     => 'At least one active workflow assigns tickets.',
        'link'     => 'workflow/',
        'check'    => $action('assign_ticket'),
    ],
    [
        'id'       => 'workflow.action_set_status',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Automatic status changes',
        'what'     => 'A workflow action that sets a ticket\'s status.',
        'why'      => 'A ticket can move itself on - back to Open when the requester replies, or to Resolved when the linked bug is fixed - without an analyst touching it.',
        'done'     => 'At least one active workflow sets a ticket status.',
        'link'     => 'workflow/',
        'check'    => $action('set_ticket_status'),
    ],
    [
        'id'       => 'workflow.action_set_priority',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Automatic priority changes',
        'what'     => 'A workflow action that sets a ticket\'s priority.',
        'why'      => 'Tickets from VIPs, or with "down" in the subject, start at the right priority and the right SLA without relying on triage.',
        'done'     => 'At least one active workflow sets a ticket priority.',
        'link'     => 'workflow/',
        'check'    => $action('set_ticket_priority'),
    ],
    [
        'id'       => 'workflow.action_add_note',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Automatic ticket notes',
        'what'     => 'A workflow action that adds a note to a ticket.',
        'why'      => 'Instructions or context land on the ticket as it arrives - "check the VPN status page first" - so the analyst sees them where they work.',
        'done'     => 'At least one active workflow adds a ticket note.',
        'link'     => 'workflow/',
        'check'    => $action('add_ticket_note'),
    ],
    [
        'id'       => 'workflow.action_create_task',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows that create tasks',
        'what'     => 'A workflow action that creates a task, optionally assigned and linked to the ticket.',
        'why'      => 'Follow-up work - order the kit, update the asset register - is captured every time instead of depending on someone remembering.',
        'done'     => 'At least one active workflow creates a task.',
        'link'     => 'workflow/',
        'check'    => $action('create_task'),
    ],
    [
        'id'       => 'workflow.action_create_ticket',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'automation',
        'title'    => 'Workflows that raise tickets',
        'what'     => 'A workflow action that creates a ticket, with its type, priority, department and assignee set.',
        'why'      => 'A failed morning check, an expiring warranty or a form submission becomes tracked work on its own, with an owner and an SLA.',
        'done'     => 'At least one active workflow creates a ticket.',
        'link'     => 'workflow/',
        'check'    => $action('create_ticket'),
    ],
    [
        'id'       => 'workflow.action_attach_checklist',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'governance',
        'title'    => 'Checklists attached automatically',
        'what'     => 'A workflow action that attaches one or more SOP checklists to a ticket.',
        'why'      => 'A new starter or a server rebuild gets the right procedure every time, so steps are not skipped because nobody went looking for the checklist.',
        'done'     => 'At least one active workflow attaches a checklist.',
        'link'     => 'workflow/',
        'check'    => $action('attach_checklist'),
    ],
    [
        'id'       => 'workflow.action_escalate_to_tracker',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Automatic escalation to a tracker',
        'what'     => 'A workflow action that raises a Jira issue or Azure DevOps work item from a ticket, using the connection\'s project and type mapping.',
        'why'      => 'Tickets of a given type or category reach the development team as soon as they arrive, without an analyst clicking Escalate.',
        'done'     => 'At least one active workflow escalates to an issue tracker.',
        'link'     => 'workflow/',
        'check'    => $action('escalate_to_tracker'),
    ],
    [
        'id'       => 'workflow.action_note_to_tracker',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Notes sent to the tracker',
        'what'     => 'A workflow action that posts a comment on the issue linked to a ticket.',
        'why'      => 'When the requester adds information, the developer working the issue sees it in their own tool.',
        'done'     => 'At least one active workflow sends a note to an issue tracker.',
        'link'     => 'workflow/',
        'check'    => $action('send_note_to_tracker'),
    ],
    [
        'id'       => 'workflow.webhook_slack',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Post to Slack',
        'what'     => 'A workflow webhook using the Slack format, which posts a message to a Slack channel through an incoming webhook.',
        'why'      => 'The team sees new P1s, breaches or outages in the channel they already watch, and can react in seconds.',
        'done'     => 'At least one active workflow sends a Slack webhook.',
        'link'     => 'workflow/',
        'check'    => $preset('slack'),
    ],
    [
        'id'       => 'workflow.webhook_teams',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Post to Microsoft Teams',
        'what'     => 'A workflow webhook using the Microsoft Teams format, which posts a message card to a Teams channel.',
        'why'      => 'In a Microsoft shop, alerts reach people in Teams, where they are, rather than in an inbox they check twice a day.',
        'done'     => 'At least one active workflow sends a Teams webhook.',
        'link'     => 'workflow/',
        'check'    => $preset('teams'),
    ],
    [
        'id'       => 'workflow.webhook_discord',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'communication',
        'title'    => 'Post to Discord',
        'what'     => 'A workflow webhook using the Discord format, which posts a message to a Discord channel.',
        'why'      => 'Teams that run on Discord get the same instant alerts as a Slack or Teams shop.',
        'done'     => 'At least one active workflow sends a Discord webhook.',
        'link'     => 'workflow/',
        'check'    => $preset('discord'),
    ],
    [
        'id'       => 'workflow.webhook_full_record',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Full-record webhooks',
        'what'     => 'A workflow webhook that sends the whole object as JSON - the same shape as the REST API - to any URL.',
        'why'      => 'Another system, Zapier or Make gets everything about the ticket in one push, with no polling and no payload to design.',
        'done'     => 'At least one active workflow sends a full-record webhook.',
        'link'     => 'workflow/',
        'check'    => $preset('full'),
    ],
    [
        'id'       => 'workflow.webhook_custom_json',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'integrations',
        'title'    => 'Custom JSON webhooks',
        'what'     => 'A workflow webhook whose body is JSON you write yourself, with event details merged in, for systems such as PagerDuty that expect an exact shape.',
        'why'      => 'Almost any tool with an incoming webhook can be driven from FreeITSM, without waiting for a built-in connector.',
        'done'     => 'At least one active workflow sends a custom JSON webhook.',
        'link'     => 'workflow/',
        'check'    => $preset('custom'),
    ],
    [
        'id'       => 'workflow.webhook_signed',
        'module'   => 'workflow',
        'tier'     => 'extra',
        'category' => 'security',
        'title'    => 'Signed webhooks',
        'what'     => 'A signing secret on a workflow webhook, so each request carries a signature the receiving system can check.',
        'why'      => 'The receiver can prove a request really came from your FreeITSM and was not forged by someone who found the URL.',
        'done'     => 'At least one active workflow webhook has a signing secret.',
        'link'     => 'workflow/',
        'check'    => ['rows', 'workflows', "$live AND actions LIKE '%\"type\":\"send_webhook\"%' AND actions REGEXP '\"secret\":\"[^\"]'"],
    ],
];
