<?php

return [
    'root' => dirname(__DIR__, 2),
    'session' => [
        'cookie' => env('LEGACY_SESSION_COOKIE', 'PHPSESSID'),
        'path' => env('LEGACY_SESSION_PATH'),
        'file_prefix' => env('LEGACY_SESSION_FILE_PREFIX', 'sess_'),
    ],
    'modules' => [
        'tickets',
        'asset-management',
        'knowledge',
        'change-management',
        'problem-management',
        'tasks',
        'workflow',
        'cmdb',
        'calendar',
        'reporting',
        'forms',
        'contracts',
        'domains',
        'people',
        'service-status',
        'war-room',
        'lms',
        'system',
        'watchtower',
        'self-service',
        'software',
        'checklists',
        'network-mapper',
        'process-mapper',
        'morning-checks',
        'auth',
    ],
    'aliases' => [
        'assets' => 'asset-management',
        'changes' => 'change-management',
        'problems' => 'problem-management',
        'status' => 'service-status',
        'kb' => 'knowledge',
        'wiki' => 'system-wiki',
    ],
    'default_entrypoint' => 'index.php',
];
