<?php

return [
    'root' => dirname(__DIR__, 2),
    'modules' => [
        'tickets',
        'asset-management',
        'knowledge',
        'change-management',
        'problem-management',
        'tasks',
        'workflow',
        'cmdb',
        'calendar',
        'reporting',
        'forms',
        'contracts',
        'domains',
        'people',
        'service-status',
        'war-room',
        'lms',
        'system',
        'watchtower',
        'self-service',
        'software',
        'checklists',
        'network-mapper',
        'process-mapper',
        'morning-checks',
        'auth',
    ],
    'default_entrypoint' => 'index.php',
];
