#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

$autoload = __DIR__ . '/vendor/autoload.php';
if (!file_exists($autoload)) {
    fwrite(STDERR, "Laravel dependencies are not installed. Run: cd /home/runner/work/Teste/Teste/laravel && composer install\n");
    exit(1);
}

require $autoload;

$app = require_once __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput());

exit($status);
